In [1]:
import pandas as pd
import numpy as np
import math
import re
from numpy.linalg import norm
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import random
import pickle

In [2]:
import nltk

In [3]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\deepak\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\deepak\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\deepak\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [4]:
import spacy
from nltk.tokenize import sent_tokenize

C:\ProgramData\Anaconda3\envs\MS_Pytorch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
#https://huggingface.co/docs/transformers/installation
#!pip install transformers[torch]
from transformers import AutoTokenizer, BertTokenizer, BertModel, LongformerTokenizer, LongformerModel
from sentence_transformers import SentenceTransformer
import torch
import networkx as nx
import gensim
import gensim.corpora as corpora

In [6]:
from sklearn.cluster import KMeans
from nltk.cluster import KMeansClusterer
from nltk.stem import WordNetLemmatizer
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import MeanShift
from scipy.spatial import distance,distance_matrix
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.metrics import r2_score, mean_squared_error
from xgboost import XGBRegressor

In [7]:
from rouge import Rouge

In [8]:
import warnings
warnings.filterwarnings('ignore')

#### Download the CNN/Daily Mail dataset

In [9]:
#https://huggingface.co/datasets/viewer/?dataset=cnn_dailymail&config=3.0.0
#!pip install datasets
from datasets import load_dataset
dataset = load_dataset('cnn_dailymail', '3.0.0')

Found cached dataset cnn_dailymail (C:/Users/deepak/.cache/huggingface/datasets/cnn_dailymail/3.0.0/3.0.0/1b3c71476f6d152c31c1730e83ccb08bcf23e348233f4fcc11e182248e6bf7de)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.01it/s]

In [10]:
dataset

DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 287113
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 13368
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 11490
    })
})

In [11]:
#dataset.save_to_disk("path/to/dataset/directory")
#dataset = load_from_disk('path/to/dataset/directory')

In [12]:
dataset["train"].shape[0]

287113

In [13]:
sample_idx=random.sample(range(dataset["train"].shape[0]),2000)
if 0 not in sample_idx:
    sample_idx=[0]+sample_idx
print(sample_idx)

[0, 5259, 186792, 91215, 197071, 102107, 158378, 163422, 243, 87638, 28945, 192825, 260017, 83444, 17119, 65735, 166414, 216621, 87603, 106711, 65552, 258661, 218408, 242208, 185665, 126700, 76835, 85294, 199541, 44348, 88568, 149761, 92568, 42371, 282933, 40475, 133620, 263124, 54610, 210093, 1976, 138667, 215047, 192113, 84528, 144495, 266672, 58860, 137711, 51231, 236532, 157856, 119652, 170801, 214497, 98101, 89236, 43613, 107413, 99964, 61921, 98488, 144461, 152545, 83250, 258127, 33771, 247813, 113041, 64535, 53861, 72339, 29453, 43936, 47725, 226538, 129738, 191321, 188325, 58027, 210880, 130839, 227685, 187587, 185528, 202039, 86585, 285713, 168811, 184242, 150549, 284057, 222151, 237510, 267641, 130671, 171639, 256449, 153759, 60519, 19220, 198711, 209232, 116722, 92419, 51998, 256311, 109308, 26021, 193966, 113322, 218470, 168184, 25525, 24066, 161365, 46111, 233249, 69371, 263381, 7128, 25994, 206278, 206789, 243771, 147164, 34371, 89829, 114881, 263476, 78436, 70946, 236468, 16579, 204325, 70125, 102255, 37162, 200511, 160201, 62894, 134852, 193324, 276662, 185116, 73927, 92868, 56187, 188581, 218504, 187108, 15074, 163630, 175244, 191855, 11302, 260432, 278302, 254742, 105805, 124012, 142012, 157231, 115666, 10863, 134575, 214560, 58574, 154685, 158321, 18309, 15755, 67609, 145278, 64690, 123147, 134546, 64209, 202255, 130185, 240358, 99828, 266165, 22055, 238351, 108869, 176662, 8419, 237496, 6947, 48117, 21683, 63770, 96299, 10380, 61238, 156529, 245355, 215300, 100449, 283727, 78793, 40651, 273285, 14903, 7500, 259228, 241089, 115422, 183952, 146252, 270011, 182014, 201862, 122531, 73213, 53289, 233546, 196053, 91145, 248660, 74154, 72032, 90416, 149459, 131034, 11625, 56969, 226315, 104620, 192499, 77722, 1, 128159, 79300, 22144, 28349, 209566, 117612, 210848, 180311, 24408, 201276, 247896, 182822, 236450, 188699, 22689, 93073, 174496, 165709, 82510, 96973, 181514, 103492, 117314, 272517, 204832, 98561, 212084, 452, 15208, 110123, 37589, 252130, 148659, 240543, 72985, 81743, 74237, 218224, 225382, 53110, 97776, 35709, 18054, 115553, 22228, 282955, 147522, 104214, 159378, 285131, 26115, 232797, 120831, 195995, 169037, 77849, 43783, 34518, 96074, 101366, 86540, 179543, 135638, 206332, 25508, 112503, 65891, 207288, 269225, 21362, 96192, 221901, 170382, 69978, 61476, 56446, 237008, 102996, 269053, 74601, 15260, 248650, 78560, 281335, 282335, 40842, 190717, 59203, 283169, 189564, 115300, 226518, 10676, 200900, 92447, 82735, 14202, 54481, 3532, 241213, 1063, 223916, 115165, 102534, 242074, 194031, 7137, 239257, 49322, 89883, 68573, 170405, 239639, 36547, 250263, 6685, 215457, 271764, 229279, 143688, 48949, 206556, 182538, 65316, 235475, 196496, 135285, 38847, 216286, 61471, 87709, 249611, 171891, 53891, 101169, 259954, 243970, 171554, 34561, 42023, 217700, 163469, 12806, 19945, 162579, 77889, 198225, 95446, 153814, 124519, 122862, 74990, 193913, 283726, 62735, 50111, 91082, 81820, 261255, 237498, 181403, 49036, 201145, 2809, 112604, 158240, 97240, 145122, 229711, 23881, 105984, 87926, 267301, 108246, 54680, 239966, 125012, 138625, 157891, 95843, 205519, 32984, 83438, 22281, 202646, 25111, 230170, 189387, 251225, 176884, 273692, 227141, 267036, 261212, 250826, 134328, 23722, 13903, 68668, 93112, 19464, 127060, 161315, 115896, 145576, 174095, 58858, 119805, 161956, 68593, 8134, 192246, 199319, 45174, 105775, 142862, 26159, 170357, 218558, 151780, 67891, 98228, 107309, 220461, 213287, 167151, 183187, 103008, 285547, 220172, 105695, 168842, 148841, 270880, 182539, 152609, 284155, 4047, 78513, 67745, 207440, 161777, 286166, 29211, 82498, 181045, 64857, 248472, 108427, 124383, 278759, 188818, 140188, 197964, 86735, 20359, 82775, 158425, 257197, 257844, 140775, 245164, 173434, 231911, 89311, 94224, 204, 31278, 244064, 54828, 100152, 239936, 241309, 229641, 223747, 103746, 23899, 121061, 128367, 887, 14082, 283605, 256734, 185923, 187695, 163163, 272419, 218323, 147507, 271762, 27414, 242936, 53204, 57896, 196091, 234076, 151625, 90773, 136490, 167651, 215494, 16826, 122151, 205399, 187274, 274997, 227203, 57884, 12839, 245895, 99666, 192489, 194746, 242481, 228838, 55595, 252958, 198857, 82034, 152463, 140455, 68118, 50241, 130456, 139221, 19448, 180089, 103643, 165556, 163778, 49655, 265154, 235512, 140719, 229232, 48781, 9374, 256339, 249959, 240878, 279831, 3260, 180501, 30604, 234551, 87901, 168848, 143884, 145961, 2748, 197979, 119203, 273622, 43418, 183560, 244655, 264644, 146243, 153261, 41882, 170961, 178465, 212158, 200478, 144769, 74027, 141021, 287007, 119177, 144401, 244666, 247920, 232022, 57076, 145504, 65516, 262473, 200951, 203390, 50622, 218985, 277568, 156014, 270127, 68380, 277139, 86475, 154319, 100171, 85761, 260592, 113635, 252209, 85681, 153199, 23551, 273068, 43219, 192882, 153950, 520, 14059, 39810, 10219, 261747, 157311, 688, 145256, 61546, 286640, 55242, 174928, 42920, 270728, 147623, 42158, 260630, 85757, 246020, 217518, 274540, 142685, 1312, 46666, 189622, 231956, 28775, 187690, 118899, 104227, 170822, 139688, 267425, 131533, 175754, 74909, 133347, 77715, 77178, 274426, 134178, 102132, 161667, 43993, 234380, 175844, 273725, 209994, 149564, 78045, 57741, 25762, 80834, 72330, 126485, 197571, 248087, 91461, 283570, 50117, 191583, 77465, 40626, 10689, 5948, 64130, 52268, 194868, 269194, 176413, 108964, 39234, 264021, 67687, 79083, 246075, 264977, 144273, 88577, 225160, 11561, 208579, 248470, 21478, 275822, 67974, 92284, 58055, 11823, 72239, 122844, 210377, 71334, 2194, 129834, 189619, 204385, 217958, 168201, 244249, 61818, 217676, 162262, 179210, 286526, 100000, 219381, 251525, 269786, 202140, 39374, 269586, 26937, 187889, 234621, 131591, 63496, 11622, 56426, 94827, 230040, 72961, 134532, 52485, 121094, 207594, 158360, 29126, 11462, 119485, 43264, 85382, 245409, 178529, 134834, 99677, 69047, 268864, 263229, 48014, 236064, 77575, 204034, 231781, 89433, 147899, 25423, 129943, 41375, 238598, 51571, 67746, 78483, 77534, 8474, 277043, 232431, 139938, 94968, 261368, 40404, 196076, 200124, 228531, 110273, 79825, 46224, 281731, 228366, 150600, 58740, 34886, 137654, 204671, 99755, 201439, 281799, 166898, 149874, 155907, 166847, 201730, 127083, 128586, 49713, 161333, 162451, 142594, 217437, 35391, 70197, 122115, 55195, 60051, 88751, 241583, 57278, 183886, 255783, 255039, 183262, 231181, 221890, 20150, 176935, 38267, 203294, 139865, 108888, 64170, 61024, 255109, 269081, 77396, 31538, 246002, 237255, 124914, 258028, 228947, 268005, 272604, 52911, 34389, 246693, 127630, 158822, 281980, 48646, 226580, 195567, 155686, 238675, 48862, 229924, 277494, 136658, 169854, 182824, 117038, 102494, 29384, 192225, 252613, 78963, 233164, 110470, 71614, 77948, 236300, 67571, 56411, 5546, 123750, 121463, 214813, 268087, 144733, 56645, 53713, 78481, 51, 223161, 238611, 136111, 285980, 154415, 258411, 253518, 24924, 109535, 194040, 180377, 281485, 244754, 264323, 180447, 232885, 97677, 226287, 122593, 45470, 141763, 90216, 147431, 13084, 158590, 171841, 184734, 286916, 174158, 43049, 142173, 65533, 51017, 127850, 189486, 147673, 110434, 238222, 181408, 203594, 137027, 75562, 114020, 100426, 128578, 70550, 102549, 211653, 198924, 40959, 279003, 197515, 87466, 110179, 174777, 132420, 178635, 102353, 194177, 24806, 162205, 276271, 171640, 105415, 174409, 179897, 152580, 25694, 115646, 227952, 110081, 94577, 185892, 253444, 254812, 283270, 141989, 278966, 113755, 52486, 122583, 129642, 168275, 186111, 221675, 233285, 220387, 225127, 191549, 124902, 213262, 131171, 80648, 140519, 243720, 283195, 115401, 190437, 218623, 264783, 238647, 277128, 39501, 153655, 190850, 139267, 214003, 260594, 205618, 240943, 213154, 157503, 285575, 63504, 60437, 149560, 216435, 244228, 82752, 202084, 169371, 144036, 266538, 61305, 18963, 39404, 192993, 217481, 274951, 32276, 181633, 163389, 276475, 204825, 144810, 87057, 131205, 210844, 63115, 185815, 271372, 10490, 88570, 106468, 103723, 77766, 213189, 236106, 89232, 157461, 186181, 45874, 63165, 159922, 70594, 209066, 6461, 208128, 26238, 205908, 17055, 88698, 237386, 134899, 249059, 30165, 283462, 98367, 112985, 11245, 196530, 37807, 225826, 23498, 182391, 197724, 69076, 120591, 267302, 223224, 173316, 144428, 168688, 25013, 203528, 19812, 269388, 43758, 2462, 160170, 260375, 94253, 215886, 67529, 60882, 273126, 69427, 98015, 216291, 257856, 52109, 17276, 229226, 287038, 72824, 182417, 69791, 279328, 119826, 70502, 9066, 244812, 255406, 56837, 241537, 81423, 123895, 31655, 193622, 189893, 129294, 196086, 194153, 179250, 258051, 174268, 29098, 177211, 196431, 236711, 150019, 116540, 249858, 210354, 259148, 213203, 154204, 227507, 6719, 162364, 285881, 202008, 186107, 177294, 199482, 231802, 247888, 148534, 68850, 102830, 144454, 268141, 18869, 262405, 41328, 148070, 218153, 15573, 211, 23915, 23412, 101272, 195346, 196562, 27140, 195244, 165480, 187445, 54122, 252975, 185169, 282740, 74731, 141611, 115878, 48896, 98142, 282519, 200778, 9484, 90764, 156347, 168548, 23505, 163294, 33378, 43820, 90572, 263112, 45287, 176448, 21334, 127189, 236220, 90473, 264104, 10824, 117095, 42355, 15268, 226311, 3575, 82024, 101995, 37401, 64607, 187606, 110295, 192513, 215213, 259430, 50688, 157558, 160131, 26950, 239630, 61743, 116658, 68876, 58818, 24419, 82348, 144582, 204861, 92788, 260908, 156031, 72636, 250622, 78499, 63358, 189338, 1780, 182887, 275422, 226384, 16742, 42110, 148066, 84508, 34990, 170058, 12265, 280031, 18078, 258709, 153927, 179796, 174231, 267679, 208859, 39666, 61182, 93120, 38086, 197078, 50799, 140052, 169246, 233386, 96608, 264758, 247557, 201808, 224221, 238847, 67764, 118145, 23353, 247516, 274716, 162127, 56321, 277793, 237449, 23998, 267585, 262615, 147574, 230461, 74951, 68455, 198525, 65369, 228669, 223506, 256457, 201489, 256689, 132430, 144625, 278534, 167831, 119795, 23935, 211719, 192019, 145806, 128225, 82708, 227688, 231639, 127761, 227616, 107570, 60707, 148415, 258578, 143865, 219847, 234875, 89314, 274260, 194015, 27080, 265774, 71653, 169314, 99558, 114497, 92124, 53368, 186404, 11709, 42844, 78778, 25592, 160254, 275873, 255905, 34586, 220944, 39143, 238029, 200944, 151939, 46554, 111339, 224675, 100393, 262121, 160294, 213759, 100165, 101629, 216496, 193083, 269501, 83981, 7239, 131825, 138897, 135301, 216308, 176907, 247344, 61236, 48417, 135898, 100290, 212648, 270101, 285456, 41588, 19437, 222451, 154016, 219477, 190861, 281506, 163752, 40053, 176813, 246699, 27440, 207991, 147619, 237607, 267055, 167877, 28026, 11749, 179156, 265706, 223441, 10637, 249744, 183062, 235220, 15156, 261863, 194672, 217825, 125940, 70860, 153322, 89857, 123887, 172523, 17631, 106631, 213536, 139923, 116884, 209613, 248886, 190740, 267861, 182172, 250745, 110172, 149725, 67617, 285068, 131092, 19558, 37637, 153745, 27538, 27197, 448, 13012, 153362, 23204, 237152, 34309, 57387, 217096, 197973, 116038, 183951, 269918, 20334, 40496, 65596, 279155, 280556, 165337, 175326, 241019, 173421, 142351, 119682, 238631, 214535, 53633, 71459, 185740, 210753, 37689, 156093, 210941, 3393, 216267, 104347, 29204, 184030, 148656, 193608, 255267, 240285, 121512, 229728, 198444, 40565, 263104, 145643, 179638, 178593, 158619, 63618, 127168, 49707, 75137, 140243, 235093, 164914, 273157, 255557, 169978, 36379, 38239, 213741, 247950, 32236, 237683, 157370, 262442, 116754, 44961, 268351, 155710, 90528, 286941, 216066, 196310, 143341, 32806, 181634, 36282, 257438, 227890, 134156, 123621, 75453, 84938, 260365, 46816, 260734, 37703, 271648, 253274, 12565, 64363, 4285, 181069, 129413, 27767, 32961, 152692, 156333, 179612, 56310, 49802, 178381, 217239, 270292, 108624, 269800, 10779, 104762, 118978, 257805, 210199, 233427, 258802, 240893, 84265, 131040, 20658, 175313, 33192, 223713, 170403, 51019, 110931, 13667, 69484, 110390, 112785, 240911, 254196, 25189, 274763, 115029, 18958, 91748, 229851, 276646, 17127, 19084, 62642, 57498, 279641, 120835, 185876, 762, 88461, 278385, 3993, 199174, 34426, 244185, 254114, 233415, 97210, 22104, 128973, 226988, 275982, 135284, 63055, 71917, 121627, 273896, 19662, 133572, 63565, 237576, 241462, 213445, 131949, 244869, 66299, 48810, 209341, 103885, 213846, 97125, 91509, 72108, 141215, 47966, 242567, 90271, 273969, 71484, 187449, 171264, 84555, 1855, 255645, 178368, 241706, 174090, 191548, 256811, 261662, 100070, 25869, 12086, 110455, 182570, 199193, 24232, 67015, 275701, 257363, 194807, 229951, 224763, 247340, 195973, 285625, 151545, 137993, 220030, 58591, 275092, 118406, 84550, 206694, 205923, 102727, 189112, 209676, 142318, 265339, 167709, 17723, 138664, 138279, 264640, 83759, 224503, 172186, 161503, 113963, 142129, 214823, 121708, 255792, 115178, 56630, 164575, 2150, 62932, 161585, 204240, 187443, 206414, 178299, 173481, 128934, 115110, 53217, 243996, 27985, 93847, 103565, 31468, 140384, 104327, 81756, 105691, 128663, 99533, 88104, 204012, 68089, 219809, 23356, 157543, 38641, 188542, 108921, 13340, 214590, 49875, 138671, 97752, 4820, 89342, 199476, 173220, 143358, 34153, 192984, 255301, 178363, 99219, 155781, 102712, 202047, 209297, 283549, 54522, 42072, 9985, 160250, 124740, 20412, 21506, 147816, 213107, 253800, 24629, 156187, 231637, 247947, 61846, 265418, 210057, 49202, 51845, 263634, 197998, 272468, 192002, 165240, 211348, 188248, 189037, 271406, 24340, 82437, 91998, 147188, 79919, 161876, 274570, 115009, 146991, 147177, 16867, 242620, 137357, 190624, 1189, 121112, 23920, 22041, 223679, 131572, 240130, 16055, 169659, 5276, 284345, 141569, 281244, 56765, 240626, 123831, 219935, 167454, 210944, 205865, 132396, 7891, 144554, 35768, 87124, 137812, 104198, 157373, 212958, 28949, 54709, 141126, 219947, 59717, 100741, 192905, 215716, 1600, 265981, 185789, 219972, 50126, 154389, 165889, 207935, 45416, 36954, 284673, 238971, 156519, 49119, 72107, 72945, 178366, 127497, 228897, 137873, 161664, 188700, 151670, 284180, 269027, 208362, 149237, 261335, 157748, 276696, 88846, 83910, 185479, 216431, 10159, 161996, 39868, 234951, 274639, 6330, 230492, 85210, 226708, 87103, 224721, 242242, 48789, 183743, 207997, 197898, 257370, 126061, 108168, 123692, 242252, 179891, 148777, 1266, 274366, 130650, 171537, 38357, 140316, 88323, 275109, 242294, 165538, 143795, 173380, 104925, 92156, 130244, 244794, 85895, 15682, 190499, 108348, 66064, 208004, 241739, 230354, 49595, 162324, 34616, 208062, 171340, 161682, 234518, 271609, 49445, 156724, 131160, 161600, 85219, 268638, 117005, 99390, 169148, 6228, 227431, 69670, 213692, 131782, 251657, 160903, 29093, 142075, 275000, 234158, 238124, 96150, 87065, 178565, 250101, 84470, 169846, 139827, 142670, 99056, 154283, 140325, 234357, 11536, 223660, 97641, 141468, 206207, 1141, 81843, 262647, 101598, 53109, 164634, 145228, 100765, 205043, 256553, 210099, 97783, 146285, 169963, 143454, 179111, 85850, 269779, 94125, 245621, 273431, 17956, 124873, 195322, 204625, 42799, 216427, 169872, 111857, 232854, 181240, 200763, 203770, 213321, 89955, 196528, 193792, 168360, 190079, 221445, 49106, 112769, 96836, 122002, 236087, 67421, 162422, 10550, 12084, 60210, 254892, 220704, 157735, 151702, 145221, 32544, 91709, 126068, 138143, 282992, 266586, 152496, 192843, 21036, 165022, 63086, 228733, 210112, 160941, 100354, 263998, 153377, 197424, 179565, 214869, 52851, 4288, 132368, 37648, 213561, 6680, 147251, 43487, 196238]

In [14]:
sample_idx_val=random.sample(range(dataset["validation"].shape[0]),2000)
print(sample_idx_val)

[1946, 12454, 7695, 7302, 13344, 13300, 2201, 5887, 5657, 13187, 268, 13028, 7630, 3795, 8169, 7162, 5199, 5156, 325, 11911, 9319, 5198, 9879, 4671, 13337, 11456, 12375, 5207, 3026, 893, 6528, 6027, 4118, 5226, 3736, 7903, 4538, 9014, 11388, 19, 3828, 10673, 11447, 5506, 4372, 5958, 5753, 7391, 11761, 116, 11491, 2883, 11764, 1212, 844, 6660, 5603, 9936, 2787, 3167, 10900, 2154, 1668, 12181, 8457, 12508, 5028, 8691, 2446, 2166, 4002, 8642, 4316, 5241, 6628, 2792, 4413, 1032, 11078, 4804, 10528, 1406, 5796, 1878, 3928, 6188, 9820, 2830, 8402, 7670, 7646, 11013, 5115, 7091, 444, 3532, 8027, 3875, 7100, 3675, 8674, 11860, 12636, 9543, 1564, 4788, 12893, 7731, 5377, 255, 11232, 2624, 5314, 8067, 3301, 3320, 2207, 8345, 6665, 12117, 7026, 2030, 500, 9331, 11298, 10387, 3294, 6326, 2961, 8059, 995, 4789, 6418, 932, 7176, 1820, 3649, 1596, 3510, 5274, 11521, 13013, 2926, 1785, 13065, 8563, 11915, 8618, 8019, 9728, 2617, 9035, 848, 3249, 193, 10240, 388, 11929, 3326, 8569, 2811, 506, 1813, 7805, 9641, 2266, 8055, 5432, 8708, 9199, 4189, 4832, 4651, 6925, 2317, 12921, 3979, 12162, 6604, 6680, 2255, 9152, 8804, 6683, 11713, 5357, 11039, 8698, 9778, 8975, 5851, 6635, 6603, 3436, 11243, 11123, 10656, 5057, 1998, 5567, 5247, 5450, 5763, 2681, 6320, 7149, 4284, 4813, 2326, 5869, 5901, 10973, 11028, 6441, 4409, 10056, 197, 1464, 1312, 1289, 12910, 2602, 3798, 3511, 122, 4340, 687, 12001, 5769, 10311, 12223, 11344, 12714, 5082, 8998, 4021, 5033, 12253, 341, 1374, 4348, 4270, 9634, 8021, 6177, 9225, 519, 1959, 12976, 10366, 9237, 7132, 2129, 9668, 5289, 5724, 5573, 10044, 6218, 5215, 1142, 3431, 10767, 2507, 4611, 12258, 4805, 2127, 466, 4967, 5640, 9656, 7755, 6301, 7640, 11561, 8634, 11606, 9134, 4013, 5503, 7072, 6165, 9673, 9184, 12923, 11498, 5505, 9390, 6142, 10209, 11933, 448, 2776, 891, 6849, 9265, 10677, 6579, 4979, 4010, 2559, 8828, 581, 5721, 7605, 2382, 9348, 7253, 12588, 9433, 1584, 6524, 1537, 5799, 6207, 1249, 11549, 12107, 10328, 10617, 11499, 6227, 9527, 5700, 5842, 11717, 5407, 7478, 5807, 9477, 934, 7808, 2672, 5210, 12030, 3976, 7160, 10747, 11645, 4636, 7066, 5103, 161, 531, 2215, 9957, 5480, 3164, 11149, 12159, 6079, 1972, 3899, 9534, 8930, 6916, 12732, 5911, 10415, 3807, 5341, 8747, 5831, 2708, 6200, 5871, 6548, 6917, 6800, 7508, 6518, 9583, 13319, 10675, 6269, 3943, 2430, 5014, 8373, 4095, 6881, 7033, 12873, 4084, 9549, 4432, 1550, 1228, 4014, 68, 5396, 3590, 2836, 443, 11316, 5308, 12856, 7486, 10144, 12918, 12157, 10321, 5859, 6657, 1420, 8779, 10123, 401, 11818, 11902, 10732, 12608, 10126, 10671, 11355, 5736, 11213, 837, 12585, 11895, 4695, 1343, 12888, 10113, 1367, 4722, 8522, 7260, 1060, 4390, 975, 2168, 6596, 10686, 10213, 670, 6922, 11463, 2307, 1621, 9250, 1647, 5779, 8983, 8762, 3605, 3435, 11173, 13219, 11271, 638, 3546, 5624, 6060, 12302, 6452, 4282, 12529, 1044, 10318, 11025, 467, 1836, 5409, 798, 1531, 8041, 8484, 8985, 12265, 1386, 11418, 6941, 1869, 6755, 6071, 10712, 894, 1084, 8664, 5181, 278, 11469, 4342, 9893, 12173, 9855, 10709, 10342, 1216, 2138, 2854, 11205, 8174, 3864, 3573, 7613, 453, 5523, 8422, 9039, 10480, 85, 51, 2366, 4107, 297, 8298, 9437, 3087, 1835, 1512, 8191, 8595, 7527, 12362, 602, 2450, 5079, 3868, 11379, 8966, 5043, 435, 7835, 7125, 11381, 4449, 5367, 2451, 212, 13306, 11357, 11119, 13164, 7375, 11720, 12802, 7394, 8787, 12130, 1294, 8619, 7313, 11507, 10031, 2765, 4631, 9154, 9812, 9269, 6030, 3261, 10279, 12908, 11190, 6568, 4921, 6257, 6780, 385, 10041, 7342, 1484, 9195, 2371, 9067, 10941, 4889, 5717, 4092, 5705, 7396, 11317, 6009, 8611, 7759, 8901, 12767, 10237, 13309, 2791, 3921, 9739, 7483, 11565, 88, 6206, 6652, 8029, 6138, 12634, 3005, 6316, 7525, 8335, 1165, 9836, 12538, 8312, 12605, 9455, 11208, 10117, 7521, 3643, 1150, 10935, 12678, 4160, 11653, 7905, 3655, 3033, 6024, 9028, 6464, 967, 10572, 4996, 7491, 3097, 4521, 2966, 2621, 2578, 11171, 7275, 9317, 3085, 2103, 6926, 12442, 11833, 7519, 5054, 9606, 9245, 6297, 6661, 5761, 1262, 12641, 8752, 3342, 5352, 5119, 8367, 13330, 9733, 245, 10933, 5545, 2448, 8254, 189, 11164, 1609, 5642, 1241, 6578, 8723, 4905, 4755, 1755, 7566, 3384, 5965, 8888, 8156, 3978, 3443, 4286, 9432, 5075, 10659, 5579, 7452, 3410, 2429, 4177, 13038, 4352, 5773, 7454, 6767, 10579, 6499, 3150, 3981, 692, 7183, 3741, 9959, 4784, 8012, 13184, 12638, 1795, 4046, 9261, 12388, 10450, 657, 13275, 1519, 4750, 8518, 6516, 4216, 6688, 450, 11681, 1793, 291, 8303, 1930, 7802, 6004, 118, 3101, 2662, 3948, 9114, 1543, 5509, 2309, 2041, 10403, 1057, 3373, 9018, 13145, 6394, 2032, 1993, 5483, 8121, 4623, 2413, 7639, 12194, 3704, 4172, 1994, 6131, 5695, 6471, 2689, 5063, 5538, 6480, 12427, 5224, 9196, 11922, 1588, 433, 10408, 3453, 1174, 3705, 8375, 11839, 4798, 4079, 5962, 5365, 13136, 11221, 546, 9084, 11854, 12834, 8631, 2434, 3625, 3918, 10276, 11702, 4878, 10967, 6900, 8468, 2224, 2877, 6059, 8070, 4689, 2597, 13207, 5546, 2976, 8880, 5495, 2298, 9762, 2631, 5157, 8365, 5411, 9108, 11601, 1912, 2560, 4593, 5501, 12889, 1097, 7775, 521, 9448, 6275, 5975, 10016, 7644, 5235, 10453, 4492, 10499, 3154, 5605, 1600, 6995, 12713, 554, 8397, 8829, 7024, 2525, 10540, 8026, 1889, 5385, 1382, 11464, 12800, 3051, 929, 8947, 11011, 4840, 13214, 8166, 1156, 10683, 10894, 11932, 12611, 8410, 6948, 11032, 10446, 2669, 1111, 8722, 13071, 7721, 7357, 6225, 8037, 13304, 5238, 971, 6160, 2773, 11323, 12232, 5998, 3195, 6096, 9930, 5610, 10061, 9311, 9478, 12787, 8212, 13112, 3815, 12745, 7661, 9824, 9001, 11186, 12236, 952, 7963, 961, 9662, 8663, 8895, 6743, 13215, 8910, 3270, 5009, 9013, 446, 12023, 6842, 1595, 9049, 7584, 11364, 2659, 8477, 576, 4060, 10604, 1554, 12209, 13151, 5123, 1190, 191, 2253, 11954, 5112, 1945, 1879, 2482, 4707, 7339, 9833, 12079, 13266, 7077, 206, 4509, 11545, 5552, 10423, 10526, 7248, 8703, 3013, 1211, 10007, 869, 4868, 6977, 1287, 3140, 1074, 9163, 2806, 9430, 12848, 6369, 11759, 1951, 71, 9169, 7301, 12930, 4888, 13076, 3258, 5229, 12832, 6532, 8025, 8627, 11266, 5272, 7291, 996, 4980, 8927, 6877, 10109, 4319, 4421, 11137, 10234, 6951, 397, 8479, 7586, 10602, 10092, 1673, 845, 13032, 8700, 3331, 4554, 1666, 12764, 4849, 3874, 8264, 855, 10983, 6379, 6482, 1200, 5890, 352, 9588, 726, 8805, 7660, 5711, 7348, 8074, 1441, 6534, 2169, 2354, 6229, 5351, 11201, 7402, 86, 9875, 5223, 8389, 12479, 5788, 12148, 1189, 6390, 1871, 2391, 11424, 2633, 235, 13008, 12172, 1819, 4823, 4643, 9769, 4070, 7954, 9627, 4345, 3865, 12122, 4714, 12540, 5528, 3412, 4386, 12770, 6357, 5755, 6087, 12071, 12701, 12551, 9472, 2900, 3181, 12955, 3404, 6234, 3201, 4235, 7097, 2043, 5961, 11326, 8476, 3715, 5886, 13004, 21, 1183, 8292, 12436, 10812, 6526, 9489, 2699, 5084, 5861, 8178, 4247, 13102, 5393, 1656, 9800, 2977, 2764, 12095, 8491, 3330, 2546, 1040, 6410, 4899, 8755, 8920, 2612, 11543, 8777, 946, 1957, 953, 6322, 9106, 637, 2431, 7563, 4733, 8253, 13066, 5692, 689, 6475, 9937, 9050, 11893, 6507, 6450, 12324, 1012, 9485, 8760, 5475, 2125, 13268, 12698, 12749, 3695, 4701, 8197, 5315, 13365, 4091, 3768, 9665, 12433, 5310, 3908, 10740, 1247, 587, 12571, 1261, 1545, 7200, 3266, 8279, 9135, 11741, 7252, 10076, 7735, 222, 3060, 3941, 6280, 6885, 2565, 10643, 482, 5436, 5313, 10424, 6671, 8016, 10810, 10407, 5064, 5068, 6043, 4416, 2927, 9842, 4404, 2193, 4471, 12267, 12515, 4441, 8247, 11707, 8881, 4940, 9792, 9322, 10689, 11154, 7170, 1488, 9274, 8196, 10490, 12138, 5035, 9246, 3502, 9244, 560, 7618, 8408, 4964, 74, 13205, 12792, 10460, 4992, 7107, 9059, 8558, 555, 3223, 77, 1558, 3231, 8354, 3932, 5363, 2447, 6119, 11010, 1751, 6153, 846, 4723, 12509, 4388, 3666, 12399, 12365, 1725, 11998, 6403, 3572, 3239, 11342, 10085, 9122, 7328, 5400, 3747, 7939, 12050, 10543, 4621, 11829, 10964, 5099, 13031, 5873, 3481, 9376, 13290, 12017, 12817, 9846, 9110, 12449, 822, 8810, 4985, 10111, 2634, 12654, 1997, 11989, 9183, 8090, 10791, 3525, 697, 664, 3885, 2196, 9127, 3190, 1538, 6955, 7856, 7479, 3497, 805, 5431, 480, 5024, 5803, 4207, 4489, 7879, 1105, 6656, 5016, 12557, 2369, 4753, 4110, 3035, 9837, 13202, 3027, 6164, 5203, 1305, 7843, 1860, 7241, 3528, 9249, 2293, 9687, 5996, 10136, 3527, 12140, 5836, 6535, 5067, 5080, 2784, 12523, 8129, 1511, 10045, 1530, 11370, 1350, 10462, 4572, 1576, 5527, 4297, 12228, 6069, 8386, 8324, 1067, 2704, 4209, 7589, 8275, 10018, 7535, 7307, 9426, 10030, 3402, 6367, 10548, 9541, 8199, 1194, 12260, 8014, 8159, 2960, 1711, 5957, 5293, 4772, 2884, 10466, 11473, 2782, 12615, 10603, 6626, 7085, 9146, 12202, 6752, 8993, 386, 5696, 1412, 7492, 378, 8922, 1812, 6127, 3117, 7677, 10549, 3335, 2110, 2756, 9105, 3639, 6426, 8840, 12847, 5227, 8349, 9561, 11667, 1082, 5520, 6572, 3930, 9038, 9357, 7322, 10121, 10399, 2357, 1175, 3892, 8771, 8380, 52, 11840, 5484, 6971, 11286, 10715, 10388, 778, 4649, 7990, 13323, 5623, 5731, 7795, 11583, 8651, 396, 12284, 1363, 1070, 3028, 5944, 7786, 993, 1884, 1456, 9713, 13078, 12052, 1304, 2463, 4693, 8274, 3271, 11551, 6491, 7885, 12575, 421, 3222, 4900, 6887, 7265, 5354, 6599, 6221, 11255, 10706, 10621, 1990, 1796, 4844, 8566, 9176, 1784, 2205, 4100, 1652, 10697, 5659, 10075, 9795, 9166, 4741, 9294, 5673, 12982, 3341, 8808, 8448, 2180, 3194, 1061, 4676, 12808, 10840, 12526, 10825, 7061, 2813, 2123, 4147, 2121, 2102, 2740, 12874, 7245, 10719, 3698, 3635, 1536, 10285, 1540, 9715, 2397, 11938, 3534, 8525, 11639, 11353, 9571, 8564, 9909, 2070, 2913, 5906, 1599, 11022, 831, 10392, 10688, 7907, 3663, 2077, 4584, 8678, 4796, 8854, 10885, 4344, 11845, 6706, 5369, 11775, 569, 2379, 13303, 4972, 10616, 11407, 1306, 11077, 12527, 11809, 12161, 3834, 8600, 1157, 12652, 5004, 6492, 1691, 8134, 2757, 2411, 2746, 4585, 9416, 10281, 1000, 3089, 7656, 8608, 7280, 3108, 8581, 12754, 5395, 5140, 3593, 9667, 10377, 5175, 10038, 7822, 5452, 2216, 2934, 10612, 12349, 650, 7608, 11680, 5687, 9766, 4539, 2768, 4452, 877, 4229, 1160, 7238, 4289, 1622, 10605, 2502, 6946, 2781, 4605, 2880, 1625, 12882, 8318, 8968, 11410, 12979, 6380, 4809, 2705, 4143, 4360, 7092, 6296, 8737, 7303, 12503, 8995, 8202, 11194, 5691, 12633, 10580, 11142, 7768, 5150, 4971, 7262, 155, 3285, 12688, 615, 3794, 12907, 2851, 7074, 3786, 2941, 332, 6563, 1477, 5481, 10069, 6343, 6956, 463, 11580, 10707, 12257, 7240, 4512, 5929, 10472, 1814, 4197, 1153, 641, 13234, 3568, 4273, 5039, 2643, 12926, 947, 5521, 3671, 10692, 5410, 11226, 11708, 7596, 7095, 11308, 23, 338, 5300, 5976, 5586, 4074, 10982, 3399, 3793, 9763, 1483, 3, 8510, 12558, 2800, 3914, 7232, 8552, 8990, 8951, 1581, 6327, 859, 419, 2953, 879, 8360, 2246, 9572, 11888, 1421, 7598, 8933, 6642, 983, 8080, 1043, 8649, 12870, 166, 1986, 3440, 6104, 7614, 4925, 8885, 1297, 7310, 9834, 3391, 10901, 12065, 10559, 11934, 5433, 3757, 5220, 10442, 1787, 11027, 10658, 8992, 9130, 11864, 7048, 35, 6196, 6338, 1223, 6930, 1051, 375, 3772, 13039, 12264, 11560, 8519, 7318, 11446, 10176, 3092, 7165, 7151, 7081, 6489, 12594, 13295, 3831, 9663, 3531, 5827, 502, 11467, 10792, 5232, 2607, 27, 11362, 5089, 6589, 10788, 13324, 13114, 3508, 8241, 5403, 7473, 7838, 9475, 11435, 8334, 4044, 6999, 8140, 8244, 4573, 10654, 3046, 13362, 7569, 1706, 6586, 10361, 4645, 7442, 8568, 7594, 8791, 9218, 9538, 4086, 2012, 9790, 2250, 5679, 1009, 5845, 11488, 6949, 8500, 477, 4821, 7576, 5047, 611, 4624, 12483, 2698, 10439, 2695, 9040, 11130, 11215, 6400, 7564, 2033, 812, 247, 3983, 1149, 4794, 12094, 9342, 1268, 3142, 9109, 4239, 13196, 1881, 7037, 9096, 8637, 3937, 11496, 9787, 3870, 5758, 2040, 5690, 548, 3796, 12964, 11430, 5526, 10881, 12029, 3738, 10703, 1553, 13147, 5006, 9323, 5853, 8567, 9832, 13087, 3439, 442, 5587, 4102, 5614, 12898, 6958, 4318, 2244, 1383, 5644, 36, 12985, 3211, 3212, 9405, 13218, 392, 9817, 6776, 10296, 1732, 12103, 7785, 8245, 7383, 8739, 7998, 8557, 7782, 3503, 764, 12080, 7249, 4475, 6876, 7547, 119, 9705, 9445, 8493, 7395, 5652, 10024, 5376, 1475, 3298, 13231, 8728, 194, 3857, 9985, 614, 5333, 6412, 1831, 4731, 6381, 6056, 9708, 1942, 6766, 8532, 357, 4105, 1753, 7373, 1743, 11737, 5497, 11270, 9178, 11229, 6973, 4196, 11517, 10000, 7192, 6552, 3213, 10077, 5908, 10865, 5806, 2804, 8287, 10241, 1248, 8688, 6725, 2564, 8958, 12233, 2648, 2540, 67, 3424, 7966, 2947, 7852, 6505, 12974, 175, 6859, 1887, 8321, 1815, 1759, 3460, 1208, 8579, 5074, 10228, 5609, 8833, 1974, 9676, 4742, 4609, 13101, 10280, 11700, 12432, 7884, 6936, 6654, 9808, 8157, 11050, 3670, 11855, 1391, 10763, 10955]

In [15]:
sample_idx[14]

17119

In [16]:
dataset_sample=dataset["train"][sample_idx]
len(dataset_sample['article'])

2001

In [17]:
dataset_sample_val=dataset["validation"][sample_idx_val]
len(dataset_sample_val['article'])

2000

In [18]:
dataset["train"][0]

{'article': 'LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won\'t cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don\'t plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don\'t think I\'ll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how he\'ll mark his landmark birthday are under wraps. His agent and publicist had no comment on his plans. "I\'ll definitely have some sort of party," he said in an interview. "Hopefully none of you will be reading about it." Radcliffe\'s earnings from the first five Potter films have been held in a trust fund which he has not been able to touch. Despite his growing fame and riches, the actor says he is keeping his feet firmly on the ground. "People are always looking to say \'kid star goes off the rails,\'" he told reporters last month. "But I try very hard not to go that way because it would be too easy for them." His latest outing as the boy wizard in "Harry Potter and the Order of the Phoenix" is breaking records on both sides of the Atlantic and he will reprise the role in the last two films.  Watch I-Reporter give her review of Potter\'s latest » . There is life beyond Potter, however. The Londoner has filmed a TV movie called "My Boy Jack," about author Rudyard Kipling and his son, due for release later this year. He will also appear in "December Boys," an Australian film about four boys who escape an orphanage. Earlier this year, he made his stage debut playing a tortured teenager in Peter Shaffer\'s "Equus." Meanwhile, he is braced for even closer media scrutiny now that he\'s legally an adult: "I just think I\'m going to be more sort of fair game," he told Reuters. E-mail to a friend . Copyright 2007 Reuters. All rights reserved.This material may not be published, broadcast, rewritten, or redistributed.',
 'highlights': "Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .\nYoung actor says he has no plans to fritter his cash away .\nRadcliffe's earnings from first five Potter films have been held in trust fund .",
 'id': '42c027e4ff9730fbb3de84c1af0d2c506e41c3e4'}

In [19]:
dataset["train"][1]

{'article': 'Editor\'s note: In our Behind the Scenes series, CNN correspondents share their experiences in covering news and analyze the stories behind the events. Here, Soledad O\'Brien takes users inside a jail where many of the inmates are mentally ill. An inmate housed on the "forgotten floor," where many mentally ill inmates are housed in Miami before trial. MIAMI, Florida (CNN) -- The ninth floor of the Miami-Dade pretrial detention facility is dubbed the "forgotten floor." Here, inmates with the most severe mental illnesses are incarcerated until they\'re ready to appear in court. Most often, they face drug charges or charges of assaulting an officer --charges that Judge Steven Leifman says are usually "avoidable felonies." He says the arrests often result from confrontations with police. Mentally ill people often won\'t do what they\'re told when police arrive on the scene -- confrontation seems to exacerbate their illness and they become more paranoid, delusional, and less likely to follow directions, according to Leifman. So, they end up on the ninth floor severely mentally disturbed, but not getting any real help because they\'re in jail. We toured the jail with Leifman. He is well known in Miami as an advocate for justice and the mentally ill. Even though we were not exactly welcomed with open arms by the guards, we were given permission to shoot videotape and tour the floor.  Go inside the \'forgotten floor\' » . At first, it\'s hard to determine where the people are. The prisoners are wearing sleeveless robes. Imagine cutting holes for arms and feet in a heavy wool sleeping bag -- that\'s kind of what they look like. They\'re designed to keep the mentally ill patients from injuring themselves. That\'s also why they have no shoes, laces or mattresses. Leifman says about one-third of all people in Miami-Dade county jails are mentally ill. So, he says, the sheer volume is overwhelming the system, and the result is what we see on the ninth floor. Of course, it is a jail, so it\'s not supposed to be warm and comforting, but the lights glare, the cells are tiny and it\'s loud. We see two, sometimes three men -- sometimes in the robes, sometimes naked, lying or sitting in their cells. "I am the son of the president. You need to get me out of here!" one man shouts at me. He is absolutely serious, convinced that help is on the way -- if only he could reach the White House. Leifman tells me that these prisoner-patients will often circulate through the system, occasionally stabilizing in a mental hospital, only to return to jail to face their charges. It\'s brutally unjust, in his mind, and he has become a strong advocate for changing things in Miami. Over a meal later, we talk about how things got this way for mental patients. Leifman says 200 years ago people were considered "lunatics" and they were locked up in jails even if they had no charges against them. They were just considered unfit to be in society. Over the years, he says, there was some public outcry, and the mentally ill were moved out of jails and into hospitals. But Leifman says many of these mental hospitals were so horrible they were shut down. Where did the patients go? Nowhere. The streets. They became, in many cases, the homeless, he says. They never got treatment. Leifman says in 1955 there were more than half a million people in state mental hospitals, and today that number has been reduced 90 percent, and 40,000 to 50,000 people are in mental hospitals. The judge says he\'s working to change this. Starting in 2008, many inmates who would otherwise have been brought to the "forgotten floor"  will instead be sent to a new mental health facility -- the first step on a journey toward long-term treatment, not just punishment. Leifman says it\'s not the complete answer, but it\'s a start. Leifman says the best part is that it\'s a win-win solution. The patients win, the families are relieved, and the state saves money by simply not cycling these prisoners through again and again. And, for Leifman, justice is served. E-mail to a friend .',
 'highlights': 'Mentally ill inmates in Miami are housed on the "forgotten floor"\nJudge Steven Leifman says most are there as a result of "avoidable felonies"\nWhile CNN tours facility, patient shouts: "I am the son of the president"\nLeifman says the system is unjust and he\'s fighting for change .',
 'id': 'ee8871b15c50d0db17b0179a6d2beab35065f1e9'}

In [20]:
#article0=dataset["train"][0]['article']
article0=dataset["train"][203704]['article']
#article0=dataset["train"][222893]['article']
article0

"Lionel Messi will sign a new contract at Barcelona, making him the best-paid player in the world, before the end of the week. The player’s father met with the club officials Javier Faus and Antoni Rossich last week and effectively closed the deal which will keep the player, who will be 27 in June, at the club until 2018. Messi’s £200m buy-out clause will remain but the player’s wages are expected to rise to £15.5m net which will take him beyond Cristiano Ronaldo who earns £15m a season at Real Madrid. New deal: Barcelona star Lionel Messi is set to sign a new contract with the Catalan club . Close: Messi (left) could still be a La Liga winner this season if his side can defeat Atletico Madrid . With the complexity of bonuses and add-ons the gap between world football’s top two will be minimal but Barca will now have bragging rights over Madrid until the capital club makes its next move. Barcelona had planned to announce the new deal at the weekend but the unexpected prospect of winning the league on Saturday if they beat Atletico Madrid at home could even bring the announcement forward to Wednesday or Thursday. As well as being the world’s top two players Messi and Ronaldo are La Liga’s commercial colossi generating more money for their respective clubs than most of the rest of the league combined and due to an important change in Messi’s new deal Barca will now be better placed to tap-in to that money stream as for the first time since signing his first deal in 2005 Messi will NOT keep 100 per cent of his image rights. Stuttering: Messi has had a quiet season by his own extremely high standards . Record: Messi is now Barca's highest ever scorer after bagging 371 goals for the club . This is . Messi’s seventh contract renewal in 11 years and his camp have finally . given in to club demands that he share his rights. Messi’s . representative and father Jorge was informed in last week’s meeting that . the club’s new manager for next season will be Luis Enrique but new . signings were not discussed. Despite that, it is no secret that the . Barça forward is close pals with Manchester City striker Sergio Aguero . and would love him to join him at the Nou Camp. A . bid for Aguero would only be possible if Barcelona successfully . off-loaded strikers Alexis Sanchez and Pedro. This summer will see Barca . celebrate winning their appeal over a transfer ban by dramatically . overhauling their squad. Wanted: Messi would love for international team-mate Sergio Aguero (above) to join him at Barca . Lucrative: Messi will overtake Cristiano Ronaldo (above) as the best-played player in the world ."

#### Preprocess text

In [21]:
# Preprocess text
def text_preprocess(article0):
    #article0_processed=article0[article0.index('--')+2:]
    article0_processed = re.sub(r'\s+', ' ', article0)
    #article0_processed = re.sub(r'\s+\.\s+', ' ', article0_processed)
    #article0_processed = re.sub(r'\.\++', '', article0_processed)
    article0_processed = re.sub(r'[\:\-]+', '', article0_processed)
    #article0_processed=article0_processed.replace('\'', '').strip()
    article0_processed = re.sub(r'\s+\.\s+', ' ', article0_processed)
    return article0_processed
article0_processed=text_preprocess(article0)
article0_processed

"Lionel Messi will sign a new contract at Barcelona, making him the bestpaid player in the world, before the end of the week. The player’s father met with the club officials Javier Faus and Antoni Rossich last week and effectively closed the deal which will keep the player, who will be 27 in June, at the club until 2018. Messi’s £200m buyout clause will remain but the player’s wages are expected to rise to £15.5m net which will take him beyond Cristiano Ronaldo who earns £15m a season at Real Madrid. New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico Madrid With the complexity of bonuses and addons the gap between world football’s top two will be minimal but Barca will now have bragging rights over Madrid until the capital club makes its next move. Barcelona had planned to announce the new deal at the weekend but the unexpected prospect of winning the league on Saturday if they beat Atletico Madrid at home could even bring the announcement forward to Wednesday or Thursday. As well as being the world’s top two players Messi and Ronaldo are La Liga’s commercial colossi generating more money for their respective clubs than most of the rest of the league combined and due to an important change in Messi’s new deal Barca will now be better placed to tapin to that money stream as for the first time since signing his first deal in 2005 Messi will NOT keep 100 per cent of his image rights. Stuttering Messi has had a quiet season by his own extremely high standards Record Messi is now Barca's highest ever scorer after bagging 371 goals for the club This is Messi’s seventh contract renewal in 11 years and his camp have finally given in to club demands that he share his rights. Messi’s representative and father Jorge was informed in last week’s meeting that the club’s new manager for next season will be Luis Enrique but new signings were not discussed. Despite that, it is no secret that the Barça forward is close pals with Manchester City striker Sergio Aguero and would love him to join him at the Nou Camp. A bid for Aguero would only be possible if Barcelona successfully offloaded strikers Alexis Sanchez and Pedro. This summer will see Barca celebrate winning their appeal over a transfer ban by dramatically overhauling their squad. Wanted Messi would love for international teammate Sergio Aguero (above) to join him at Barca Lucrative Messi will overtake Cristiano Ronaldo (above) as the bestplayed player in the world ."

In [22]:
def text_in_lemma_form(article0_processed):
    nlp=spacy.load("en_core_web_md")
    text_lemma_list=[]
    doc=nlp(article0_processed)
    for token in doc:
        #print(token.lemma_)
        text_lemma_list.append(token.lemma_)
    text_lemma=" ".join(text_lemma_list)
    return text_lemma
text_in_lemma_form(article0_processed)

"Lionel Messi will sign a new contract at Barcelona , make he the bestpaid player in the world , before the end of the week . the player ’s father meet with the club official Javier Faus and Antoni Rossich last week and effectively close the deal which will keep the player , who will be 27 in June , at the club until 2018 . Messi ’s £ 200 m buyout clause will remain but the player ’s wage be expect to rise to £ 15.5 m net which will take he beyond Cristiano Ronaldo who earn £ 15 m a season at Real Madrid . new deal Barcelona star Lionel Messi be set to sign a new contract with the catalan club Close Messi ( left ) could still be a La Liga winner this season if his side can defeat Atletico Madrid with the complexity of bonus and addon the gap between world football ’s top two will be minimal but Barca will now have bragging right over Madrid until the capital club make its next move . Barcelona have plan to announce the new deal at the weekend but the unexpected prospect of win the league on Saturday if they beat Atletico Madrid at home could even bring the announcement forward to Wednesday or Thursday . as well as be the world ’s top two player Messi and Ronaldo be La Liga ’s commercial colossi generate more money for their respective club than most of the rest of the league combine and due to an important change in Messi ’s new deal Barca will now be well place to tapin to that money stream as for the first time since sign his first deal in 2005 Messi will not keep 100 per cent of his image right . stutter Messi have have a quiet season by his own extremely high standard Record Messi be now Barca 's high ever scorer after bag 371 goal for the club this be Messi ’s seventh contract renewal in 11 year and his camp have finally give in to club demand that he share his right . Messi ’s representative and father Jorge be inform in last week ’s meeting that the club ’s new manager for next season will be Luis Enrique but new signing be not discuss . despite that , it be no secret that the Barça forward be close pal with Manchester City striker Sergio Aguero and would love he to join he at the Nou Camp . a bid for Aguero would only be possible if Barcelona successfully offload striker Alexis Sanchez and Pedro . this summer will see Barca celebrate win their appeal over a transfer ban by dramatically overhaul their squad . want Messi would love for international teammate Sergio Aguero ( above ) to join he at Barca Lucrative Messi will overtake Cristiano Ronaldo ( above ) as the bestplaye player in the world ."

In [23]:
# Removing special characters and digits
def text_preprocess_more(article0_processed):
    article0_processed_more=text_in_lemma_form(article0_processed)
    article0_processed_more = re.sub('[^a-zA-Z0-9]', ' ', article0_processed_more)
    article0_processed_more = re.sub(r'\s+', ' ', article0_processed_more)
    article0_processed_more=article0_processed_more.lower()
    return article0_processed_more
article0_processed_more=text_preprocess_more(article0_processed)
article0_processed_more

'lionel messi will sign a new contract at barcelona make he the bestpaid player in the world before the end of the week the player s father meet with the club official javier faus and antoni rossich last week and effectively close the deal which will keep the player who will be 27 in june at the club until 2018 messi s 200 m buyout clause will remain but the player s wage be expect to rise to 15 5 m net which will take he beyond cristiano ronaldo who earn 15 m a season at real madrid new deal barcelona star lionel messi be set to sign a new contract with the catalan club close messi left could still be a la liga winner this season if his side can defeat atletico madrid with the complexity of bonus and addon the gap between world football s top two will be minimal but barca will now have bragging right over madrid until the capital club make its next move barcelona have plan to announce the new deal at the weekend but the unexpected prospect of win the league on saturday if they beat atletico madrid at home could even bring the announcement forward to wednesday or thursday as well as be the world s top two player messi and ronaldo be la liga s commercial colossi generate more money for their respective club than most of the rest of the league combine and due to an important change in messi s new deal barca will now be well place to tapin to that money stream as for the first time since sign his first deal in 2005 messi will not keep 100 per cent of his image right stutter messi have have a quiet season by his own extremely high standard record messi be now barca s high ever scorer after bag 371 goal for the club this be messi s seventh contract renewal in 11 year and his camp have finally give in to club demand that he share his right messi s representative and father jorge be inform in last week s meeting that the club s new manager for next season will be luis enrique but new signing be not discuss despite that it be no secret that the bar a forward be close pal with manchester city striker sergio aguero and would love he to join he at the nou camp a bid for aguero would only be possible if barcelona successfully offload striker alexis sanchez and pedro this summer will see barca celebrate win their appeal over a transfer ban by dramatically overhaul their squad want messi would love for international teammate sergio aguero above to join he at barca lucrative messi will overtake cristiano ronaldo above as the bestplaye player in the world '

In [24]:
#highlights0=dataset["train"][0]['highlights']
highlights0=dataset["train"][203704]['highlights']
#highlights0=dataset["train"][222893]['highlights']
highlights0

"Lionel Messi set to sign new Barcelona contract worth £15.5m a season .\nThe Barca star will become the best-paid player in the world .\nCristiano Ronaldo currently earns £15m a season at Real Madrid .\nMessi's £200m buy-out clause will remain in place ."

In [25]:
highlights0_processed=text_preprocess(highlights0)
highlights0_processed

"Lionel Messi set to sign new Barcelona contract worth £15.5m a season The Barca star will become the bestpaid player in the world Cristiano Ronaldo currently earns £15m a season at Real Madrid Messi's £200m buyout clause will remain in place ."

#### Text to Sentences

In [26]:
nlp=spacy.load("en_core_web_md")
def text_to_sentences(article0_processed):
    doc=nlp(article0_processed)
    sentences=[]
    for sent in doc.sents:
        if len(sent)>=5:
        #if len(sent)>=0:
            sentences.append(sent.text.strip())
    return sentences
sentences=text_to_sentences(article0_processed)
sentences

['Lionel Messi will sign a new contract at Barcelona, making him the bestpaid player in the world, before the end of the week.',
 'The player’s father met with the club officials Javier Faus and Antoni Rossich last week and effectively closed the deal which will keep the player, who will be 27 in June, at the club until 2018.',
 'Messi’s £200m buyout clause will remain but the player’s wages are expected to rise to £15.5m net which will take him beyond Cristiano Ronaldo who earns £15m a season at Real Madrid.',
 'New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico Madrid',
 'With the complexity of bonuses and addons the gap between world football’s top two will be minimal but Barca will now have bragging rights over Madrid until the capital club makes its next move.',
 'Barcelona had planned to announce the new deal at the weekend but the unexpected prospect of winning the league on Saturday if they beat Atletico Madrid at home could even bring the announcement forward to Wednesday or Thursday.',
 'As well as being the world’s top two players Messi and Ronaldo are La Liga’s commercial colossi generating more money for their respective clubs than most of the rest of the league combined and due to an important change in Messi’s new deal Barca will now be better placed to tapin to that money stream as for the first time since signing his first deal in 2005 Messi will NOT keep 100 per cent of his image rights.',
 "Stuttering Messi has had a quiet season by his own extremely high standards Record Messi is now Barca's highest ever scorer after bagging 371 goals for the club This is Messi’s seventh contract renewal in 11 years and his camp have finally given in to club demands that he share his rights.",
 'Messi’s representative and father Jorge was informed in last week’s meeting that the club’s new manager for next season will be Luis Enrique but new signings were not discussed.',
 'Despite that, it is no secret that the Barça forward is close pals with Manchester City striker Sergio Aguero and would love him to join him at the Nou Camp.',
 'A bid for Aguero would only be possible if Barcelona successfully offloaded strikers Alexis Sanchez and Pedro.',
 'This summer will see Barca celebrate winning their appeal over a transfer ban by dramatically overhauling their squad.',
 'Wanted Messi would love for international teammate Sergio Aguero (above) to join him at Barca Lucrative Messi will overtake Cristiano Ronaldo (above) as the bestplayed player in the world .']

### EDA

In [27]:
n_of_sent=[]
n_of_words=[]
i=0
for article in dataset_sample['highlights']:
    i+=1
    article_processed=text_preprocess(article)
    sentences=text_to_sentences(article_processed)
    n_of_sent.append(len(sentences))
    for sent in sentences:
        n_of_words.append(len(nlp(sent)))
    #print(i)

In [28]:
pd.Series(n_of_sent).describe()

count    2001.000000
mean        1.291854
std         0.570770
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         6.000000
dtype: float64

In [29]:
pd.Series(n_of_words).describe()

count    2585.000000
mean       40.617408
std        21.914736
min         5.000000
25%        24.000000
50%        39.000000
75%        52.000000
max       175.000000
dtype: float64

In [36]:
n_of_sent=[]
n_of_words=[]
i=0
for article in dataset_sample['article']:
    i+=1
    article_processed=text_preprocess(article)
    sentences=text_to_sentences(article_processed)
    n_of_sent.append(len(sentences))
    for sent in sentences:
        n_of_words.append(len(nlp(sent)))
    #print(i)

In [37]:
pd.Series(n_of_sent).describe()

count    2001.000000
mean       29.876062
std        16.303271
min         3.000000
25%        18.000000
50%        26.000000
75%        39.000000
max       135.000000
dtype: float64

In [38]:
pd.Series(n_of_words).describe()

count    59782.000000
mean        25.926048
std         14.845533
min          4.000000
25%         16.000000
50%         24.000000
75%         32.000000
max        297.000000
dtype: float64

In [39]:
n_of_sent_val=[]
n_of_words_val=[]
i=0
for article in dataset_sample_val['article']:
    i+=1
    article_processed=text_preprocess(article)
    sentences=text_to_sentences(article_processed)
    n_of_sent_val.append(len(sentences))
    for sent in sentences:
        n_of_words_val.append(len(nlp(sent)))

In [40]:
pd.Series(n_of_sent_val).describe()

count    2000.000000
mean       28.476000
std        16.161684
min         2.000000
25%        17.000000
50%        25.000000
75%        37.000000
max       108.000000
dtype: float64

In [41]:
pd.Series(n_of_words_val).describe()

count    56952.000000
mean        26.780640
std         16.678803
min          5.000000
25%         16.000000
50%         24.000000
75%         33.000000
max        324.000000
dtype: float64

### Longformer Model

In [25]:
#### Longformer
#https://huggingface.co/docs/transformers/model_doc/longformer
#https://github.com/allenai/longformer
"""
model = LongformerModel.from_pretrained("allenai/longformer-base-4096")
tokenizer = AutoTokenizer.from_pretrained("allenai/longformer-base-4096")

inputs = tokenizer(article0_processed, return_tensors="pt")

outputs = model(**inputs)
sequence_output = outputs.last_hidden_state
print(sequence_output)
pooled_output = outputs.pooler_output
print(pooled_output)
"""

'\nmodel = LongformerModel.from_pretrained("allenai/longformer-base-4096")\ntokenizer = AutoTokenizer.from_pretrained("allenai/longformer-base-4096")\n\ninputs = tokenizer(article0_processed, return_tensors="pt")\n\noutputs = model(**inputs)\nsequence_output = outputs.last_hidden_state\nprint(sequence_output)\npooled_output = outputs.pooler_output\nprint(pooled_output)\n'

### BERT Model

In [26]:
#https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel
#tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [27]:
inputs = tokenizer(article0_processed, return_tensors="pt")
inputs

Token indices sequence length is longer than the specified maximum sequence length for this model (564 > 512). Running this sequence through the model will result in indexing errors

{'input_ids': tensor([[  101, 14377,  6752,  2072,  2097,  3696,  1037,  2047,  3206,  2012,
          7623,  1010,  2437,  2032,  1996,  2190,  4502,  3593,  2447,  1999,
          1996,  2088,  1010,  2077,  1996,  2203,  1997,  1996,  2733,  1012,
          1996,  2447,  1521,  1055,  2269,  2777,  2007,  1996,  2252,  4584,
         13824,  6904,  2271,  1998,  9865,  2072, 18451,  2818,  2197,  2733,
          1998,  6464,  2701,  1996,  3066,  2029,  2097,  2562,  1996,  2447,
          1010,  2040,  2097,  2022,  2676,  1999,  2238,  1010,  2012,  1996,
          2252,  2127,  2760,  1012,  6752,  2072,  1521,  1055, 21853,  8889,
          2213,  4965,  5833, 11075,  2097,  3961,  2021,  1996,  2447,  1521,
          1055, 12678,  2024,  3517,  2000,  4125,  2000, 14534,  2629,  1012,
          1019,  2213,  5658,  2029,  2097,  2202,  2032,  3458, 13675,  2923,
         15668,  8923,  2080,  2040,  7796,  2015, 14534,  2629,  2213,  1037,
          2161,  2012,  2613,  6921,  1012,  2047,  3066,  7623,  2732, 14377,
          6752,  2072,  2003,  2275,  2000,  3696,  1037,  2047,  3206,  2007,
          1996, 13973,  2252,  2485,  6752,  2072,  1006,  2187,  1007,  2071,
          2145,  2022,  1037,  2474,  8018,  3453,  2023,  2161,  2065,  2010,
          2217,  2064,  4154, 16132,  6921,  2007,  1996, 11619,  1997, 29563,
          1998,  5587,  5644,  1996,  6578,  2090,  2088,  2374,  1521,  1055,
          2327,  2048,  2097,  2022, 10124,  2021,  3347,  3540,  2097,  2085,
          2031, 23678,  2075,  2916,  2058,  6921,  2127,  1996,  3007,  2252,
          3084,  2049,  2279,  2693,  1012,  7623,  2018,  3740,  2000, 14970,
          1996,  2047,  3066,  2012,  1996,  5353,  2021,  1996,  9223,  9824,
          1997,  3045,  1996,  2223,  2006,  5095,  2065,  2027,  3786, 16132,
          6921,  2012,  2188,  2071,  2130,  3288,  1996,  8874,  2830,  2000,
          9317,  2030,  9432,  1012,  2004,  2092,  2004,  2108,  1996,  2088,
          1521,  1055,  2327,  2048,  2867,  6752,  2072,  1998,  8923,  2080,
          2024,  2474,  8018,  1521,  1055,  3293,  8902, 15094,  2072, 11717,
          2062,  2769,  2005,  2037,  7972,  4184,  2084,  2087,  1997,  1996,
          2717,  1997,  1996,  2223,  4117,  1998,  2349,  2000,  2019,  2590,
          2689,  1999,  6752,  2072,  1521,  1055,  2047,  3066,  3347,  3540,
          2097,  2085,  2022,  2488,  2872,  2000, 11112,  2378,  2000,  2008,
          2769,  5460,  2004,  2005,  1996,  2034,  2051,  2144,  6608,  2010,
          2034,  3066,  1999,  2384,  6752,  2072,  2097,  2025,  2562,  2531,
          2566,  9358,  1997,  2010,  3746,  2916,  1012, 24646, 19567,  6752,
          2072,  2038,  2018,  1037,  4251,  2161,  2011,  2010,  2219,  5186,
          2152,  4781,  2501,  6752,  2072,  2003,  2085,  3347,  3540,  1005,
          1055,  3284,  2412, 10835,  2044,  4524,  4726,  4261,  2487,  3289,
          2005,  1996,  2252,  2023,  2003,  6752,  2072,  1521,  1055,  5066,
          3206, 14524,  1999,  2340,  2086,  1998,  2010,  3409,  2031,  2633,
          2445,  1999,  2000,  2252,  7670,  2008,  2002,  3745,  2010,  2916,
          1012,  6752,  2072,  1521,  1055,  4387,  1998,  2269, 10853,  2001,
          6727,  1999,  2197,  2733,  1521,  1055,  3116,  2008,  1996,  2252,
          1521,  1055,  2047,  3208,  2005,  2279,  2161,  2097,  2022,  6446,
         15769,  2021,  2047,  6608,  2015,  2020,  2025,  6936,  1012,  2750,
          2008,  1010,  2009,  2003,  2053,  3595,  2008,  1996,  3347,  3540,
          2830,  2003,  2485, 14412,  2015,  2007,  5087,  2103, 11854, 13983,
         12943, 13094,  2080,  1998,  2052,  2293,  2032,  2000,  3693,  2032,
          2012,  1996,  2053,  2226,  3409,  1012,  1037,  7226,  2005, 12943,
         13094,  2080,  2052,  2069,  2022,  2825,  2065,  7623,  5147,  2125,
         17468, 26049, 13573, 10568,  1998,  7707,  1012,  2023,  2621,  2097,
          2156,  3347,  3540,  8439,  3045,  2037,  5574,  2058,  1037,  4651,
          7221,  2011, 12099, 18181,  2075,  2037,  4686,  1012,  2359,  6752,
          2072,  2052,  2293,  2005,  2248, 10809, 13983, 12943, 13094,  2080,
          1006,  2682,  1007,  2000,  3693,  2032,  2012,  3347,  3540, 21115,
          6752,  2072,  2097,  2058, 15166, 13675,  2923, 15668,  8923,  2080,
          1006,  2682,  1007,  2004,  1996,  2190, 13068,  2098,  2447,  1999,
          1996,  2088,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [28]:
print(inputs['input_ids'].shape)
print(inputs['token_type_ids'].shape)
print(inputs['attention_mask'].shape)

torch.Size([1, 564])
torch.Size([1, 564])
torch.Size([1, 564])

In [29]:
inputs['input_ids'][0,:512].reshape(1,-1)

tensor([[  101, 14377,  6752,  2072,  2097,  3696,  1037,  2047,  3206,  2012,
          7623,  1010,  2437,  2032,  1996,  2190,  4502,  3593,  2447,  1999,
          1996,  2088,  1010,  2077,  1996,  2203,  1997,  1996,  2733,  1012,
          1996,  2447,  1521,  1055,  2269,  2777,  2007,  1996,  2252,  4584,
         13824,  6904,  2271,  1998,  9865,  2072, 18451,  2818,  2197,  2733,
          1998,  6464,  2701,  1996,  3066,  2029,  2097,  2562,  1996,  2447,
          1010,  2040,  2097,  2022,  2676,  1999,  2238,  1010,  2012,  1996,
          2252,  2127,  2760,  1012,  6752,  2072,  1521,  1055, 21853,  8889,
          2213,  4965,  5833, 11075,  2097,  3961,  2021,  1996,  2447,  1521,
          1055, 12678,  2024,  3517,  2000,  4125,  2000, 14534,  2629,  1012,
          1019,  2213,  5658,  2029,  2097,  2202,  2032,  3458, 13675,  2923,
         15668,  8923,  2080,  2040,  7796,  2015, 14534,  2629,  2213,  1037,
          2161,  2012,  2613,  6921,  1012,  2047,  3066,  7623,  2732, 14377,
          6752,  2072,  2003,  2275,  2000,  3696,  1037,  2047,  3206,  2007,
          1996, 13973,  2252,  2485,  6752,  2072,  1006,  2187,  1007,  2071,
          2145,  2022,  1037,  2474,  8018,  3453,  2023,  2161,  2065,  2010,
          2217,  2064,  4154, 16132,  6921,  2007,  1996, 11619,  1997, 29563,
          1998,  5587,  5644,  1996,  6578,  2090,  2088,  2374,  1521,  1055,
          2327,  2048,  2097,  2022, 10124,  2021,  3347,  3540,  2097,  2085,
          2031, 23678,  2075,  2916,  2058,  6921,  2127,  1996,  3007,  2252,
          3084,  2049,  2279,  2693,  1012,  7623,  2018,  3740,  2000, 14970,
          1996,  2047,  3066,  2012,  1996,  5353,  2021,  1996,  9223,  9824,
          1997,  3045,  1996,  2223,  2006,  5095,  2065,  2027,  3786, 16132,
          6921,  2012,  2188,  2071,  2130,  3288,  1996,  8874,  2830,  2000,
          9317,  2030,  9432,  1012,  2004,  2092,  2004,  2108,  1996,  2088,
          1521,  1055,  2327,  2048,  2867,  6752,  2072,  1998,  8923,  2080,
          2024,  2474,  8018,  1521,  1055,  3293,  8902, 15094,  2072, 11717,
          2062,  2769,  2005,  2037,  7972,  4184,  2084,  2087,  1997,  1996,
          2717,  1997,  1996,  2223,  4117,  1998,  2349,  2000,  2019,  2590,
          2689,  1999,  6752,  2072,  1521,  1055,  2047,  3066,  3347,  3540,
          2097,  2085,  2022,  2488,  2872,  2000, 11112,  2378,  2000,  2008,
          2769,  5460,  2004,  2005,  1996,  2034,  2051,  2144,  6608,  2010,
          2034,  3066,  1999,  2384,  6752,  2072,  2097,  2025,  2562,  2531,
          2566,  9358,  1997,  2010,  3746,  2916,  1012, 24646, 19567,  6752,
          2072,  2038,  2018,  1037,  4251,  2161,  2011,  2010,  2219,  5186,
          2152,  4781,  2501,  6752,  2072,  2003,  2085,  3347,  3540,  1005,
          1055,  3284,  2412, 10835,  2044,  4524,  4726,  4261,  2487,  3289,
          2005,  1996,  2252,  2023,  2003,  6752,  2072,  1521,  1055,  5066,
          3206, 14524,  1999,  2340,  2086,  1998,  2010,  3409,  2031,  2633,
          2445,  1999,  2000,  2252,  7670,  2008,  2002,  3745,  2010,  2916,
          1012,  6752,  2072,  1521,  1055,  4387,  1998,  2269, 10853,  2001,
          6727,  1999,  2197,  2733,  1521,  1055,  3116,  2008,  1996,  2252,
          1521,  1055,  2047,  3208,  2005,  2279,  2161,  2097,  2022,  6446,
         15769,  2021,  2047,  6608,  2015,  2020,  2025,  6936,  1012,  2750,
          2008,  1010,  2009,  2003,  2053,  3595,  2008,  1996,  3347,  3540,
          2830,  2003,  2485, 14412,  2015,  2007,  5087,  2103, 11854, 13983,
         12943, 13094,  2080,  1998,  2052,  2293,  2032,  2000,  3693,  2032,
          2012,  1996,  2053,  2226,  3409,  1012,  1037,  7226,  2005, 12943,
         13094,  2080,  2052,  2069,  2022,  2825,  2065,  7623,  5147,  2125,
         17468, 26049, 13573, 10568,  1998,  7707,  1012,  2023,  2621,  2097,
          2156,  3347,  3540,  8439,  3045,  2037,  5574,  2058,  1037,  4651,
          7221,  2011]])

In [30]:
tshape1=inputs['input_ids'].shape[1]
tlimit=512
inputs_list=[]
if tshape1 > tlimit:
    tstart=0
    tend=512
    n=math.ceil(tshape1/tlimit)
    for i in range(n):
        inp={}
        inp['input_ids']=inputs['input_ids'][0,tstart:tend].reshape(1,-1)
        inp['token_type_ids']=inputs['token_type_ids'][0,tstart:tend].reshape(1,-1)
        inp['attention_mask']=inputs['attention_mask'][0,tstart:tend].reshape(1,-1)
        inputs_list.append(inp)
        tstart+=tlimit
        tend+=tlimit
else:
    inputs_list.append(inputs)

In [31]:
#inputs_list

In [32]:
#outputs = model(**inputs)
i=0
for inputs in inputs_list:
    outputs = model(**inputs)
    last_hidden_states = outputs.last_hidden_state
    if i > 0:
        #last_hidden_states=torch.stack((last_hidden_states_temp, last_hidden_states), 0)
        last_hidden_states=torch.Tensor(np.vstack([last_hidden_states_temp.detach().numpy()[0],last_hidden_states.detach().numpy()[0]]))
    last_hidden_states_temp = last_hidden_states
    i+=1
last_hidden_states

tensor([[-0.2018, -0.0579,  0.5692,  ...,  0.0666,  0.6675,  0.1846],
        [-0.9975,  0.7882,  0.8868,  ...,  0.1869,  0.7869, -0.2969],
        [-0.4413,  0.2572,  1.0442,  ..., -0.0903,  0.9241,  0.2598],
        ...,
        [-0.0244, -0.7477,  0.7922,  ..., -0.1170,  0.5047, -0.2382],
        [-0.5096, -1.2863,  0.1609,  ...,  0.2883,  0.7362, -0.4317],
        [ 0.7137,  0.1441, -0.1498,  ...,  0.1411, -0.9592, -0.2126]])

In [33]:
last_hidden_states.shape

torch.Size([564, 768])

In [34]:
last_hidden_states=last_hidden_states.reshape(1,last_hidden_states.shape[0],last_hidden_states.shape[1])
last_hidden_states

tensor([[[-0.2018, -0.0579,  0.5692,  ...,  0.0666,  0.6675,  0.1846],
         [-0.9975,  0.7882,  0.8868,  ...,  0.1869,  0.7869, -0.2969],
         [-0.4413,  0.2572,  1.0442,  ..., -0.0903,  0.9241,  0.2598],
         ...,
         [-0.0244, -0.7477,  0.7922,  ..., -0.1170,  0.5047, -0.2382],
         [-0.5096, -1.2863,  0.1609,  ...,  0.2883,  0.7362, -0.4317],
         [ 0.7137,  0.1441, -0.1498,  ...,  0.1411, -0.9592, -0.2126]]])

In [35]:
last_hidden_states.shape

torch.Size([1, 564, 768])

In [36]:
text="Harry Potter star Daniel Radcliffe gains access to a reported £20 million. Watch I-Reporter give her review of Potter"
#tokenizer.convert_tokens_to_ids(tokenizer.tokenize(text))
inputs=tokenizer(text,return_tensors="pt")
inputs

{'input_ids': tensor([[  101,  4302, 10693,  2732,  3817, 22603, 12154,  3229,  2000,  1037,
          2988, 21853,  2692,  2454,  1012,  3422,  1045,  1011,  6398,  2507,
          2014,  3319,  1997, 10693,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1]])}

In [37]:
outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state
last_hidden_states

tensor([[[-0.1289,  0.1160,  0.4355,  ..., -0.6428,  0.1035,  0.1271],
         [ 0.3416,  0.0150, -0.0039,  ...,  0.3593,  0.8584, -0.0685],
         [-0.4105, -0.3816,  0.5314,  ...,  0.3247,  0.9627,  1.0177],
         ...,
         [-0.2492,  0.0821,  0.5188,  ...,  0.0937,  0.1071,  0.1337],
         [-0.9083, -0.2852, -0.3630,  ...,  0.3930,  0.7090,  0.4202],
         [ 0.6997,  0.3498,  0.0125,  ...,  0.0165, -0.6544, -0.2492]]],
       grad_fn=<NativeLayerNormBackward0>)

In [38]:
last_hidden_states.shape

torch.Size([1, 25, 768])

In [39]:
#dataset = dataset.map(lambda x: tokenizer(x["text"], truncation=True, padding=True), batched=True)
#dataset.set_format(type="numpy", columns=['input_ids', 'token_type_ids', 'attention_mask', 'label'])
#dataset["train"].format

### SBERT Model

In [40]:
"""
model = SentenceTransformer('all-MiniLM-L6-v2')
#Our sentences we like to encode
sentences = ['This framework generates embeddings for each input sentence',
    'this framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.',
    'The quick brown fox jumps over the lazy dog.']

#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")
"""

'\nmodel = SentenceTransformer(\'all-MiniLM-L6-v2\')\n#Our sentences we like to encode\nsentences = [\'This framework generates embeddings for each input sentence\',\n    \'this framework generates embeddings for each input sentence\',\n    \'Sentences are passed as a list of string.\',\n    \'The quick brown fox jumps over the lazy dog.\']\n\n#Sentences are encoded by calling model.encode()\nembeddings = model.encode(sentences)\n\n#Print the embeddings\nfor sentence, embedding in zip(sentences, embeddings):\n    print("Sentence:", sentence)\n    print("Embedding:", embedding)\n    print("")\n'

In [41]:
#model = SentenceTransformer('all-MiniLM-L6-v2')
model = SentenceTransformer('stsb-roberta-base')
embeddings = model.encode(sentences)
"""
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")
"""

'\nfor sentence, embedding in zip(sentences, embeddings):\n    print("Sentence:", sentence)\n    print("Embedding:", embedding)\n    print("")\n'

In [42]:
embeddings.shape

(13, 768)

#### Apply PCA

In [43]:
def pca_decomposition(X,nf):
    pca = PCA(n_components=nf)
    X_pca=pca.fit_transform(X)
    print(pca.explained_variance_ratio_.sum())
    return X_pca

In [44]:
pca_decomposition(embeddings,10)

0.94665354

array([[ 3.8727319e+00, -1.7000664e+00,  9.1905384e+00, -2.1819081e+00,
         5.5943489e-01,  1.6763802e+00, -2.2436290e+00,  2.5247591e+00,
        -1.6714432e+00, -1.9577118e+00],
       [-5.7608948e+00, -6.6597819e+00, -3.9703548e-01,  2.8108711e+00,
        -6.4312673e+00,  1.0173342e+00,  4.1569909e-01,  1.6182102e+00,
         5.7490964e+00, -2.4035633e+00],
       [ 1.2022895e+01, -1.8804104e+00, -7.7373767e-01,  4.1000915e+00,
        -1.5692252e+00, -1.7333882e+00,  7.1380997e+00,  2.2973158e+00,
        -1.2649920e+00,  2.4617477e-01],
       [ 2.9354149e-01, -5.1799047e-01,  5.8712783e+00, -1.4161661e+00,
         1.7666397e+00,  3.3879018e+00, -1.3621775e+00,  1.3937643e+00,
         9.1600083e-03, -3.8862365e-01],
       [ 1.4714113e-01,  6.0740728e+00, -6.1266475e+00, -1.2468283e+00,
        -3.2110260e+00,  6.5821428e+00, -1.5452619e-01, -1.9991370e+00,
        -3.5256963e+00, -3.3716455e+00],
       [-5.6568441e+00,  9.1811285e+00,  4.3724475e+00,  7.4315596e+00,
         1.9898907e+00,  5.7391959e-01,  2.9848974e+00, -3.4792118e+00,
         1.3189836e+00,  1.3836564e+00],
       [ 7.9526253e+00,  6.3852584e-01, -3.0533965e+00,  2.0767705e+00,
         9.5677453e-01, -4.6642928e+00, -6.1327338e+00, -4.8104324e+00,
         2.0513580e+00, -1.8941724e+00],
       [ 2.7081881e+00, -4.6923580e+00, -2.7628794e+00, -3.1347368e+00,
        -8.1395978e-01,  4.7819271e+00, -3.5022056e-01, -2.8129351e+00,
         1.3786476e+00,  5.9925370e+00],
       [-6.0744519e+00, -8.5981493e+00, -9.6564513e-01,  5.7940283e+00,
         1.8225205e+00, -1.4233855e+00, -2.7390881e+00, -4.1962382e-01,
        -5.4488006e+00,  1.0250014e+00],
       [-5.8577819e+00, -3.0645335e+00, -3.9999437e+00, -5.4451184e+00,
         4.2663832e+00, -3.1456134e+00,  4.9806747e+00, -5.7742363e-01,
        -6.6286254e-01, -2.1176112e+00],
       [-1.8177527e+00,  6.9340897e+00, -4.8379984e+00,  3.3510157e-01,
        -5.8064115e-01, -2.1915834e+00, -3.2840114e+00,  8.2189465e+00,
         5.9714932e-02,  2.2041965e+00],
       [-2.5097482e+00,  3.3985252e+00,  4.1881151e+00, -6.2931457e+00,
        -6.1491303e+00, -5.6069074e+00,  5.1719397e-01, -2.6142170e+00,
        -1.4086539e+00,  1.5661678e+00],
       [ 6.8034762e-01,  8.8695228e-01, -7.0509636e-01, -2.8305228e+00,
         7.3936152e+00,  7.4556649e-01,  2.2982104e-01,  6.5998751e-01,
         3.4154890e+00, -2.8440940e-01]], dtype=float32)

#### Cosine similarity in the sentence embeddings

In [45]:
def cosine_similarity_matrix(sentences,embeddings):
    slen = len(sentences)
    sim_matrix = np.zeros((slen, slen))
    for sentence_a, embedding_a in zip(sentences, embeddings):
        for sentence_b, embedding_b in zip(sentences, embeddings):
            #print(a)
            #print(b)
            # compute cosine similarity
            cosine = np.dot(embedding_a,embedding_b)/(norm(embedding_a)*norm(embedding_b))
            #print("Cosine Similarity:", cosine)
            sentence_a_idx=sentences.index(sentence_a)
            sentence_b_idx=sentences.index(sentence_b)
            if sentence_a_idx != sentence_b_idx:
                sim_matrix[sentence_a_idx][sentence_b_idx] = cosine
    return sim_matrix

In [46]:
sim_matrix=cosine_similarity_matrix(sentences,embeddings)

In [47]:
sim_matrix.shape

(13, 13)

#### Page rank using sentence similarity matrix

In [48]:
#https://towardsdatascience.com/text-summarization-in-python-with-jaro-winkler-and-pagerank-72d693da94e8
def page_ranked_sentence(sim_matrix,sentences):
    # create network
    #G = nx.from_numpy_matrix(sim_matrix)
    G = nx.from_numpy_array(sim_matrix)
    # calculate page rank scores
    #pr_sim = nx.pagerank(G)
    pr_sim = nx.pagerank_numpy(G)
    ranked_sentences = [
        #(sentences[sent], rank) for sent,rank in sorted(pr_sim.items(), key=lambda item: item[1], reverse = True)
        sent for sent,rank in sorted(pr_sim.items(), key=lambda item: item[1], reverse = True)
    ]
    return ranked_sentences,pr_sim

In [49]:
ranked_sentences,sentence_scores=page_ranked_sentence(sim_matrix,sentences)
print(ranked_sentences)
print(sentence_scores)

[3, 12, 7, 0, 11, 4, 1, 9, 6, 10, 8, 5, 2]
{0: 0.0874219727644179, 1: 0.07393489507955624, 2: 0.06137596829086055, 3: 0.09779983984514816, 4: 0.0778859641856019, 5: 0.06352526220256988, 6: 0.07170485345098267, 7: 0.08965317184466733, 8: 0.0663664905660405, 9: 0.07223469623164058, 10: 0.06861313656307295, 11: 0.07974879987550798, 12: 0.08973494909993339}

In [50]:
def combine_sentences(my_list,sentences):    
    summary=[]
    for i in sorted(my_list):
        s=sentences[i]
        #print(s)
        summary+=[s]
    summary=''.join(summary)
    return summary

In [51]:
nos=2
my_list=sorted(ranked_sentences[:nos])
my_list

[3, 12]

In [52]:
summary=combine_sentences(my_list,sentences)
summary

'New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico MadridWanted Messi would love for international teammate Sergio Aguero (above) to join him at Barca Lucrative Messi will overtake Cristiano Ronaldo (above) as the bestplayed player in the world .'

#### Evaluation using ROGUE

In [53]:
highlights0_processed

"Lionel Messi set to sign new Barcelona contract worth £15.5m a season The Barca star will become the bestpaid player in the world Cristiano Ronaldo currently earns £15m a season at Real Madrid Messi's £200m buyout clause will remain in place ."

In [54]:
def rouge_metric(summary, highlights):
    rouge = Rouge()
    return rouge.get_scores(summary, highlights)

In [55]:
rouge_metric(summary, highlights0_processed)

[{'rouge-1': {'r': 0.5405405405405406,
   'p': 0.35714285714285715,
   'f': 0.4301075220904151},
  'rouge-2': {'r': 0.175, 'p': 0.1111111111111111, 'f': 0.13592232534640414},
  'rouge-l': {'r': 0.40540540540540543,
   'p': 0.26785714285714285,
   'f': 0.322580640369985}}]

#### For dataset sample

In [56]:
r_metric_all={}
def summarize_dataset_sample():
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        """
        nf=50
        if embeddings.shape[0]>=nf:
            embeddings = pca_decomposition(embeddings,nf)
        """
        sim_matrix=cosine_similarity_matrix(sentences,embeddings)
        sim_matrix=np.nan_to_num(sim_matrix)
        ranked_sentences,sentence_scores=page_ranked_sentence(sim_matrix,sentences)
        nos=2
        my_list=sorted(ranked_sentences[:nos])
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
LONDON, England (Reuters)  Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him."People are always looking to say 'kid star goes off the rails,'" he told reporters last month.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.3055555555555556, 'p': 0.2391304347826087, 'f': 0.2682926780011899}, 'rouge-2': {'r': 0.21621621621621623, 'p': 0.15384615384615385, 'f': 0.17977527604090407}, 'rouge-l': {'r': 0.3055555555555556, 'p': 0.2391304347826087, 'f': 0.2682926780011899}}]
@@@@@@@
WASHINGTON (CNN)  Virginia prosecutors are asking a state court to set a November 9 execution date for John Allen Muhammad, convicted in a series of sniperstyle shootings that terrorized the Washington area in 2002.Ultimately, Muhammad was convicted of the Meyers' killing and of one Maryland murder, which prosecutors there said was "insurance" in case the Virginia conviction was overturned.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.27586206896551724, 'p': 0.1702127659574468, 'f': 0.21052631106994468}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.01694915254237288, 'f': 0.02298850138195353}, 'rouge-l': {'r': 0.27586206896551724, 'p': 0.1702127659574468, 'f': 0.21052631106994468}}]
@@@@@@@
A muchderided figure following the doomed takeover which left Rangers back at the financial precipice, however, Green claimed Mike Ashley is the right man to turn the club around.Expressing regret over the disharmony and split between board and supporters Green – who left Rangers with a near £1million payoff in 2013 – urged fans to give Ashley time.
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.16071428571428573, 'p': 0.1875, 'f': 0.17307691810650905}, 'rouge-2': {'r': 0.04838709677419355, 'p': 0.05263157894736842, 'f': 0.050420163076054444}, 'rouge-l': {'r': 0.16071428571428573, 'p': 0.1875, 'f': 0.17307691810650905}}]
@@@@@@@
By Andrew Levy PUBLISHED 1435 EST, 21 February 2013 | UPDATED 1844 EST, 21 February 2013 Suspect Kenneth Gillespie who is linked to a raid on a McDonalds in Ipswich could not be charged despite having £5,500 in cash on him When robbers snatched £17,000 from a security guard outside a McDonald’s, police had a pretty good idea who might have done it.And Kenneth Gillespie, 59, the man found with the cash, is now on the run after absconding from another open prison.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.3548387096774194, 'p': 0.3283582089552239, 'f': 0.3410852663253411}, 'rouge-2': {'r': 0.05128205128205128, 'p': 0.05, 'f': 0.050632906393206716}, 'rouge-l': {'r': 0.20967741935483872, 'p': 0.19402985074626866, 'f': 0.2015503826044109}}]
@@@@@@@
Cheick Tiote, Papiss Cisse and Wilfried Bony are among the players who will be checked for the virus, after competing in African Nations Cup qualifiers.Scroll down for video Cheick Tiote (left) and Papiss Cisse (right) are among the players being closely monitored following their return from international qualifiers in Africa, where the Ebola crisis is deepening Swansea City's Wilfried Bony, who plays for Ivory Coast, will also be tested after competing in West Africa
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2876712328767123, 'p': 0.3888888888888889, 'f': 0.3307086565292331}, 'rouge-2': {'r': 0.12359550561797752, 'p': 0.16176470588235295, 'f': 0.14012738362448798}, 'rouge-l': {'r': 0.1643835616438356, 'p': 0.2222222222222222, 'f': 0.18897637306466625}}]
@@@@@@@
Having tipped Brazil to win the World Cup I must say their opening performance against Croatia was an anticlimax that highlighted vulnerabilities, particularly in defence.That’s the mark of a really great player, doing not much then contributing something significant when it matters.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.24324324324324326, 'p': 0.21428571428571427, 'f': 0.22784809628585176}, 'rouge-2': {'r': 0.10810810810810811, 'p': 0.09523809523809523, 'f': 0.10126581780483922}, 'rouge-l': {'r': 0.16216216216216217, 'p': 0.14285714285714285, 'f': 0.15189872919724418}}]
@@@@@@@
Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.'I’m scared that my rapist will get out of jail and he knows where I live,' she said.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.37681159420289856, 'p': 0.3611111111111111, 'f': 0.3687943212433983}, 'rouge-2': {'r': 0.047619047619047616, 'p': 0.043010752688172046, 'f': 0.04519773512592222}, 'rouge-l': {'r': 0.2318840579710145, 'p': 0.2222222222222222, 'f': 0.22695034961219265}}]
@@@@@@@
During her career, Arthur won acclaim for her comic timing and deadpan delivery in roles such as Maude, right 'It’s historically significant  it’s radical to sexualize someone people think of as asexual,' spokesman Koji Inoue told The New York Post.Arthur, famous for her Emmywinning roles in the 1970s and '80s television series ‘Maude’ and ‘The Golden Girls,’ died of cancer in 2009 at age 86.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.3333333333333333, 'p': 0.21428571428571427, 'f': 0.26086956045368626}, 'rouge-2': {'r': 0.11904761904761904, 'p': 0.078125, 'f': 0.09433961785688882}, 'rouge-l': {'r': 0.2777777777777778, 'p': 0.17857142857142858, 'f': 0.2173912995841211}}]
@@@@@@@
Caesars Palace hotel and casino, in Las Vegas is pictured, as they try and find a way of cutting debt 'Caesars is, in a certain sense, a Nevada version of 'too big to fail,' said Michael Green, a history professor with the University of Nevada, Las Vegas.U.S. casinohotel companies are dependent on extra cash in a person's pocket, but perhaps none more than Caesars, which waded into the recent economic downturn already burdened by more debt than any of them  a byproduct of a buyout in January 2008 that was largely a wager using other people's money.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.23684210526315788, 'p': 0.11538461538461539, 'f': 0.1551724093876339}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.21052631578947367, 'p': 0.10256410256410256, 'f': 0.1379310300772891}}]
@@@@@@@
WASHINGTON (CNN)  The National Transportation Safety Board began four days of hearings Tuesday on how to stem the "drastic increase" in medical helicopter accidents.Watch Sumwalt's remarks at hearing » Flying at night in poor weather conditions likely contributed to the crashes in Texas and Alaska of three medical helicopters that killed 11 people, the NTSB said.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.37142857142857144, 'p': 0.2653061224489796, 'f': 0.30952380466269847}, 'rouge-2': {'r': 0.14285714285714285, 'p': 0.08928571428571429, 'f': 0.10989010515638228}, 'rouge-l': {'r': 0.3142857142857143, 'p': 0.22448979591836735, 'f': 0.2619047570436508}}]

In [57]:
#r_metric_all

In [58]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.305556  0.239130  0.268293  rouge-1     0
0   0.216216  0.153846  0.179775  rouge-2     0
0   0.305556  0.239130  0.268293  rouge-l     0
0   0.275862  0.170213  0.210526  rouge-1     1
0   0.035714  0.016949  0.022989  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.013333  0.018349  rouge-2  1999
0   0.181818  0.093750  0.123711  rouge-l  1999
0   0.350000  0.191781  0.247788  rouge-1  2000
0   0.041667  0.021978  0.028777  rouge-2  2000
0   0.250000  0.136986  0.176991  rouge-l  2000

[6003 rows x 5 columns]

In [59]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.337319  0.238420  0.267798  1000.0
rouge-2  0.112902  0.070692  0.082248  1000.0
rouge-l  0.257401  0.180951  0.203433  1000.0

#### K-means Clustering

In [60]:
"""
n_clusters=2
kclusterer = KMeansClusterer(n_clusters, distance=nltk.cluster.util.cosine_distance,repeats=25,avoid_empty_clusters=True)
assigned_clusters = kclusterer.cluster(embeddings, assign_clusters=True)
assigned_clusters
len(kclusterer.means())
"""

'\nn_clusters=2\nkclusterer = KMeansClusterer(n_clusters, distance=nltk.cluster.util.cosine_distance,repeats=25,avoid_empty_clusters=True)\nassigned_clusters = kclusterer.cluster(embeddings, assign_clusters=True)\nassigned_clusters\nlen(kclusterer.means())\n'

In [61]:
def cluster_kmeans(X,n_clusters):
    kmeans = KMeans(n_clusters, init = 'k-means++', random_state = 42)
    y_kmeans = kmeans.fit_predict(X)
    cluster_centers = kmeans.cluster_centers_
    return y_kmeans,cluster_centers
    """
    kmeans = KMeansClusterer(n_clusters, distance=nltk.cluster.util.cosine_distance,repeats=25,avoid_empty_clusters=True)
    y_kmeans = kmeans.cluster(X, assign_clusters=True)
    cluster_centers = [arr.tolist() for arr in kmeans.means()]
    return y_kmeans,cluster_centers
    """

In [62]:
def fetch_top_n(X,y_kmeans,cluster_centers,nos):
    # Pick 1 sentence from each group
    my_list=[]
    for i in range(len(cluster_centers)):
        my_dict={}
        for j in range(len(y_kmeans)):
            if y_kmeans[j]==i:
                #my_dict[j] =  distance.euclidean(kmeans.cluster_centers_[i],[list(sentence_scores.values())[j]])
                my_dict[j] =  distance.euclidean(cluster_centers[i],X[j])
        #min_distance = min(my_dict.values())
        #my_list.append(min(my_dict, key=my_dict.get))
        my_list.extend([s for s,d in sorted(my_dict.items(), key=lambda item: item[1])][:nos])
    return my_list

In [63]:
embeddings.shape

(13, 768)

In [64]:
n_clusters = 2
nos=1
y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
my_list=fetch_top_n(embeddings,y_kmeans,cluster_centers,nos)
my_list

[10, 3]

In [65]:
summary=combine_sentences(my_list,sentences)
summary

'New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico MadridA bid for Aguero would only be possible if Barcelona successfully offloaded strikers Alexis Sanchez and Pedro.'

In [66]:
rouge_metric(summary, highlights0_processed)

[{'rouge-1': {'r': 0.32432432432432434,
   'p': 0.2553191489361702,
   'f': 0.2857142807851475},
  'rouge-2': {'r': 0.075, 'p': 0.058823529411764705, 'f': 0.06593406100712511},
  'rouge-l': {'r': 0.2972972972972973,
   'p': 0.23404255319148937,
   'f': 0.26190475697562365}}]

#### For dataset sample

In [67]:
r_metric_all={}
def summarize_dataset_sample():
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        n_clusters = 2
        nos=1
        y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
        my_list=fetch_top_n(embeddings,y_kmeans,cluster_centers,nos)
        summary=combine_sentences(my_list,sentences)
        #print(y_kmeans)
        #print(my_list)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
LONDON, England (Reuters)  Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him."Hopefully none of you will be reading about it."
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.3055555555555556, 'p': 0.2558139534883721, 'f': 0.27848100769748446}, 'rouge-2': {'r': 0.21621621621621623, 'p': 0.17777777777777778, 'f': 0.19512194626710305}, 'rouge-l': {'r': 0.3055555555555556, 'p': 0.2558139534883721, 'f': 0.27848100769748446}}]
@@@@@@@
In a letter dated Wednesday, Senior Assistant Attorney General Katherine B. Burnett said the November date "has been carefully coordinated with the governor's office to insure his availability for any clemency petition Muhammad may wish to pursue."Ultimately, Muhammad was convicted of the Meyers' killing and of one Maryland murder, which prosecutors there said was "insurance" in case the Virginia conviction was overturned.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.20689655172413793, 'p': 0.1111111111111111, 'f': 0.1445783087066339}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.20689655172413793, 'p': 0.1111111111111111, 'f': 0.1445783087066339}}]
@@@@@@@
A muchderided figure following the doomed takeover which left Rangers back at the financial precipice, however, Green claimed Mike Ashley is the right man to turn the club around.'Derek Llambias (Chief Executive) might have had a charisma bypass, but actually he is a good guy doing a good job.
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.17857142857142858, 'p': 0.23255813953488372, 'f': 0.20202019710641783}, 'rouge-2': {'r': 0.06451612903225806, 'p': 0.08333333333333333, 'f': 0.0727272678082648}, 'rouge-l': {'r': 0.17857142857142858, 'p': 0.23255813953488372, 'f': 0.20202019710641783}}]
@@@@@@@
By Andrew Levy PUBLISHED 1435 EST, 21 February 2013 | UPDATED 1844 EST, 21 February 2013 Suspect Kenneth Gillespie who is linked to a raid on a McDonalds in Ipswich could not be charged despite having £5,500 in cash on him When robbers snatched £17,000 from a security guard outside a McDonald’s, police had a pretty good idea who might have done it.A CPS spokesman said ‘We have made the decision not to charge in this case due to the lack of essential forensic evidence.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.2903225806451613, 'p': 0.2608695652173913, 'f': 0.27480915531962014}, 'rouge-2': {'r': 0.038461538461538464, 'p': 0.036585365853658534, 'f': 0.03749999500312567}, 'rouge-l': {'r': 0.1935483870967742, 'p': 0.17391304347826086, 'f': 0.1832061018845057}}]
@@@@@@@
Downing Street said the regime is poised to be rolled out across Gatwick and the Eurostar terminal The screening techniques include a form for passengers to fill in, asking about potential symptoms of the virus The Ghanaian sports minister said he had been contacted by the Confederation of African Football (CAF), which was also said to have been in touch with the South African Football Association.'What I am certain of is that we have the people who know how to keep the country safe and that is exactly what we will do.'
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2328767123287671, 'p': 0.23943661971830985, 'f': 0.23611110611207572}, 'rouge-2': {'r': 0.033707865168539325, 'p': 0.03260869565217391, 'f': 0.03314916627209257}, 'rouge-l': {'r': 0.1232876712328767, 'p': 0.1267605633802817, 'f': 0.1249999950009647}}]
@@@@@@@
Having tipped Brazil to win the World Cup I must say their opening performance against Croatia was an anticlimax that highlighted vulnerabilities, particularly in defence.He’s not a ballwinner who breaks up play.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.2702702702702703, 'p': 0.30303030303030304, 'f': 0.2857142807306123}, 'rouge-2': {'r': 0.10810810810810811, 'p': 0.125, 'f': 0.11594202401176246}, 'rouge-l': {'r': 0.16216216216216217, 'p': 0.18181818181818182, 'f': 0.1714285664448981}}]
@@@@@@@
He'd been charged with breaking into apartments before On the stand Cesar was delivering pizza to a neighbour Graves' luxury condo complex in Manhattan when he attacked her as she slept next to her sevenyearold daughter ‘I screamed,’ the Graves told the Daily News at the time.He briefly lifted his head to speak the words ‘Not guilty’.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.21739130434782608, 'p': 0.29411764705882354, 'f': 0.24999999511250007}, 'rouge-2': {'r': 0.023809523809523808, 'p': 0.03508771929824561, 'f': 0.02836878950958283}, 'rouge-l': {'r': 0.10144927536231885, 'p': 0.13725490196078433, 'f': 0.11666666177916689}}]
@@@@@@@
During her career, Arthur won acclaim for her comic timing and deadpan delivery in roles such as Maude, right 'It’s historically significant  it’s radical to sexualize someone people think of as asexual,' spokesman Koji Inoue told The New York Post.In a twopart episode that aired in November 1972, the show stirred protest and controversy when Maude decided to have an abortion because of her age.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.25, 'p': 0.15254237288135594, 'f': 0.18947367950360122}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.19444444444444445, 'p': 0.11864406779661017, 'f': 0.14736841634570655}}]
@@@@@@@
Caesars Palace hotel and casino, in Las Vegas is pictured, as they try and find a way of cutting debt 'Caesars is, in a certain sense, a Nevada version of 'too big to fail,' said Michael Green, a history professor with the University of Nevada, Las Vegas.U.S. casinohotel companies are dependent on extra cash in a person's pocket, but perhaps none more than Caesars, which waded into the recent economic downturn already burdened by more debt than any of them  a byproduct of a buyout in January 2008 that was largely a wager using other people's money.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.23684210526315788, 'p': 0.11538461538461539, 'f': 0.1551724093876339}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.21052631578947367, 'p': 0.10256410256410256, 'f': 0.1379310300772891}}]
@@@@@@@
WASHINGTON (CNN)  The National Transportation Safety Board began four days of hearings Tuesday on how to stem the "drastic increase" in medical helicopter accidents.The three crashes occurred near South Padre Island, Texas, in February 2008; Huntsville, Texas, in June; and Whittier, Alaska, in December 2007.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.34285714285714286, 'p': 0.2926829268292683, 'f': 0.31578946871537406}, 'rouge-2': {'r': 0.14285714285714285, 'p': 0.11363636363636363, 'f': 0.1265822735459063}, 'rouge-l': {'r': 0.2857142857142857, 'p': 0.24390243902439024, 'f': 0.2631578897680056}}]

In [68]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.305556  0.255814  0.278481  rouge-1     0
0   0.216216  0.177778  0.195122  rouge-2     0
0   0.305556  0.255814  0.278481  rouge-l     0
0   0.206897  0.111111  0.144578  rouge-1     1
0   0.000000  0.000000  0.000000  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.009434  0.014286  rouge-2  1999
0   0.212121  0.080460  0.116667  rouge-l  1999
0   0.275000  0.207547  0.236559  rouge-1  2000
0   0.020833  0.016667  0.018519  rouge-2  2000
0   0.200000  0.150943  0.172043  rouge-l  2000

[6003 rows x 5 columns]

In [69]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.303020  0.229988  0.250849  1000.0
rouge-2  0.094687  0.066248  0.073720  1000.0
rouge-l  0.229950  0.173633  0.189621  1000.0

#### Mean-Shift Clustering

In [70]:
#embeddings_test=np.vstack([embeddings,embeddings[0]+1])
#embeddings_test.shape

In [71]:
def cluster_mshift(X):
    ms = MeanShift()
    ms.fit(X)
    labels=ms.labels_
    cluster_centers = ms.cluster_centers_
    return labels,cluster_centers

In [72]:
labels,cluster_centers=cluster_mshift(embeddings)
labels,cluster_centers.shape

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64), (1, 768))

In [73]:
nos=2
my_list=fetch_top_n(embeddings,labels,cluster_centers,nos)
my_list

[3, 12]

In [74]:
summary=combine_sentences(my_list,sentences)
summary

'New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico MadridWanted Messi would love for international teammate Sergio Aguero (above) to join him at Barca Lucrative Messi will overtake Cristiano Ronaldo (above) as the bestplayed player in the world .'

In [75]:
rouge_metric(summary, highlights0_processed)

[{'rouge-1': {'r': 0.5405405405405406,
   'p': 0.35714285714285715,
   'f': 0.4301075220904151},
  'rouge-2': {'r': 0.175, 'p': 0.1111111111111111, 'f': 0.13592232534640414},
  'rouge-l': {'r': 0.40540540540540543,
   'p': 0.26785714285714285,
   'f': 0.322580640369985}}]

#### For datset sample

In [76]:
r_metric_all={}
def summarize_dataset_sample():
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        nos=2
        labels,cluster_centers=cluster_mshift(embeddings)
        my_list=fetch_top_n(embeddings,labels,cluster_centers,nos)
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(labels)
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
LONDON, England (Reuters)  Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him."People are always looking to say 'kid star goes off the rails,'" he told reporters last month.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.3055555555555556, 'p': 0.2391304347826087, 'f': 0.2682926780011899}, 'rouge-2': {'r': 0.21621621621621623, 'p': 0.15384615384615385, 'f': 0.17977527604090407}, 'rouge-l': {'r': 0.3055555555555556, 'p': 0.2391304347826087, 'f': 0.2682926780011899}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
WASHINGTON (CNN)  Virginia prosecutors are asking a state court to set a November 9 execution date for John Allen Muhammad, convicted in a series of sniperstyle shootings that terrorized the Washington area in 2002.Ultimately, Muhammad was convicted of the Meyers' killing and of one Maryland murder, which prosecutors there said was "insurance" in case the Virginia conviction was overturned.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.27586206896551724, 'p': 0.1702127659574468, 'f': 0.21052631106994468}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.01694915254237288, 'f': 0.02298850138195353}, 'rouge-l': {'r': 0.27586206896551724, 'p': 0.1702127659574468, 'f': 0.21052631106994468}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
A muchderided figure following the doomed takeover which left Rangers back at the financial precipice, however, Green claimed Mike Ashley is the right man to turn the club around.The former Rangers chief executive (right) came to the defense of the existing regime at Ibrox Green came to the defence of Newcastle chairman Mike Ashley (left) after saying that he did not like him Pausing for dramatic effect throughout Green, in hospital for a knee operation, said 'Days like today make me think I should go back (to Rangers).
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.375, 'p': 0.29577464788732394, 'f': 0.330708656487073}, 'rouge-2': {'r': 0.11290322580645161, 'p': 0.08235294117647059, 'f': 0.0952380903604982}, 'rouge-l': {'r': 0.26785714285714285, 'p': 0.2112676056338028, 'f': 0.23622046751069511}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
By Andrew Levy PUBLISHED 1435 EST, 21 February 2013 | UPDATED 1844 EST, 21 February 2013 Suspect Kenneth Gillespie who is linked to a raid on a McDonalds in Ipswich could not be charged despite having £5,500 in cash on him When robbers snatched £17,000 from a security guard outside a McDonald’s, police had a pretty good idea who might have done it.And Kenneth Gillespie, 59, the man found with the cash, is now on the run after absconding from another open prison.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.3548387096774194, 'p': 0.3283582089552239, 'f': 0.3410852663253411}, 'rouge-2': {'r': 0.05128205128205128, 'p': 0.05, 'f': 0.050632906393206716}, 'rouge-l': {'r': 0.20967741935483872, 'p': 0.19402985074626866, 'f': 0.2015503826044109}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Manager Alan Pardew said Newcastle FC would be 'naive' not to take precautions following the Ebola outbreak They said 'Players are probably more closely monitored healthwise than any individuals in the country.Downing Street said the regime is poised to be rolled out across Gatwick and the Eurostar terminal The screening techniques include a form for passengers to fill in, asking about potential symptoms of the virus The Ghanaian sports minister said he had been contacted by the Confederation of African Football (CAF), which was also said to have been in touch with the South African Football Association.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.3150684931506849, 'p': 0.2948717948717949, 'f': 0.3046357565948863}, 'rouge-2': {'r': 0.10112359550561797, 'p': 0.09375, 'f': 0.09729729230445605}, 'rouge-l': {'r': 0.2054794520547945, 'p': 0.19230769230769232, 'f': 0.19867549169422408}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
Having tipped Brazil to win the World Cup I must say their opening performance against Croatia was an anticlimax that highlighted vulnerabilities, particularly in defence.The room was quiet, despondent, but it didn’t stay like that as Neymar equalised and then Brazil went on to win.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.2702702702702703, 'p': 0.24390243902439024, 'f': 0.2564102514234057}, 'rouge-2': {'r': 0.10810810810810811, 'p': 0.09090909090909091, 'f': 0.09876542713610756}, 'rouge-l': {'r': 0.24324324324324326, 'p': 0.21951219512195122, 'f': 0.2307692257823801}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.He'd been charged with breaking into apartments before On the stand Cesar was delivering pizza to a neighbour Graves' luxury condo complex in Manhattan when he attacked her as she slept next to her sevenyearold daughter ‘I screamed,’ the Graves told the Daily News at the time.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.43478260869565216, 'p': 0.32967032967032966, 'f': 0.3749999950945313}, 'rouge-2': {'r': 0.07142857142857142, 'p': 0.04918032786885246, 'f': 0.05825242235460498}, 'rouge-l': {'r': 0.2028985507246377, 'p': 0.15384615384615385, 'f': 0.1749999950945314}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Arthur, famous for her Emmywinning roles in the 1970s and '80s television series ‘Maude’ and ‘The Golden Girls,’ died of cancer in 2009 at age 86.Golden Girls Arthur, far right, with her costars in the 80s TV show Betty White, left, and Rue Mcclanahan In the early 1970s, she appeared on the groundbreaking television comedy 'All in the Family' as Edith Bunker's fiercely liberal cousin Maude.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.3055555555555556, 'p': 0.2037037037037037, 'f': 0.2444444396444445}, 'rouge-2': {'r': 0.14285714285714285, 'p': 0.09375, 'f': 0.11320754238519067}, 'rouge-l': {'r': 0.2777777777777778, 'p': 0.18518518518518517, 'f': 0.22222221742222234}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Caesars Palace hotel and casino, in Las Vegas is pictured, as they try and find a way of cutting debt 'Caesars is, in a certain sense, a Nevada version of 'too big to fail,' said Michael Green, a history professor with the University of Nevada, Las Vegas.U.S. casinohotel companies are dependent on extra cash in a person's pocket, but perhaps none more than Caesars, which waded into the recent economic downturn already burdened by more debt than any of them  a byproduct of a buyout in January 2008 that was largely a wager using other people's money.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.23684210526315788, 'p': 0.11538461538461539, 'f': 0.1551724093876339}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.21052631578947367, 'p': 0.10256410256410256, 'f': 0.1379310300772891}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
Watch Sumwalt's remarks at hearing » Flying at night in poor weather conditions likely contributed to the crashes in Texas and Alaska of three medical helicopters that killed 11 people, the NTSB said.Expert witnesses such as pilots, medical personnel, managers and Federal Aviation Administration officials will give sworn testimony on what has been an "ongoing concern" of the safety board, which issued a report on emergency medical services operations in 2006.The recommendations have not been fully implemented, the NTSB said.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.3142857142857143, 'p': 0.16176470588235295, 'f': 0.21359222852295232}, 'rouge-2': {'r': 0.02857142857142857, 'p': 0.012658227848101266, 'f': 0.017543855393968407}, 'rouge-l': {'r': 0.2571428571428571, 'p': 0.1323529411764706, 'f': 0.17475727706664165}}]

In [77]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.305556  0.239130  0.268293  rouge-1     0
0   0.216216  0.153846  0.179775  rouge-2     0
0   0.305556  0.239130  0.268293  rouge-l     0
0   0.275862  0.170213  0.210526  rouge-1     1
0   0.035714  0.016949  0.022989  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.015152  0.020000  rouge-2  1999
0   0.181818  0.096774  0.126316  rouge-l  1999
0   0.250000  0.144928  0.183486  rouge-1  2000
0   0.020833  0.011628  0.014925  rouge-2  2000
0   0.175000  0.101449  0.128440  rouge-l  2000

[6003 rows x 5 columns]

In [78]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.355486  0.217445  0.258134  1000.0
rouge-2  0.119914  0.063971  0.078658  1000.0
rouge-l  0.275626  0.166756  0.198531  1000.0

### TF-IDF Model

#### Word Freq

In [79]:
stopwords = nltk.corpus.stopwords.words('english')

In [80]:
def getWordFreq(text):
    word_frequencies = {}
    for word in nltk.word_tokenize(text):
        if word not in stopwords:
            if word not in word_frequencies.keys():
                word_frequencies[word] = 1
            else:
                word_frequencies[word] += 1
    maximum_frequncy = max(word_frequencies.values())
    for word in word_frequencies.keys():
        word_frequencies[word] = (word_frequencies[word]/maximum_frequncy)
    return word_frequencies

In [81]:
def getSentScore(word_frequencies,sentences):
    # Get sentence score by adding word frequency of all the words within the sentence
    sentence_scores = {}
    for i,sent in zip(range(len(sentences)),sentences):
        for word in nltk.word_tokenize(sent.lower()):
        #for word in nltk.word_tokenize(sent):
            if word in word_frequencies.keys():
                if i not in sentence_scores.keys():
                    sentence_scores[i] = word_frequencies[word]
                else:
                    sentence_scores[i] += word_frequencies[word]
        if i not in sentence_scores.keys():
            sentence_scores[i] = 0
    ranked_sentences = [
        #(sentences[sent], rank) for sent,rank in sorted(pr_sim.items(), key=lambda item: item[1], reverse = True)
        sent for sent,rank in sorted(sentence_scores.items(), key=lambda item: item[1], reverse = True)
    ]
    return ranked_sentences,sentence_scores

In [82]:
word_frequencies=getWordFreq(article0_processed_more)
ranked_sentences,sentence_scores=getSentScore(word_frequencies,sentences)
print(ranked_sentences)
print(sentence_scores)

[6, 3, 7, 12, 8, 1, 0, 5, 2, 4, 9, 10, 11]
{0: 3.6153846153846163, 1: 3.8461538461538467, 2: 3.0769230769230766, 3: 7.0769230769230775, 4: 2.6153846153846154, 5: 3.0769230769230775, 6: 8.230769230769232, 7: 6.307692307692307, 8: 4.153846153846154, 9: 2.0, 10: 1.2307692307692306, 11: 0.9999999999999998, 12: 4.769230769230769}

In [83]:
sentence_scores.values()

dict_values([3.6153846153846163, 3.8461538461538467, 3.0769230769230766, 7.0769230769230775, 2.6153846153846154, 3.0769230769230775, 8.230769230769232, 6.307692307692307, 4.153846153846154, 2.0, 1.2307692307692306, 0.9999999999999998, 4.769230769230769])

In [84]:
r_metric_all={}
def summarize_dataset_sample():
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        article_processed_more=text_preprocess_more(article_processed)
        word_frequencies=getWordFreq(article_processed_more)
        ranked_sentences,sentence_scores=getSentScore(word_frequencies,sentences)
        nos=2
        my_list=sorted(ranked_sentences[:nos])
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties.At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel Part II," currently six places below his number one movie on the UK box office chart.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.4722222222222222, 'p': 0.265625, 'f': 0.339999995392}, 'rouge-2': {'r': 0.32432432432432434, 'p': 0.15, 'f': 0.205128200803565}, 'rouge-l': {'r': 0.4166666666666667, 'p': 0.234375, 'f': 0.299999995392}}]
@@@@@@@
WASHINGTON (CNN)  Virginia prosecutors are asking a state court to set a November 9 execution date for John Allen Muhammad, convicted in a series of sniperstyle shootings that terrorized the Washington area in 2002.The letter, addressed to the chief judge of the Prince William County Circuit Court, says the court must hold a hearing within 10 days of receiving the letter, and must set an execution date no later than 60 days after the hearing.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.27586206896551724, 'p': 0.14285714285714285, 'f': 0.18823528962214545}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.013513513513513514, 'f': 0.01960783915417228}, 'rouge-l': {'r': 0.2413793103448276, 'p': 0.125, 'f': 0.16470587785743956}}]
@@@@@@@
The former Rangers chief executive (right) came to the defense of the existing regime at Ibrox Green came to the defence of Newcastle chairman Mike Ashley (left) after saying that he did not like him Pausing for dramatic effect throughout Green, in hospital for a knee operation, said 'Days like today make me think I should go back (to Rangers).Green said that current chief exec Derek Llambias (right) was a good guy despite having a 'charisma bypass' Green then hit out at wouldbe owner Dave King by mentioning he has numerous convictions against his name 'I met him when I took Llambias into Ibrox when we did the deal for the naming rights (sold to Sports Direct for a pound).
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.4642857142857143, 'p': 0.2826086956521739, 'f': 0.3513513466471877}, 'rouge-2': {'r': 0.12903225806451613, 'p': 0.06837606837606838, 'f': 0.08938547033238686}, 'rouge-l': {'r': 0.30357142857142855, 'p': 0.18478260869565216, 'f': 0.22972972502556618}}]
@@@@@@@
By Andrew Levy PUBLISHED 1435 EST, 21 February 2013 | UPDATED 1844 EST, 21 February 2013 Suspect Kenneth Gillespie who is linked to a raid on a McDonalds in Ipswich could not be charged despite having £5,500 in cash on him When robbers snatched £17,000 from a security guard outside a McDonald’s, police had a pretty good idea who might have done it.Employer Mr Gillespie was on day release working at Ipswich Town Football Club, pictured, when the robbery took place Open prison Kenneth Gillespie had been serving a life sentence at Hollesley Bay in Woodbridge, Suffolk He has been at large since failing to return from day release on January 23.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.532258064516129, 'p': 0.38372093023255816, 'f': 0.4459459410774288}, 'rouge-2': {'r': 0.19230769230769232, 'p': 0.14018691588785046, 'f': 0.1621621572850257}, 'rouge-l': {'r': 0.3548387096774194, 'p': 0.2558139534883721, 'f': 0.29729729242878017}}]
@@@@@@@
Scroll down for video Cheick Tiote (left) and Papiss Cisse (right) are among the players being closely monitored following their return from international qualifiers in Africa, where the Ebola crisis is deepening Swansea City's Wilfried Bony, who plays for Ivory Coast, will also be tested after competing in West AfricaManchester City FC has refused to say whether Yaya Touré  the Ivory Coast captain  was screened for the virus on return from the African continent 'Of course it's a worry when you've got players such a long way away, you're just looking at your phone hoping no messages come thorough that are negative.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.3424657534246575, 'p': 0.2808988764044944, 'f': 0.30864197035741503}, 'rouge-2': {'r': 0.10112359550561797, 'p': 0.09, 'f': 0.09523809025503233}, 'rouge-l': {'r': 0.2465753424657534, 'p': 0.20224719101123595, 'f': 0.2222222172709954}}]
@@@@@@@
Rio in Rio Rio Ferdinand (centre) with former teammates Rafael and Fabio plus friends watching BrazilCroatia They had a big crowd of family and friends around to watch the game, 25 people in one room, including six kids.A whole new ball game Ferdinand (right) plays beach volleyball with the Da Silva twins and a friend I got back to Rio late, and there were still umpteen impromptu matches being played all along the beach.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.2972972972972973, 'p': 0.18333333333333332, 'f': 0.22680411899245415}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.1891891891891892, 'p': 0.11666666666666667, 'f': 0.14432989218833048}}]
@@@@@@@
By Daily Mail Reporters PUBLISHED 2040 EST, 26 January 2014 | UPDATED 0631 EST, 27 January 2014 Shattered Kia Graves is a former actress who once had a successful career with a modeling agency but since she was raped in 2012, she hasn't worked and her socially life has been shattered A woman who was attacked and raped in her Manhattan apartment in 2012 has come forward to detail the horrific night a teenage pizza boy allegedly assaulted her as her 7yearold daughter slept in the bed beside her.Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.5507246376811594, 'p': 0.3392857142857143, 'f': 0.4198894980446263}, 'rouge-2': {'r': 0.19047619047619047, 'p': 0.1, 'f': 0.1311475364686914}, 'rouge-l': {'r': 0.3188405797101449, 'p': 0.19642857142857142, 'f': 0.24309391793412904}}]
@@@@@@@
A topless painting of the late actress Bea Arthur  famous for her role as Dorothy in the TV show ‘Golden Girls’ – sold for nearly $2 million at a Christie’s auction in New York on Wednesday night.During her career, Arthur won acclaim for her comic timing and deadpan delivery in roles such as Maude, right 'It’s historically significant  it’s radical to sexualize someone people think of as asexual,' spokesman Koji Inoue told The New York Post.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.3333333333333333, 'p': 0.1875, 'f': 0.2399999953920001}, 'rouge-2': {'r': 0.09523809523809523, 'p': 0.05405405405405406, 'f': 0.06896551262187903}, 'rouge-l': {'r': 0.2777777777777778, 'p': 0.15625, 'f': 0.19999999539200009}}]
@@@@@@@
Caesars Palace hotel and casino, in Las Vegas is pictured, as they try and find a way of cutting debt 'Caesars is, in a certain sense, a Nevada version of 'too big to fail,' said Michael Green, a history professor with the University of Nevada, Las Vegas.The fountain in front of Caesars Palace hotel and casino in Las Vegas is part of the group's lavish design In between, the company had cut about 200 people from its corporate staff.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.2631578947368421, 'p': 0.1724137931034483, 'f': 0.20833332855034734}, 'rouge-2': {'r': 0.024390243902439025, 'p': 0.013888888888888888, 'f': 0.017699110420550977}, 'rouge-l': {'r': 0.21052631578947367, 'p': 0.13793103448275862, 'f': 0.1666666618836807}}]
@@@@@@@
iReport Watch smoke pour from a medical chopper crash in Michigan A December 2007 accident in Cherokee, Alabama, was likely caused by the pilot flying too low over trees, the NTSB said.Expert witnesses such as pilots, medical personnel, managers and Federal Aviation Administration officials will give sworn testimony on what has been an "ongoing concern" of the safety board, which issued a report on emergency medical services operations in 2006.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.14285714285714285, 'p': 0.07936507936507936, 'f': 0.10204081173469408}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.08571428571428572, 'p': 0.047619047619047616, 'f': 0.061224485204081976}}]

In [85]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.472222  0.265625  0.340000  rouge-1     0
0   0.324324  0.150000  0.205128  rouge-2     0
0   0.416667  0.234375  0.300000  rouge-l     0
0   0.275862  0.142857  0.188235  rouge-1     1
0   0.035714  0.013514  0.019608  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.013333  0.018349  rouge-2  1999
0   0.181818  0.093750  0.123711  rouge-l  1999
0   0.425000  0.250000  0.314815  rouge-1  2000
0   0.166667  0.097561  0.123077  rouge-2  2000
0   0.275000  0.161765  0.203704  rouge-l  2000

[6003 rows x 5 columns]

In [86]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.386492  0.226826  0.276116  1000.0
rouge-2  0.140029  0.073349  0.091920  1000.0
rouge-l  0.295900  0.172892  0.210591  1000.0

#### TF-IDF Vectorizer

In [87]:
vectorizer = TfidfVectorizer(stop_words="english")
X_tdidf = vectorizer.fit_transform(sentences)
X_tdidf

<13x163 sparse matrix of type '<class 'numpy.float64'>'
	with 224 stored elements in Compressed Sparse Row format>

In [88]:
vectorizer.get_feature_names_out()

array(['100', '11', '15', '15m', '2005', '200m', '2018', '27', '371',
       '5m', 'addons', 'aguero', 'alexis', 'announce', 'announcement',
       'antoni', 'appeal', 'atletico', 'bagging', 'ban', 'barca',
       'barcelona', 'barça', 'beat', 'bestpaid', 'bestplayed', 'better',
       'bid', 'bonuses', 'bragging', 'bring', 'buyout', 'camp', 'capital',
       'catalan', 'celebrate', 'cent', 'change', 'city', 'clause',
       'close', 'closed', 'club', 'clubs', 'colossi', 'combined',
       'commercial', 'complexity', 'contract', 'cristiano', 'deal',
       'defeat', 'demands', 'despite', 'discussed', 'dramatically',
       'earns', 'effectively', 'end', 'enrique', 'expected', 'extremely',
       'father', 'faus', 'finally', 'football', 'forward', 'gap',
       'generating', 'given', 'goals', 'high', 'highest', 'home', 'image',
       'important', 'informed', 'international', 'javier', 'join',
       'jorge', 'june', 'la', 'league', 'left', 'liga', 'lionel', 'love',
       'lucrative', 'luis', 'madrid', 'makes', 'making', 'manager',
       'manchester', 'meeting', 'messi', 'met', 'minimal', 'money', 'net',
       'new', 'nou', 'officials', 'offloaded', 'overhauling', 'overtake',
       'pals', 'pedro', 'placed', 'planned', 'player', 'players',
       'possible', 'prospect', 'quiet', 'real', 'record', 'remain',
       'renewal', 'representative', 'respective', 'rest', 'rights',
       'rise', 'ronaldo', 'rossich', 'sanchez', 'saturday', 'scorer',
       'season', 'secret', 'sergio', 'set', 'seventh', 'share', 'sign',
       'signing', 'signings', 'squad', 'standards', 'star', 'stream',
       'striker', 'strikers', 'stuttering', 'successfully', 'summer',
       'tapin', 'teammate', 'thursday', 'time', 'transfer', 'unexpected',
       'wages', 'wanted', 'wednesday', 'week', 'weekend', 'winner',
       'winning', 'world', 'years'], dtype=object)

#### K-means Clustering

In [89]:
n_clusters = 2
nos=1
y_kmeans,cluster_centers=cluster_kmeans(X_tdidf.toarray(),n_clusters)
my_list=fetch_top_n(X_tdidf.toarray(),y_kmeans,cluster_centers,nos)
my_list

[12, 3]

#### Generate summary

In [90]:
summary=combine_sentences(my_list,sentences)
summary

'New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico MadridWanted Messi would love for international teammate Sergio Aguero (above) to join him at Barca Lucrative Messi will overtake Cristiano Ronaldo (above) as the bestplayed player in the world .'

In [91]:
highlights0_processed

"Lionel Messi set to sign new Barcelona contract worth £15.5m a season The Barca star will become the bestpaid player in the world Cristiano Ronaldo currently earns £15m a season at Real Madrid Messi's £200m buyout clause will remain in place ."

In [92]:
rouge_metric(summary, highlights0_processed)

[{'rouge-1': {'r': 0.5405405405405406,
   'p': 0.35714285714285715,
   'f': 0.4301075220904151},
  'rouge-2': {'r': 0.175, 'p': 0.1111111111111111, 'f': 0.13592232534640414},
  'rouge-l': {'r': 0.40540540540540543,
   'p': 0.26785714285714285,
   'f': 0.322580640369985}}]

In [93]:
"""
# Find k
#X=embeddings
#X = model.encode(sentences)
#X=[list(sentence_scores.values())]
X=X_tdidf.toarray()
range_n_clusters = [2, 3, 4, 5, 6]
for n_clusters in range_n_clusters:
    # Create a subplot with 1 row and 1 columns
    fig, (ax2) = plt.subplots(1, 1)
    fig.set_size_inches(18, 7)
    
    # Initialize the clusterer with n_clusters value and a random generator
    # seed of 10 for reproducibility.
    clusterer = KMeans(n_clusters=n_clusters, n_init="auto", random_state=10)
    cluster_labels = clusterer.fit_predict(X)

    # The silhouette_score gives the average value for all the samples.
    # This gives a perspective into the density and separation of the formed
    # clusters
    silhouette_avg = silhouette_score(X, cluster_labels)
    print(
        "For n_clusters =",
        n_clusters,
        "The average silhouette_score is :",
        silhouette_avg,
    )

    # Compute the silhouette scores for each sample
    sample_silhouette_values = silhouette_samples(X, cluster_labels)

    # 2nd Plot showing the actual clusters formed
    colors = cm.nipy_spectral(cluster_labels.astype(float) / n_clusters)
    ax2.scatter(
        X[:, 0], X[:, 1], marker=".", s=300, lw=0, alpha=0.7, c=colors, edgecolor="k"
    )

    # Labeling the clusters
    centers = clusterer.cluster_centers_
    # Draw white circles at cluster centers
    ax2.scatter(
        centers[:, 0],
        centers[:, 1],
        marker="o",
        c="white",
        alpha=1,
        s=200,
        edgecolor="k",
    )

    for i, c in enumerate(centers):
        ax2.scatter(c[0], c[1], marker="$%d$" % i, alpha=1, s=50, edgecolor="k")

    ax2.set_title("The visualization of the clustered data.")
    ax2.set_xlabel("Feature space for the 1st feature")
    ax2.set_ylabel("Feature space for the 2nd feature")

    plt.suptitle(
        "Silhouette analysis for KMeans clustering on sample data with n_clusters = %d"
        % n_clusters,
        fontsize=14,
        fontweight="bold",
    )

plt.show()
"""
summary

'New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico MadridWanted Messi would love for international teammate Sergio Aguero (above) to join him at Barca Lucrative Messi will overtake Cristiano Ronaldo (above) as the bestplayed player in the world .'

In [94]:
#clusterer.cluster_centers_

#### For datset sample

In [95]:
r_metric_all={}
def summarize_dataset_sample():
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        vectorizer = TfidfVectorizer(stop_words="english")
        X_tdidf = vectorizer.fit_transform(sentences)
        embeddings = X_tdidf.toarray()
        n_clusters = 2
        nos=1
        y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
        my_list=fetch_top_n(embeddings,y_kmeans,cluster_centers,nos)
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties."I don't think I'll be particularly extravagant.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.4722222222222222, 'p': 0.3953488372093023, 'f': 0.43037974187469963}, 'rouge-2': {'r': 0.32432432432432434, 'p': 0.24489795918367346, 'f': 0.2790697625392104}, 'rouge-l': {'r': 0.3888888888888889, 'p': 0.32558139534883723, 'f': 0.354430374786092}}]
@@@@@@@
Muhammad, now 48, was convicted of murder in the death of Dean Harold Meyers at a Manassas, Virginia, filling station.The letter, addressed to the chief judge of the Prince William County Circuit Court, says the court must hold a hearing within 10 days of receiving the letter, and must set an execution date no later than 60 days after the hearing.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.1724137931034483, 'p': 0.10204081632653061, 'f': 0.1282051235338595}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.13793103448275862, 'p': 0.08163265306122448, 'f': 0.10256409789283387}}]
@@@@@@@
The former Rangers chief executive (right) came to the defense of the existing regime at Ibrox Green came to the defence of Newcastle chairman Mike Ashley (left) after saying that he did not like him Pausing for dramatic effect throughout Green, in hospital for a knee operation, said 'Days like today make me think I should go back (to Rangers).'They have put money in.
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.32142857142857145, 'p': 0.3157894736842105, 'f': 0.3185840657968518}, 'rouge-2': {'r': 0.06451612903225806, 'p': 0.06451612903225806, 'f': 0.06451612403225845}, 'rouge-l': {'r': 0.21428571428571427, 'p': 0.21052631578947367, 'f': 0.21238937553136514}}]
@@@@@@@
The McDonald's in Ipswich, Suffolk, where a G4S security guard was pushed to the ground and £17,000 was stolen in November 2011 All three were on a work placement a mile away at Ipswich Town Football Club after being allowed out of Hollesley Bay open prison, near Woodbridge.A CPS spokesman said ‘We have made the decision not to charge in this case due to the lack of essential forensic evidence.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.3548387096774194, 'p': 0.36065573770491804, 'f': 0.35772357223610285}, 'rouge-2': {'r': 0.11538461538461539, 'p': 0.13043478260869565, 'f': 0.12244897461057913}, 'rouge-l': {'r': 0.1774193548387097, 'p': 0.18032786885245902, 'f': 0.1788617836182168}}]
@@@@@@@
Scroll down for video Cheick Tiote (left) and Papiss Cisse (right) are among the players being closely monitored following their return from international qualifiers in Africa, where the Ebola crisis is deepening Swansea City's Wilfried Bony, who plays for Ivory Coast, will also be tested after competing in West Africa'I do not have it.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2602739726027397, 'p': 0.37254901960784315, 'f': 0.30645160806061406}, 'rouge-2': {'r': 0.06741573033707865, 'p': 0.11320754716981132, 'f': 0.08450703757488619}, 'rouge-l': {'r': 0.1506849315068493, 'p': 0.21568627450980393, 'f': 0.17741934999609796}}]
@@@@@@@
Having tipped Brazil to win the World Cup I must say their opening performance against Croatia was an anticlimax that highlighted vulnerabilities, particularly in defence.He isn’t a creator.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.24324324324324326, 'p': 0.3103448275862069, 'f': 0.2727272678007347}, 'rouge-2': {'r': 0.10810810810810811, 'p': 0.14285714285714285, 'f': 0.12307691817278127}, 'rouge-l': {'r': 0.13513513513513514, 'p': 0.1724137931034483, 'f': 0.15151514658861356}}]
@@@@@@@
Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.He said “I’m sorry,” and ran out,’ she said.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.34782608695652173, 'p': 0.36363636363636365, 'f': 0.35555555055802474}, 'rouge-2': {'r': 0.047619047619047616, 'p': 0.047058823529411764, 'f': 0.047337273106684466}, 'rouge-l': {'r': 0.2028985507246377, 'p': 0.21212121212121213, 'f': 0.20740740240987665}}]
@@@@@@@
John Curran's 1991 painting 'Bea Arthur Naked' has fetched $1.9m at auction The oil on canvas painting was purchased by an anonymous phone bidder for $1.9 million.Arthur, famous for her Emmywinning roles in the 1970s and '80s television series ‘Maude’ and ‘The Golden Girls,’ died of cancer in 2009 at age 86.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.3888888888888889, 'p': 0.2857142857142857, 'f': 0.3294117598228374}, 'rouge-2': {'r': 0.11904761904761904, 'p': 0.09259259259259259, 'f': 0.1041666617447919}, 'rouge-l': {'r': 0.3888888888888889, 'p': 0.2857142857142857, 'f': 0.3294117598228374}}]
@@@@@@@
Caesars lost $2.9 billion.Senior creditors who OK'd the plan would get cash and new debt to make them whole.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.13157894736842105, 'p': 0.23809523809523808, 'f': 0.16949152083883953}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.10526315789473684, 'p': 0.19047619047619047, 'f': 0.1355932157540938}}]
@@@@@@@
Watch Sumwalt's remarks at hearing » Flying at night in poor weather conditions likely contributed to the crashes in Texas and Alaska of three medical helicopters that killed 11 people, the NTSB said.Expert witnesses such as pilots, medical personnel, managers and Federal Aviation Administration officials will give sworn testimony on what has been an "ongoing concern" of the safety board, which issued a report on emergency medical services operations in 2006.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.2, 'p': 0.11290322580645161, 'f': 0.14432989229461168}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.14285714285714285, 'p': 0.08064516129032258, 'f': 0.10309277889254989}}]

In [96]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.472222  0.395349  0.430380  rouge-1     0
0   0.324324  0.244898  0.279070  rouge-2     0
0   0.388889  0.325581  0.354430  rouge-l     0
0   0.172414  0.102041  0.128205  rouge-1     1
0   0.000000  0.000000  0.000000  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.264706  0.102273  0.147541  rouge-2  1999
0   0.393939  0.180556  0.247619  rouge-l  1999
0   0.525000  0.512195  0.518519  rouge-1  2000
0   0.333333  0.340426  0.336842  rouge-2  2000
0   0.400000  0.390244  0.395062  rouge-l  2000

[6003 rows x 5 columns]

In [97]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.314608  0.258440  0.268563  1000.0
rouge-2  0.109576  0.081849  0.087818  1000.0
rouge-l  0.241416  0.197782  0.205359  1000.0

#### Mean-Shift Clustering

In [98]:
labels,cluster_centers=cluster_mshift(X_tdidf.toarray())
labels,cluster_centers.shape

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64), (1, 163))

In [99]:
nos=2
my_list=fetch_top_n(X_tdidf.toarray(),labels,cluster_centers,nos)
my_list

[3, 0]

In [100]:
summary=combine_sentences(my_list,sentences)
summary

'Lionel Messi will sign a new contract at Barcelona, making him the bestpaid player in the world, before the end of the week.New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico Madrid'

In [101]:
rouge_metric(summary, highlights0_processed)

[{'rouge-1': {'r': 0.4864864864864865,
   'p': 0.3829787234042553,
   'f': 0.4285714236422903},
  'rouge-2': {'r': 0.175, 'p': 0.12962962962962962, 'f': 0.14893616532367604},
  'rouge-l': {'r': 0.43243243243243246,
   'p': 0.3404255319148936,
   'f': 0.3809523760232426}}]

In [102]:
#dataset_sample=dataset["train"][0,14497]
#dataset_sample

#### For datset sample

In [103]:
r_metric_all={}
def summarize_dataset_sample():
    i=0
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        #print(sample_idx[i])
        i+=1
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        vectorizer = TfidfVectorizer(stop_words="english")
        X_tdidf = vectorizer.fit_transform(sentences)
        embeddings = X_tdidf.toarray()
        nos=2
        labels,cluster_centers=cluster_mshift(embeddings)
        my_list=fetch_top_n(embeddings,labels,cluster_centers,nos)
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(labels)
            print("Summary - "+ summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties.His latest outing as the boy wizard in "Harry Potter and the Order of the Phoenix" is breaking records on both sides of the Atlantic and he will reprise the role in the last two films.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.5, 'p': 0.33962264150943394, 'f': 0.4044943772048984}, 'rouge-2': {'r': 0.32432432432432434, 'p': 0.17391304347826086, 'f': 0.22641508979530092}, 'rouge-l': {'r': 0.4444444444444444, 'p': 0.3018867924528302, 'f': 0.3595505569801793}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - WASHINGTON (CNN)  Virginia prosecutors are asking a state court to set a November 9 execution date for John Allen Muhammad, convicted in a series of sniperstyle shootings that terrorized the Washington area in 2002.Muhammad, now 48, was convicted of murder in the death of Dean Harold Meyers at a Manassas, Virginia, filling station.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.20689655172413793, 'p': 0.13636363636363635, 'f': 0.1643835568549448}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.018867924528301886, 'f': 0.024691353500991532}, 'rouge-l': {'r': 0.20689655172413793, 'p': 0.13636363636363635, 'f': 0.1643835568549448}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - The former Rangers chief executive (right) came to the defense of the existing regime at Ibrox Green came to the defence of Newcastle chairman Mike Ashley (left) after saying that he did not like him Pausing for dramatic effect throughout Green, in hospital for a knee operation, said 'Days like today make me think I should go back (to Rangers).'You have Sandy Easdale, who has put money in – Dave King who hasn't.'
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.375, 'p': 0.3181818181818182, 'f': 0.3442622901155604}, 'rouge-2': {'r': 0.08064516129032258, 'p': 0.06944444444444445, 'f': 0.07462686069948796}, 'rouge-l': {'r': 0.25, 'p': 0.21212121212121213, 'f': 0.2295081917549047}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - The McDonald's in Ipswich, Suffolk, where a G4S security guard was pushed to the ground and £17,000 was stolen in November 2011 All three were on a work placement a mile away at Ipswich Town Football Club after being allowed out of Hollesley Bay open prison, near Woodbridge.Employer Mr Gillespie was on day release working at Ipswich Town Football Club, pictured, when the robbery took place Open prison Kenneth Gillespie had been serving a life sentence at Hollesley Bay in Woodbridge, Suffolk He has been at large since failing to return from day release on January 23.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.5483870967741935, 'p': 0.4533333333333333, 'f': 0.4963503600085247}, 'rouge-2': {'r': 0.23076923076923078, 'p': 0.1956521739130435, 'f': 0.2117647009162631}, 'rouge-l': {'r': 0.3064516129032258, 'p': 0.25333333333333335, 'f': 0.27737225781874375}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - Scroll down for video Cheick Tiote (left) and Papiss Cisse (right) are among the players being closely monitored following their return from international qualifiers in Africa, where the Ebola crisis is deepening Swansea City's Wilfried Bony, who plays for Ivory Coast, will also be tested after competing in West Africa'I do not have it.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2602739726027397, 'p': 0.37254901960784315, 'f': 0.30645160806061406}, 'rouge-2': {'r': 0.06741573033707865, 'p': 0.11320754716981132, 'f': 0.08450703757488619}, 'rouge-l': {'r': 0.1506849315068493, 'p': 0.21568627450980393, 'f': 0.17741934999609796}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]
Summary - Paulinho (right) isn't a ball winner or a creator and it isn't clear what he brings to BrazilA whole new ball game Ferdinand (right) plays beach volleyball with the Da Silva twins and a friend I got back to Rio late, and there were still umpteen impromptu matches being played all along the beach.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.21621621621621623, 'p': 0.18181818181818182, 'f': 0.19753085923487287}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.13513513513513514, 'p': 0.11363636363636363, 'f': 0.12345678516079886}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - Cesar Lucas was working as a delivery boy at Sal’s Pizza in the same Manhattan neighborhood as the woman’s luxury apartment building.Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.37681159420289856, 'p': 0.37681159420289856, 'f': 0.3768115892028986}, 'rouge-2': {'r': 0.047619047619047616, 'p': 0.041666666666666664, 'f': 0.04444443946666723}, 'rouge-l': {'r': 0.21739130434782608, 'p': 0.21739130434782608, 'f': 0.21739129934782622}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - A topless painting of the late actress Bea Arthur  famous for her role as Dorothy in the TV show ‘Golden Girls’ – sold for nearly $2 million at a Christie’s auction in New York on Wednesday night.Arthur, famous for her Emmywinning roles in the 1970s and '80s television series ‘Maude’ and ‘The Golden Girls,’ died of cancer in 2009 at age 86.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.4166666666666667, 'p': 0.29411764705882354, 'f': 0.3448275813555292}, 'rouge-2': {'r': 0.19047619047619047, 'p': 0.13559322033898305, 'f': 0.15841583672581136}, 'rouge-l': {'r': 0.3611111111111111, 'p': 0.2549019607843137, 'f': 0.2988505698612763}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - Las Vegas Sands made a $2.3 billion profit that year.Caesars lost $2.9 billion.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.05263157894736842, 'p': 0.14285714285714285, 'f': 0.07692307298816588}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.05263157894736842, 'p': 0.14285714285714285, 'f': 0.07692307298816588}}]
@@@@@@@
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Summary - Watch Sumwalt's remarks at hearing » Flying at night in poor weather conditions likely contributed to the crashes in Texas and Alaska of three medical helicopters that killed 11 people, the NTSB said.The pilot, a paramedic and a flight nurse were killed, the NTSB said.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.14285714285714285, 'p': 0.13157894736842105, 'f': 0.13698629637830753}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.11428571428571428, 'p': 0.10526315789473684, 'f': 0.109589036104335}}]

In [104]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.500000  0.339623  0.404494  rouge-1     0
0   0.324324  0.173913  0.226415  rouge-2     0
0   0.444444  0.301887  0.359551  rouge-l     0
0   0.206897  0.136364  0.164384  rouge-1     1
0   0.035714  0.018868  0.024691  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.010000  0.014925  rouge-2  1999
0   0.212121  0.084337  0.120690  rouge-l  1999
0   0.425000  0.314815  0.361702  rouge-1  2000
0   0.187500  0.136364  0.157895  rouge-2  2000
0   0.275000  0.203704  0.234043  rouge-l  2000

[6003 rows x 5 columns]

In [105]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.345945  0.262240  0.281426  1000.0
rouge-2  0.127183  0.084575  0.094546  1000.0
rouge-l  0.265645  0.201181  0.215508  1000.0

#### Cosine similarity in TfIdf

In [106]:
embeddings=X_tdidf.toarray()
embeddings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.24741204,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.24974463, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.285293  , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.19403195,
        0.        ]])

In [107]:
len(sentences)

13

In [108]:
sim_matrix=cosine_similarity_matrix(sentences,embeddings)

In [109]:
sim_matrix.shape

(13, 13)

#### Page rank using sentence similarity matrix

In [110]:
ranked_sentences,sentence_scores=page_ranked_sentence(sim_matrix,sentences)
ranked_sentences

[3, 0, 12, 6, 7, 8, 1, 5, 2, 4, 9, 10, 11]

In [111]:
nos=2
my_list=sorted(ranked_sentences[:nos])
my_list

[0, 3]

In [112]:
summary=combine_sentences(my_list,sentences)
summary

'Lionel Messi will sign a new contract at Barcelona, making him the bestpaid player in the world, before the end of the week.New deal Barcelona star Lionel Messi is set to sign a new contract with the Catalan club Close Messi (left) could still be a La Liga winner this season if his side can defeat Atletico Madrid'

#### Evaluation using ROGUE

In [113]:
highlights0_processed

"Lionel Messi set to sign new Barcelona contract worth £15.5m a season The Barca star will become the bestpaid player in the world Cristiano Ronaldo currently earns £15m a season at Real Madrid Messi's £200m buyout clause will remain in place ."

In [114]:
rouge_metric(summary, highlights0_processed)

[{'rouge-1': {'r': 0.4864864864864865,
   'p': 0.3829787234042553,
   'f': 0.4285714236422903},
  'rouge-2': {'r': 0.175, 'p': 0.12962962962962962, 'f': 0.14893616532367604},
  'rouge-l': {'r': 0.43243243243243246,
   'p': 0.3404255319148936,
   'f': 0.3809523760232426}}]

#### For datset sample

In [272]:
r_metric_all={}
def summarize_dataset_sample():
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        vectorizer = TfidfVectorizer(stop_words="english")
        X_tdidf = vectorizer.fit_transform(sentences)
        embeddings = X_tdidf.toarray()
        sim_matrix=cosine_similarity_matrix(sentences,embeddings)
        sim_matrix=np.nan_to_num(sim_matrix)
        #print(sim_matrix)
        ranked_sentences,sentence_scores=page_ranked_sentence(sim_matrix,sentences)
        nos=2
        my_list=sorted(ranked_sentences[:nos])
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties."I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.4722222222222222, 'p': 0.25757575757575757, 'f': 0.3333333287658593}, 'rouge-2': {'r': 0.32432432432432434, 'p': 0.15584415584415584, 'f': 0.21052631140504782}, 'rouge-l': {'r': 0.3888888888888889, 'p': 0.21212121212121213, 'f': 0.27450979935409464}}]
@@@@@@@
WASHINGTON (CNN)  Virginia prosecutors are asking a state court to set a November 9 execution date for John Allen Muhammad, convicted in a series of sniperstyle shootings that terrorized the Washington area in 2002.Muhammad, now 48, was convicted of murder in the death of Dean Harold Meyers at a Manassas, Virginia, filling station.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.20689655172413793, 'p': 0.13636363636363635, 'f': 0.1643835568549448}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.018867924528301886, 'f': 0.024691353500991532}, 'rouge-l': {'r': 0.20689655172413793, 'p': 0.13636363636363635, 'f': 0.1643835568549448}}]
@@@@@@@
The former Rangers chief executive (right) came to the defense of the existing regime at Ibrox Green came to the defence of Newcastle chairman Mike Ashley (left) after saying that he did not like him Pausing for dramatic effect throughout Green, in hospital for a knee operation, said 'Days like today make me think I should go back (to Rangers).'You have Sandy Easdale, who has put money in – Dave King who hasn't.'
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.375, 'p': 0.3181818181818182, 'f': 0.3442622901155604}, 'rouge-2': {'r': 0.08064516129032258, 'p': 0.06944444444444445, 'f': 0.07462686069948796}, 'rouge-l': {'r': 0.25, 'p': 0.21212121212121213, 'f': 0.2295081917549047}}]
@@@@@@@
The McDonald's in Ipswich, Suffolk, where a G4S security guard was pushed to the ground and £17,000 was stolen in November 2011 All three were on a work placement a mile away at Ipswich Town Football Club after being allowed out of Hollesley Bay open prison, near Woodbridge.Employer Mr Gillespie was on day release working at Ipswich Town Football Club, pictured, when the robbery took place Open prison Kenneth Gillespie had been serving a life sentence at Hollesley Bay in Woodbridge, Suffolk He has been at large since failing to return from day release on January 23.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.5483870967741935, 'p': 0.4533333333333333, 'f': 0.4963503600085247}, 'rouge-2': {'r': 0.23076923076923078, 'p': 0.1956521739130435, 'f': 0.2117647009162631}, 'rouge-l': {'r': 0.3064516129032258, 'p': 0.25333333333333335, 'f': 0.27737225781874375}}]
@@@@@@@
Scroll down for video Cheick Tiote (left) and Papiss Cisse (right) are among the players being closely monitored following their return from international qualifiers in Africa, where the Ebola crisis is deepening Swansea City's Wilfried Bony, who plays for Ivory Coast, will also be tested after competing in West AfricaHe said 'Out of our players, it is only Bony that has returned from Africa.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2602739726027397, 'p': 0.3220338983050847, 'f': 0.28787878293503216}, 'rouge-2': {'r': 0.06741573033707865, 'p': 0.09523809523809523, 'f': 0.07894736356734794}, 'rouge-l': {'r': 0.1506849315068493, 'p': 0.1864406779661017, 'f': 0.16666666172291106}}]
@@@@@@@
Paulinho (right) isn't a ball winner or a creator and it isn't clear what he brings to BrazilA whole new ball game Ferdinand (right) plays beach volleyball with the Da Silva twins and a friend I got back to Rio late, and there were still umpteen impromptu matches being played all along the beach.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.21621621621621623, 'p': 0.18181818181818182, 'f': 0.19753085923487287}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.13513513513513514, 'p': 0.11363636363636363, 'f': 0.12345678516079886}}]
@@@@@@@
Cesar Lucas was working as a delivery boy at Sal’s Pizza in the same Manhattan neighborhood as the woman’s luxury apartment building.Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.37681159420289856, 'p': 0.37681159420289856, 'f': 0.3768115892028986}, 'rouge-2': {'r': 0.047619047619047616, 'p': 0.041666666666666664, 'f': 0.04444443946666723}, 'rouge-l': {'r': 0.21739130434782608, 'p': 0.21739130434782608, 'f': 0.21739129934782622}}]
@@@@@@@
A topless painting of the late actress Bea Arthur  famous for her role as Dorothy in the TV show ‘Golden Girls’ – sold for nearly $2 million at a Christie’s auction in New York on Wednesday night.Arthur, famous for her Emmywinning roles in the 1970s and '80s television series ‘Maude’ and ‘The Golden Girls,’ died of cancer in 2009 at age 86.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.4166666666666667, 'p': 0.29411764705882354, 'f': 0.3448275813555292}, 'rouge-2': {'r': 0.19047619047619047, 'p': 0.13559322033898305, 'f': 0.15841583672581136}, 'rouge-l': {'r': 0.3611111111111111, 'p': 0.2549019607843137, 'f': 0.2988505698612763}}]
@@@@@@@
Las Vegas Sands made a $2.3 billion profit that year.Caesars lost $2.9 billion.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.05263157894736842, 'p': 0.14285714285714285, 'f': 0.07692307298816588}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.05263157894736842, 'p': 0.14285714285714285, 'f': 0.07692307298816588}}]
@@@@@@@
Watch Sumwalt's remarks at hearing » Flying at night in poor weather conditions likely contributed to the crashes in Texas and Alaska of three medical helicopters that killed 11 people, the NTSB said.iReport Watch smoke pour from a medical chopper crash in Michigan A December 2007 accident in Cherokee, Alabama, was likely caused by the pilot flying too low over trees, the NTSB said.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.14285714285714285, 'p': 0.09433962264150944, 'f': 0.11363635884555806}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.08571428571428572, 'p': 0.05660377358490566, 'f': 0.06818181339101273}}]

In [273]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.472222  0.257576  0.333333  rouge-1     0
0   0.324324  0.155844  0.210526  rouge-2     0
0   0.388889  0.212121  0.274510  rouge-l     0
0   0.206897  0.136364  0.164384  rouge-1     1
0   0.035714  0.018868  0.024691  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.010000  0.014925  rouge-2  1999
0   0.212121  0.084337  0.120690  rouge-l  1999
0   0.425000  0.314815  0.361702  rouge-1  2000
0   0.187500  0.136364  0.157895  rouge-2  2000
0   0.275000  0.203704  0.234043  rouge-l  2000

[6003 rows x 5 columns]

In [274]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.353582  0.260679  0.285236  1000.0
rouge-2  0.128587  0.084048  0.095372  1000.0
rouge-l  0.270948  0.199625  0.218157  1000.0

### Build sentence related features

In [118]:
article_processed=text_preprocess(article0)
highlights_processed=text_preprocess(highlights0)
sentences=text_to_sentences(article_processed)
article_processed_more=text_preprocess_more(article_processed)

In [119]:
df = pd.DataFrame(sentences)
df.columns=['sentence']
df.head()

                                            sentence
0  Lionel Messi will sign a new contract at Barce...
1  The player’s father met with the club official...
2  Messi’s £200m buyout clause will remain but th...
3  New deal Barcelona star Lionel Messi is set to...
4  With the complexity of bonuses and addons the ...

In [120]:
df['sentence_processed_more']=df.sentence.apply(text_preprocess_more)
df.head()

,sentence,sentence_processed_more
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...
1,The player’s father met with the club official...,the player s father meet with the club officia...
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...

In [121]:
# Sentence position
df['sentence_position']=df.index+1
df['sentence_position']=df['sentence_position']/df['sentence_position'].max()
df.head()

,sentence,sentence_processed_more,sentence_position
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615

In [122]:
# Sentence length
df['sentence_length']=df.sentence.apply(lambda x: len(nlp(x)))
df

,sentence,sentence_processed_more,sentence_position,sentence_length
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923,26
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846,40
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769,41
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692,38
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615,36
5,Barcelona had planned to announce the new deal...,barcelona have plan to announce the new deal a...,0.461538,39
6,As well as being the world’s top two players M...,as well as be the world s top two player messi...,0.538462,82
7,Stuttering Messi has had a quiet season by his...,stutter messi have have a quiet season by his ...,0.615385,55
8,Messi’s representative and father Jorge was in...,messi s representative and father jorge be inf...,0.692308,33
9,"Despite that, it is no secret that the Barça f...",despite that it be no secret that the bar a fo...,0.769231,32
10,A bid for Aguero would only be possible if Bar...,a bid for aguero would only be possible if bar...,0.846154,18
11,This summer will see Barca celebrate winning t...,this summer will see barca celebrate win their...,0.923077,19
12,Wanted Messi would love for international team...,want messi would love for international teamma...,1.000000,34

In [123]:
# TF based sentence score
word_frequencies=getWordFreq(article_processed_more)
ranked_sentences,sentence_scores=getSentScore(word_frequencies,sentences)

In [124]:
[i for i in df.index if i not in ranked_sentences]

[]

In [125]:
sentences[34]

IndexError: list index out of range

In [126]:
len(ranked_sentences)

13

In [127]:
len(sentence_scores)

13

In [128]:
len(sentences)

13

In [129]:
sentence_scores[34]

KeyError: 34

In [130]:
df['sentence_tf_avg']=sentence_scores.values()
df.head()

,sentence,sentence_processed_more,sentence_position,sentence_length,sentence_tf_avg
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923,26,3.615385
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846,40,3.846154
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769,41,3.076923
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692,38,7.076923
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615,36,2.615385

In [131]:
# POS ratio
df['sentence_word_list']=df.sentence.apply(lambda x: [t for t in nlp(x)])
df['sentence_pos_list']=df.sentence.apply(lambda x: [t.pos_ for t in nlp(x)])
df.head()

,sentence,sentence_processed_more,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923,26,3.615385,"[Lionel, Messi, will, sign, a, new, contract, ...","[PROPN, PROPN, AUX, VERB, DET, ADJ, NOUN, ADP,..."
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846,40,3.846154,"[The, player, ’s, father, met, with, the, club...","[DET, NOUN, PART, NOUN, VERB, ADP, DET, NOUN, ..."
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769,41,3.076923,"[Messi, ’s, £, 200, m, buyout, clause, will, r...","[PROPN, PART, SYM, NUM, NOUN, NOUN, NOUN, AUX,..."
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692,38,7.076923,"[New, deal, Barcelona, star, Lionel, Messi, is...","[ADJ, NOUN, PROPN, NOUN, PROPN, PROPN, AUX, VE..."
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615,36,2.615385,"[With, the, complexity, of, bonuses, and, addo...","[SCONJ, DET, NOUN, ADP, NOUN, CCONJ, NOUN, DET..."

In [132]:
df['sentence_propn_count']=df['sentence_pos_list'].apply(lambda x: x.count('PROPN')/len(x))
df['sentence_noun_count']=df['sentence_pos_list'].apply(lambda x: x.count('NOUN')/len(x))
df['sentence_verb_count']=df['sentence_pos_list'].apply(lambda x: x.count('VERB')/len(x))
df['sentence_adv_count']=df['sentence_pos_list'].apply(lambda x: x.count('ADV')/len(x))
df['sentence_adj_count']=df['sentence_pos_list'].apply(lambda x: x.count('ADJ')/len(x))
df.head()

,sentence,sentence_processed_more,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923,26,3.615385,"[Lionel, Messi, will, sign, a, new, contract, ...","[PROPN, PROPN, AUX, VERB, DET, ADJ, NOUN, ADP,...",0.115385,0.192308,0.076923,0.000000,0.076923
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846,40,3.846154,"[The, player, ’s, father, met, with, the, club...","[DET, NOUN, PART, NOUN, VERB, ADP, DET, NOUN, ...",0.125000,0.200000,0.075000,0.025000,0.025000
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769,41,3.076923,"[Messi, ’s, £, 200, m, buyout, clause, will, r...","[PROPN, PART, SYM, NUM, NOUN, NOUN, NOUN, AUX,...",0.121951,0.219512,0.121951,0.000000,0.000000
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692,38,7.076923,"[New, deal, Barcelona, star, Lionel, Messi, is...","[ADJ, NOUN, PROPN, NOUN, PROPN, PROPN, AUX, VE...",0.236842,0.184211,0.078947,0.052632,0.078947
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615,36,2.615385,"[With, the, complexity, of, bonuses, and, addo...","[SCONJ, DET, NOUN, ADP, NOUN, CCONJ, NOUN, DET...",0.055556,0.305556,0.055556,0.027778,0.083333

In [133]:
# Numbers in sentences
df['sentence_num_count']=df['sentence_pos_list'].apply(lambda x: x.count('NUM')/len(x))
df.head()

,sentence,sentence_processed_more,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count,sentence_num_count
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923,26,3.615385,"[Lionel, Messi, will, sign, a, new, contract, ...","[PROPN, PROPN, AUX, VERB, DET, ADJ, NOUN, ADP,...",0.115385,0.192308,0.076923,0.000000,0.076923,0.000000
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846,40,3.846154,"[The, player, ’s, father, met, with, the, club...","[DET, NOUN, PART, NOUN, VERB, ADP, DET, NOUN, ...",0.125000,0.200000,0.075000,0.025000,0.025000,0.050000
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769,41,3.076923,"[Messi, ’s, £, 200, m, buyout, clause, will, r...","[PROPN, PART, SYM, NUM, NOUN, NOUN, NOUN, AUX,...",0.121951,0.219512,0.121951,0.000000,0.000000,0.073171
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692,38,7.076923,"[New, deal, Barcelona, star, Lionel, Messi, is...","[ADJ, NOUN, PROPN, NOUN, PROPN, PROPN, AUX, VE...",0.236842,0.184211,0.078947,0.052632,0.078947,0.000000
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615,36,2.615385,"[With, the, complexity, of, bonuses, and, addo...","[SCONJ, DET, NOUN, ADP, NOUN, CCONJ, NOUN, DET...",0.055556,0.305556,0.055556,0.027778,0.083333,0.027778

In [134]:
#Stopwords in sentences
df['sentence_stopword_count']=df['sentence'].apply(lambda x: sum([1 for t in nlp(x) if t.text in stopwords]))
df['sentence_stopword_count']=df['sentence_stopword_count']/df['sentence_length']
df.head()

,sentence,sentence_processed_more,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count,sentence_num_count,sentence_stopword_count
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923,26,3.615385,"[Lionel, Messi, will, sign, a, new, contract, ...","[PROPN, PROPN, AUX, VERB, DET, ADJ, NOUN, ADP,...",0.115385,0.192308,0.076923,0.000000,0.076923,0.000000,0.423077
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846,40,3.846154,"[The, player, ’s, father, met, with, the, club...","[DET, NOUN, PART, NOUN, VERB, ADP, DET, NOUN, ...",0.125000,0.200000,0.075000,0.025000,0.025000,0.050000,0.375000
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769,41,3.076923,"[Messi, ’s, £, 200, m, buyout, clause, will, r...","[PROPN, PART, SYM, NUM, NOUN, NOUN, NOUN, AUX,...",0.121951,0.219512,0.121951,0.000000,0.000000,0.073171,0.365854
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692,38,7.076923,"[New, deal, Barcelona, star, Lionel, Messi, is...","[ADJ, NOUN, PROPN, NOUN, PROPN, PROPN, AUX, VE...",0.236842,0.184211,0.078947,0.052632,0.078947,0.000000,0.289474
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615,36,2.615385,"[With, the, complexity, of, bonuses, and, addo...","[SCONJ, DET, NOUN, ADP, NOUN, CCONJ, NOUN, DET...",0.055556,0.305556,0.055556,0.027778,0.083333,0.027778,0.416667

In [135]:
# Rogue-2 per sentence
df['sentence_rougue2_f']=df['sentence'].apply(lambda x: rouge_metric(x, highlights_processed)[0]['rouge-2']['f'])
df.head()

,sentence,sentence_processed_more,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count,sentence_num_count,sentence_stopword_count,sentence_rougue2_f
0,Lionel Messi will sign a new contract at Barce...,lionel messi will sign a new contract at barce...,0.076923,26,3.615385,"[Lionel, Messi, will, sign, a, new, contract, ...","[PROPN, PROPN, AUX, VERB, DET, ADJ, NOUN, ADP,...",0.115385,0.192308,0.076923,0.000000,0.076923,0.000000,0.423077,0.161290
1,The player’s father met with the club official...,the player s father meet with the club officia...,0.153846,40,3.846154,"[The, player, ’s, father, met, with, the, club...","[DET, NOUN, PART, NOUN, VERB, ADP, DET, NOUN, ...",0.125000,0.200000,0.075000,0.025000,0.025000,0.050000,0.375000,0.000000
2,Messi’s £200m buyout clause will remain but th...,messi s 200 m buyout clause will remain but th...,0.230769,41,3.076923,"[Messi, ’s, £, 200, m, buyout, clause, will, r...","[PROPN, PART, SYM, NUM, NOUN, NOUN, NOUN, AUX,...",0.121951,0.219512,0.121951,0.000000,0.000000,0.073171,0.365854,0.333333
3,New deal Barcelona star Lionel Messi is set to...,new deal barcelona star lionel messi be set to...,0.307692,38,7.076923,"[New, deal, Barcelona, star, Lionel, Messi, is...","[ADJ, NOUN, PROPN, NOUN, PROPN, PROPN, AUX, VE...",0.236842,0.184211,0.078947,0.052632,0.078947,0.000000,0.289474,0.080000
4,With the complexity of bonuses and addons the ...,with the complexity of bonus and addon the gap...,0.384615,36,2.615385,"[With, the, complexity, of, bonuses, and, addo...","[SCONJ, DET, NOUN, ADP, NOUN, CCONJ, NOUN, DET...",0.055556,0.305556,0.055556,0.027778,0.083333,0.027778,0.416667,0.000000

In [136]:
df.columns

Index(['sentence', 'sentence_processed_more', 'sentence_position',
       'sentence_length', 'sentence_tf_avg', 'sentence_word_list',
       'sentence_pos_list', 'sentence_propn_count', 'sentence_noun_count',
       'sentence_verb_count', 'sentence_adv_count', 'sentence_adj_count',
       'sentence_num_count', 'sentence_stopword_count', 'sentence_rougue2_f'],
      dtype='object')

#### For datset sample

In [143]:
def getSentenceFeatures(sentences,article_processed_more,highlights_processed):
    ## Dataframe Creation
    df = pd.DataFrame(sentences)
    df.columns=['sentence']
    #df['sentence_processed_more']=df.sentence.apply(text_preprocess_more)
    # Sentence position
    df['sentence_position']=df.index+1
    df['sentence_position']=df['sentence_position']/df['sentence_position'].max()
    # Sentence length
    df['sentence_length']=df.sentence.apply(lambda x: len(nlp(x)))
    # TF based sentence score
    word_frequencies=getWordFreq(article_processed_more)
    ranked_sentences,sentence_scores=getSentScore(word_frequencies,sentences)
    #print(sentence_scores)
    df['sentence_tf_avg']=sentence_scores.values()
    # POS ratio
    df['sentence_word_list']=df.sentence.apply(lambda x: [t for t in nlp(x)])
    df['sentence_pos_list']=df.sentence.apply(lambda x: [t.pos_ for t in nlp(x)])
    df['sentence_propn_count']=df['sentence_pos_list'].apply(lambda x: x.count('PROPN')/len(x))
    df['sentence_noun_count']=df['sentence_pos_list'].apply(lambda x: x.count('NOUN')/len(x))
    df['sentence_verb_count']=df['sentence_pos_list'].apply(lambda x: x.count('VERB')/len(x))
    df['sentence_adv_count']=df['sentence_pos_list'].apply(lambda x: x.count('ADV')/len(x))
    df['sentence_adj_count']=df['sentence_pos_list'].apply(lambda x: x.count('ADJ')/len(x))
    # Numbers in sentences
    df['sentence_num_count']=df['sentence_pos_list'].apply(lambda x: x.count('NUM')/len(x))
    #Stopwords in sentences
    df['sentence_stopword_count']=df['sentence'].apply(lambda x: sum([1 for t in nlp(x) if t.text in stopwords]))
    df['sentence_stopword_count']=df['sentence_stopword_count']/df['sentence_length']
    # Rogue-2 per sentence
    df['sentence_rougue2_f']=df['sentence'].apply(lambda x: rouge_metric(x, highlights_processed)[0]['rouge-2']['f'])
    return df

In [157]:
def build_dataset_sample():
    dict_df={}
    i=0
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        print(i)
        i+=1
        article_processed=text_preprocess(article)
        article_processed_more=text_preprocess_more(article_processed)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        df=getSentenceFeatures(sentences,article_processed_more,highlights_processed)
        df['sid']=sid
        #df_master=pd.concat([df_master,df])
        dict_df[sid]=df
        #break
    return dict_df

In [158]:
dict_df=build_dataset_sample()
len(dict_df)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000

2001

In [159]:
df_master=pd.concat(dict_df.values(), ignore_index=True)
df_master

,sentence,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count,sentence_num_count,sentence_stopword_count,sentence_rougue2_f,sid
0,"LONDON, England (Reuters) Harry Potter star D...",0.047619,46,5.285714,"[LONDON, ,, England, (, Reuters, ), , Harry, ...","[PROPN, PUNCT, PROPN, PUNCT, PROPN, PUNCT, SPA...",0.173913,0.108696,0.108696,0.000000,0.000000,0.108696,0.239130,0.222222,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
1,"Daniel Radcliffe as Harry Potter in ""Harry Pot...",0.095238,48,6.571429,"[Daniel, Radcliffe, as, Harry, Potter, in, "", ...","[PROPN, PROPN, ADP, PROPN, PROPN, ADP, PUNCT, ...",0.145833,0.250000,0.062500,0.020833,0.041667,0.000000,0.354167,0.303797,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
2,"""I don't plan to be one of those people who, a...",0.142857,42,4.000000,"["", I, do, n't, plan, to, be, one, of, those, ...","[PUNCT, PRON, AUX, PART, VERB, PART, AUX, NUM,...",0.000000,0.142857,0.095238,0.095238,0.071429,0.047619,0.357143,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
3,"""I don't think I'll be particularly extravagant.",0.190476,11,0.571429,"["", I, do, n't, think, I, 'll, be, particularl...","[PUNCT, PRON, AUX, PART, VERB, PRON, AUX, AUX,...",0.000000,0.000000,0.090909,0.090909,0.090909,0.000000,0.181818,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
4,"""The things I like buying are things that cost...",0.238095,21,0.428571,"["", The, things, I, like, buying, are, things,...","[PUNCT, DET, NOUN, PRON, VERB, VERB, AUX, NOUN...",0.000000,0.285714,0.142857,0.047619,0.000000,0.047619,0.238095,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59005,After a break Monday for a political fundraise...,0.833333,53,5.625000,"[After, a, break, Monday, for, a, political, f...","[ADP, DET, NOUN, PROPN, ADP, DET, ADJ, NOUN, P...",0.188679,0.150943,0.132075,0.018868,0.018868,0.000000,0.358491,0.063158,566ee8a8f59241a64a1a88724f14aca68f4a635b
59006,"Speaking to business leaders on Saturday, the ...",0.875000,25,3.875000,"[Speaking, to, business, leaders, on, Saturday...","[VERB, ADP, NOUN, NOUN, ADP, PROPN, PUNCT, DET...",0.120000,0.240000,0.160000,0.040000,0.000000,0.000000,0.360000,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b
59007,"""We've been a little bit lazy, I think, over t...",0.916667,19,0.875000,"["", We, 've, been, a, little, bit, lazy, ,, I,...","[PUNCT, PRON, AUX, AUX, DET, ADJ, NOUN, ADJ, P...",0.000000,0.157895,0.052632,0.000000,0.157895,0.000000,0.263158,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b
59008,"We've kind of taken for granted well, people ...",0.958333,39,2.875000,"[We, 've, kind, of, taken, for, granted, , we...","[PRON, AUX, ADV, ADV, VERB, ADP, VERB, SPACE, ...",0.051282,0.076923,0.205128,0.128205,0.051282,0.000000,0.358974,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b
59009,"""We can do much better than we're doing right ...",1.000000,14,0.250000,"["", We, can, do, much, better, than, we, 're, ...","[PUNCT, PRON, AUX, VERB, ADV, ADJ, SCONJ, PRON...",0.000000,0.000000,0.142857,0.214286,0.071429,0.000000,0.428571,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b

In [160]:
df_master['sentence_rougue2_f_norm']=df_master.groupby('sid')['sentence_rougue2_f'].apply(lambda x: x/x.max()).fillna(0)
df_master

,sentence,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count,sentence_num_count,sentence_stopword_count,sentence_rougue2_f,sid,sentence_rougue2_f_norm
0,"LONDON, England (Reuters) Harry Potter star D...",0.047619,46,5.285714,"[LONDON, ,, England, (, Reuters, ), , Harry, ...","[PROPN, PUNCT, PROPN, PUNCT, PROPN, PUNCT, SPA...",0.173913,0.108696,0.108696,0.000000,0.000000,0.108696,0.239130,0.222222,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.595960
1,"Daniel Radcliffe as Harry Potter in ""Harry Pot...",0.095238,48,6.571429,"[Daniel, Radcliffe, as, Harry, Potter, in, "", ...","[PROPN, PROPN, ADP, PROPN, PROPN, ADP, PUNCT, ...",0.145833,0.250000,0.062500,0.020833,0.041667,0.000000,0.354167,0.303797,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.814730
2,"""I don't plan to be one of those people who, a...",0.142857,42,4.000000,"["", I, do, n't, plan, to, be, one, of, those, ...","[PUNCT, PRON, AUX, PART, VERB, PART, AUX, NUM,...",0.000000,0.142857,0.095238,0.095238,0.071429,0.047619,0.357143,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.000000
3,"""I don't think I'll be particularly extravagant.",0.190476,11,0.571429,"["", I, do, n't, think, I, 'll, be, particularl...","[PUNCT, PRON, AUX, PART, VERB, PRON, AUX, AUX,...",0.000000,0.000000,0.090909,0.090909,0.090909,0.000000,0.181818,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.000000
4,"""The things I like buying are things that cost...",0.238095,21,0.428571,"["", The, things, I, like, buying, are, things,...","[PUNCT, DET, NOUN, PRON, VERB, VERB, AUX, NOUN...",0.000000,0.285714,0.142857,0.047619,0.000000,0.047619,0.238095,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59005,After a break Monday for a political fundraise...,0.833333,53,5.625000,"[After, a, break, Monday, for, a, political, f...","[ADP, DET, NOUN, PROPN, ADP, DET, ADJ, NOUN, P...",0.188679,0.150943,0.132075,0.018868,0.018868,0.000000,0.358491,0.063158,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.297744
59006,"Speaking to business leaders on Saturday, the ...",0.875000,25,3.875000,"[Speaking, to, business, leaders, on, Saturday...","[VERB, ADP, NOUN, NOUN, ADP, PROPN, PUNCT, DET...",0.120000,0.240000,0.160000,0.040000,0.000000,0.000000,0.360000,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000
59007,"""We've been a little bit lazy, I think, over t...",0.916667,19,0.875000,"["", We, 've, been, a, little, bit, lazy, ,, I,...","[PUNCT, PRON, AUX, AUX, DET, ADJ, NOUN, ADJ, P...",0.000000,0.157895,0.052632,0.000000,0.157895,0.000000,0.263158,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000
59008,"We've kind of taken for granted well, people ...",0.958333,39,2.875000,"[We, 've, kind, of, taken, for, granted, , we...","[PRON, AUX, ADV, ADV, VERB, ADP, VERB, SPACE, ...",0.051282,0.076923,0.205128,0.128205,0.051282,0.000000,0.358974,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000
59009,"""We can do much better than we're doing right ...",1.000000,14,0.250000,"["", We, can, do, much, better, than, we, 're, ...","[PUNCT, PRON, AUX, VERB, ADV, ADJ, SCONJ, PRON...",0.000000,0.000000,0.142857,0.214286,0.071429,0.000000,0.428571,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000

In [161]:
df_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59010 entries, 0 to 59009
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sentence                 59010 non-null  object
 1   sentence_position        59010 non-null  float64
 2   sentence_length          59010 non-null  int64
 3   sentence_tf_avg          59010 non-null  float64
 4   sentence_word_list       59010 non-null  object
 5   sentence_pos_list        59010 non-null  object
 6   sentence_propn_count     59010 non-null  float64
 7   sentence_noun_count      59010 non-null  float64
 8   sentence_verb_count      59010 non-null  float64
 9   sentence_adv_count       59010 non-null  float64
 10  sentence_adj_count       59010 non-null  float64
 11  sentence_num_count       59010 non-null  float64
 12  sentence_stopword_count  59010 non-null  float64
 13  sentence_rougue2_f       59010 non-null  float64
 14  sid                      59010 non-null  object
 15  sentence_rougue2_f_norm  59010 non-null  float64
dtypes: float64(11), int64(1), object(4)
memory usage: 7.2+ MB

In [162]:
df_master.columns

Index(['sentence', 'sentence_position', 'sentence_length', 'sentence_tf_avg',
       'sentence_word_list', 'sentence_pos_list', 'sentence_propn_count',
       'sentence_noun_count', 'sentence_verb_count', 'sentence_adv_count',
       'sentence_adj_count', 'sentence_num_count', 'sentence_stopword_count',
       'sentence_rougue2_f', 'sid', 'sentence_rougue2_f_norm'],
      dtype='object')

#### Linear Regression Model

In [163]:
sid_list=df_master.sid.unique().tolist()
sid_list_train=sid_list[:(len(sid_list)*80)//100]
sid_list_test=sid_list[(len(sid_list)*80)//100:]
print(len(sid_list_train))
print(len(sid_list_test))

1600
401

In [164]:
df_master

,sentence,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count,sentence_num_count,sentence_stopword_count,sentence_rougue2_f,sid,sentence_rougue2_f_norm
0,"LONDON, England (Reuters) Harry Potter star D...",0.047619,46,5.285714,"[LONDON, ,, England, (, Reuters, ), , Harry, ...","[PROPN, PUNCT, PROPN, PUNCT, PROPN, PUNCT, SPA...",0.173913,0.108696,0.108696,0.000000,0.000000,0.108696,0.239130,0.222222,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.595960
1,"Daniel Radcliffe as Harry Potter in ""Harry Pot...",0.095238,48,6.571429,"[Daniel, Radcliffe, as, Harry, Potter, in, "", ...","[PROPN, PROPN, ADP, PROPN, PROPN, ADP, PUNCT, ...",0.145833,0.250000,0.062500,0.020833,0.041667,0.000000,0.354167,0.303797,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.814730
2,"""I don't plan to be one of those people who, a...",0.142857,42,4.000000,"["", I, do, n't, plan, to, be, one, of, those, ...","[PUNCT, PRON, AUX, PART, VERB, PART, AUX, NUM,...",0.000000,0.142857,0.095238,0.095238,0.071429,0.047619,0.357143,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.000000
3,"""I don't think I'll be particularly extravagant.",0.190476,11,0.571429,"["", I, do, n't, think, I, 'll, be, particularl...","[PUNCT, PRON, AUX, PART, VERB, PRON, AUX, AUX,...",0.000000,0.000000,0.090909,0.090909,0.090909,0.000000,0.181818,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.000000
4,"""The things I like buying are things that cost...",0.238095,21,0.428571,"["", The, things, I, like, buying, are, things,...","[PUNCT, DET, NOUN, PRON, VERB, VERB, AUX, NOUN...",0.000000,0.285714,0.142857,0.047619,0.000000,0.047619,0.238095,0.000000,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59005,After a break Monday for a political fundraise...,0.833333,53,5.625000,"[After, a, break, Monday, for, a, political, f...","[ADP, DET, NOUN, PROPN, ADP, DET, ADJ, NOUN, P...",0.188679,0.150943,0.132075,0.018868,0.018868,0.000000,0.358491,0.063158,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.297744
59006,"Speaking to business leaders on Saturday, the ...",0.875000,25,3.875000,"[Speaking, to, business, leaders, on, Saturday...","[VERB, ADP, NOUN, NOUN, ADP, PROPN, PUNCT, DET...",0.120000,0.240000,0.160000,0.040000,0.000000,0.000000,0.360000,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000
59007,"""We've been a little bit lazy, I think, over t...",0.916667,19,0.875000,"["", We, 've, been, a, little, bit, lazy, ,, I,...","[PUNCT, PRON, AUX, AUX, DET, ADJ, NOUN, ADJ, P...",0.000000,0.157895,0.052632,0.000000,0.157895,0.000000,0.263158,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000
59008,"We've kind of taken for granted well, people ...",0.958333,39,2.875000,"[We, 've, kind, of, taken, for, granted, , we...","[PRON, AUX, ADV, ADV, VERB, ADP, VERB, SPACE, ...",0.051282,0.076923,0.205128,0.128205,0.051282,0.000000,0.358974,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000
59009,"""We can do much better than we're doing right ...",1.000000,14,0.250000,"["", We, can, do, much, better, than, we, 're, ...","[PUNCT, PRON, AUX, VERB, ADV, ADJ, SCONJ, PRON...",0.000000,0.000000,0.142857,0.214286,0.071429,0.000000,0.428571,0.000000,566ee8a8f59241a64a1a88724f14aca68f4a635b,0.000000

In [165]:
cols=['sentence_position', 'sentence_length', 'sentence_tf_avg', 'sentence_propn_count', 'sentence_noun_count', 'sentence_verb_count', 'sentence_adv_count', 'sentence_adj_count', 'sentence_num_count', 'sentence_stopword_count']

In [166]:
X=df_master[cols]
y=df_master['sentence_rougue2_f']
X_train=df_master[df_master.sid.isin(sid_list_train)][cols]
y_train=df_master[df_master.sid.isin(sid_list_train)]['sentence_rougue2_f']
X_test=df_master[df_master.sid.isin(sid_list_test)][cols]
y_test=df_master[df_master.sid.isin(sid_list_test)]['sentence_rougue2_f']
print(X.shape,X_train.shape,X_test.shape)
print(y.shape,y_train.shape,y_test.shape)

(59010, 10) (46896, 10) (12114, 10)
(59010,) (46896,) (12114,)

In [167]:
ridge_reg = Ridge(alpha=1.0)
ridge_reg.fit(X_train, y_train)
y_train_pred=ridge_reg.predict(X_train)
print("R2 score : ",r2_score(y_train, y_train_pred))
print("RMSE : ",mean_squared_error(y_train, y_train_pred,squared=False))
y_test_pred=ridge_reg.predict(X_test)
print("R2 score : ",r2_score(y_test, y_test_pred))
print("RMSE : ",mean_squared_error(y_test, y_test_pred,squared=False))

R2 score :  0.1416929834628201
RMSE :  0.05764321528595213
R2 score :  0.13265142418246378
RMSE :  0.05755305214144626

In [171]:
#filename = 'ridge_reg_model.pkl'
#pickle.dump(ridge_reg, open(filename, 'wb'))
filename = 'ridge_reg_model.pkl'
ridge_reg = pickle.load(open(filename, 'rb'))

In [172]:
lr_reg = LinearRegression()
lr_reg.fit(X_train, y_train)
y_train_pred=lr_reg.predict(X_train)
print("R2 score : ",r2_score(y_train, y_train_pred))
print("RMSE : ",mean_squared_error(y_train, y_train_pred,squared=False))
y_test_pred=lr_reg.predict(X_test)
print("R2 score : ",r2_score(y_test, y_test_pred))
print("RMSE : ",mean_squared_error(y_test, y_test_pred,squared=False))

R2 score :  0.14169379226377943
RMSE :  0.05764318812673177
R2 score :  0.1326748350676148
RMSE :  0.057552275419708726

In [173]:
#filename = 'lr_reg_model.pkl'
#pickle.dump(lr_reg, open(filename, 'wb'))
filename = 'lr_reg_model.pkl'
lr_reg = pickle.load(open(filename, 'rb'))

In [174]:
import statsmodels.api as sm
X_train_sm = sm.add_constant(X_train, prepend=False)
sm_reg = sm.OLS(y_train,X_train_sm)
res = sm_reg.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:     sentence_rougue2_f   R-squared:                       0.142
Model:                            OLS   Adj. R-squared:                  0.142
Method:                 Least Squares   F-statistic:                     774.0
Date:                Wed, 08 Mar 2023   Prob (F-statistic):               0.00
Time:                        20:30:04   Log-Likelihood:                 67274.
No. Observations:               46896   AIC:                        -1.345e+05
Df Residuals:                   46885   BIC:                        -1.344e+05
Df Model:                          10
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
sentence_position          -0.0373      0.001    -39.855      0.000      -0.039      -0.035
sentence_length            -0.0004   2.96e-05    -13.008      0.000      -0.000      -0.000
sentence_tf_avg             0.0106      0.000     46.323      0.000       0.010       0.011
sentence_propn_count        0.0419      0.004     10.945      0.000       0.034       0.049
sentence_noun_count         0.0377      0.004      9.671      0.000       0.030       0.045
sentence_verb_count         0.0246      0.006      4.423      0.000       0.014       0.035
sentence_adv_count         -0.0070      0.006     -1.106      0.269      -0.019       0.005
sentence_adj_count          0.0173      0.006      3.003      0.003       0.006       0.029
sentence_num_count          0.0610      0.007      8.614      0.000       0.047       0.075
sentence_stopword_count     0.0449      0.003     13.988      0.000       0.039       0.051
const                       0.0024      0.002      1.082      0.279      -0.002       0.007
==============================================================================
Omnibus:                    40728.804   Durbin-Watson:                   1.785
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1550158.325
Skew:                           4.095   Prob(JB):                         0.00
Kurtosis:                      29.949   Cond. No.                         977.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### XGBRegression Model

In [175]:
xgb_model = XGBRegressor()
xgb_model.fit(X_train, y_train)
y_train_pred=xgb_model.predict(X_train)
print("R2 score : ",r2_score(y_train, y_train_pred))
print("RMSE : ",mean_squared_error(y_train, y_train_pred,squared=False))
y_test_pred=xgb_model.predict(X_test)
print("R2 score : ",r2_score(y_test, y_test_pred))
print("RMSE : ",mean_squared_error(y_test, y_test_pred,squared=False))

R2 score :  0.453652368709913
RMSE :  0.045989787005185835
R2 score :  0.11930450604308718
RMSE :  0.05799418001491227

In [176]:
#filename = 'xgb_model_model.pkl'
#pickle.dump(xgb_model, open(filename, 'wb'))
filename = 'xgb_model_model.pkl'
xgb_model = pickle.load(open(filename, 'rb'))

In [178]:
df_master['sentence_rougue2_f_pred']=y_pred
df_master

NameError: name 'y_pred' is not defined

In [179]:
df_master.sort_values(by=['sid','sentence_rougue2_f_pred'],ascending=False)

KeyError: 'sentence_rougue2_f_pred'

In [722]:
#df_master.groupby('sid').head(2)

### SBERT+KMeans+CustomFeatures

In [180]:
def model_based_top_n(df,y_kmeans,nos):
    # Pick 1 sentence from each group
    my_list=[]
    for i in range(len(np.unique(y_kmeans))):
        my_dict={}
        for j in range(len(y_kmeans)):
            if y_kmeans[j]==i:
                my_dict[j] =  df['sentence_rougue2_f_pred'][j]
        my_list.extend([s for s,d in sorted(my_dict.items(), key=lambda item: item[1], reverse = True)][:nos])
    return my_list

In [181]:
article_processed=text_preprocess(article0)
article_processed_more=text_preprocess_more(article_processed)
highlights_processed=text_preprocess(highlights0)
sentences=text_to_sentences(article_processed)
embeddings = model.encode(sentences)
n_clusters = 2
nos=1
y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)

In [182]:
y_kmeans

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [183]:
len(np.unique(y_kmeans))

2

In [184]:
cluster_centers

array([[-0.11015956,  0.21178077, -0.2716884 , ..., -0.1619766 ,
        -0.30788615,  0.96253103],
       [-0.13900489,  0.32268262, -0.09069959, ..., -0.01662779,
        -0.1974927 ,  0.68162596]], dtype=float32)

In [185]:
dfF=getSentenceFeatures(sentences,article_processed_more,highlights_processed)
X=dfF[cols]
y_pred=xgb_model.predict(X)
dfF['sentence_rougue2_f_pred']=y_pred
dfF

,sentence,sentence_position,sentence_length,sentence_tf_avg,sentence_word_list,sentence_pos_list,sentence_propn_count,sentence_noun_count,sentence_verb_count,sentence_adv_count,sentence_adj_count,sentence_num_count,sentence_stopword_count,sentence_rougue2_f,sentence_rougue2_f_pred
0,Lionel Messi will sign a new contract at Barce...,0.076923,26,3.615385,"[Lionel, Messi, will, sign, a, new, contract, ...","[PROPN, PROPN, AUX, VERB, DET, ADJ, NOUN, ADP,...",0.115385,0.192308,0.076923,0.000000,0.076923,0.000000,0.423077,0.161290,0.106904
1,The player’s father met with the club official...,0.153846,40,3.846154,"[The, player, ’s, father, met, with, the, club...","[DET, NOUN, PART, NOUN, VERB, ADP, DET, NOUN, ...",0.125000,0.200000,0.075000,0.025000,0.025000,0.050000,0.375000,0.000000,0.077650
2,Messi’s £200m buyout clause will remain but th...,0.230769,41,3.076923,"[Messi, ’s, £, 200, m, buyout, clause, will, r...","[PROPN, PART, SYM, NUM, NOUN, NOUN, NOUN, AUX,...",0.121951,0.219512,0.121951,0.000000,0.000000,0.073171,0.365854,0.333333,0.046171
3,New deal Barcelona star Lionel Messi is set to...,0.307692,38,7.076923,"[New, deal, Barcelona, star, Lionel, Messi, is...","[ADJ, NOUN, PROPN, NOUN, PROPN, PROPN, AUX, VE...",0.236842,0.184211,0.078947,0.052632,0.078947,0.000000,0.289474,0.080000,0.056625
4,With the complexity of bonuses and addons the ...,0.384615,36,2.615385,"[With, the, complexity, of, bonuses, and, addo...","[SCONJ, DET, NOUN, ADP, NOUN, CCONJ, NOUN, DET...",0.055556,0.305556,0.055556,0.027778,0.083333,0.027778,0.416667,0.000000,0.030125
5,Barcelona had planned to announce the new deal...,0.461538,39,3.076923,"[Barcelona, had, planned, to, announce, the, n...","[PROPN, AUX, VERB, PART, VERB, DET, ADJ, NOUN,...",0.153846,0.153846,0.128205,0.051282,0.051282,0.000000,0.410256,0.000000,0.042743
6,As well as being the world’s top two players M...,0.538462,82,8.230769,"[As, well, as, being, the, world, ’s, top, two...","[ADV, ADV, ADP, AUX, DET, NOUN, PART, ADJ, NUM...",0.085366,0.195122,0.073171,0.048780,0.109756,0.036585,0.390244,0.000000,0.058575
7,Stuttering Messi has had a quiet season by his...,0.615385,55,6.307692,"[Stuttering, Messi, has, had, a, quiet, season...","[VERB, PROPN, AUX, VERB, DET, ADJ, NOUN, ADP, ...",0.090909,0.218182,0.090909,0.072727,0.090909,0.036364,0.381818,0.000000,0.048863
8,Messi’s representative and father Jorge was in...,0.692308,33,4.153846,"[Messi, ’s, representative, and, father, Jorge...","[PROPN, PART, NOUN, CCONJ, NOUN, PROPN, AUX, V...",0.121212,0.242424,0.060606,0.000000,0.121212,0.000000,0.333333,0.000000,0.017160
9,"Despite that, it is no secret that the Barça f...",0.769231,32,2.000000,"[Despite, that, ,, it, is, no, secret, that, t...","[SCONJ, PRON, PUNCT, PRON, AUX, DET, NOUN, SCO...",0.218750,0.093750,0.062500,0.031250,0.031250,0.000000,0.437500,0.000000,0.020065
10,A bid for Aguero would only be possible if Bar...,0.846154,18,1.230769,"[A, bid, for, Aguero, would, only, be, possibl...","[DET, NOUN, ADP, PROPN, AUX, ADV, AUX, ADJ, SC...",0.277778,0.111111,0.055556,0.111111,0.055556,0.000000,0.277778,0.000000,0.010659
11,This summer will see Barca celebrate winning t...,0.923077,19,1.000000,"[This, summer, will, see, Barca, celebrate, wi...","[DET, NOUN, AUX, VERB, PROPN, VERB, VERB, PRON...",0.052632,0.263158,0.210526,0.052632,0.000000,0.000000,0.315789,0.000000,0.010826
12,Wanted Messi would love for international team...,1.000000,34,4.769231,"[Wanted, Messi, would, love, for, internationa...","[VERB, PROPN, AUX, VERB, ADP, ADJ, NOUN, PROPN...",0.235294,0.088235,0.147059,0.058824,0.029412,0.000000,0.323529,0.117647,0.041132

In [186]:
my_list=model_based_top_n(dfF,y_kmeans,nos)
my_list

[5, 0]

In [187]:
summary=combine_sentences(my_list,sentences)
summary

'Lionel Messi will sign a new contract at Barcelona, making him the bestpaid player in the world, before the end of the week.Barcelona had planned to announce the new deal at the weekend but the unexpected prospect of winning the league on Saturday if they beat Atletico Madrid at home could even bring the announcement forward to Wednesday or Thursday.'

In [188]:
rouge_metric(summary, highlights0_processed)

[{'rouge-1': {'r': 0.40540540540540543, 'p': 0.3125, 'f': 0.3529411715543253},
  'rouge-2': {'r': 0.125, 'p': 0.08333333333333333, 'f': 0.09999999520000023},
  'rouge-l': {'r': 0.35135135135135137,
   'p': 0.2708333333333333,
   'f': 0.30588234802491354}}]

#### For dataset sample

In [191]:
r_metric_all={}
def summarize_dataset_sample():
    i=0
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        i+=1
        print(i)
        article_processed=text_preprocess(article)
        article_processed_more=text_preprocess_more(article_processed)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        n_clusters = 2
        nos=1
        y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
        df=getSentenceFeatures(sentences,article_processed_more,highlights_processed)
        X=df[cols]
        y_pred=xgb_model.predict(X)
        df['sentence_rougue2_f_pred']=y_pred
        my_list=model_based_top_n(df,y_kmeans,nos)
        summary=combine_sentences(my_list,sentences)
        #print(y_kmeans)
        #print(my_list)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

1
@@@@@@@
Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties."I don't think I'll be particularly extravagant.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.4722222222222222, 'p': 0.3953488372093023, 'f': 0.43037974187469963}, 'rouge-2': {'r': 0.32432432432432434, 'p': 0.24489795918367346, 'f': 0.2790697625392104}, 'rouge-l': {'r': 0.3888888888888889, 'p': 0.32558139534883723, 'f': 0.354430374786092}}]
2
@@@@@@@
John Allen Muhammad was sentenced to death for the slaying of Dean Harold Meyers.In a letter dated Wednesday, Senior Assistant Attorney General Katherine B. Burnett said the November date "has been carefully coordinated with the governor's office to insure his availability for any clemency petition Muhammad may wish to pursue."
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.20689655172413793, 'p': 0.13043478260869565, 'f': 0.15999999525688902}, 'rouge-2': {'r': 0.07142857142857142, 'p': 0.0392156862745098, 'f': 0.05063290681621576}, 'rouge-l': {'r': 0.20689655172413793, 'p': 0.13043478260869565, 'f': 0.15999999525688902}}]
3
@@@@@@@
'Derek Llambias (Chief Executive) might have had a charisma bypass, but actually he is a good guy doing a good job.Green said that current chief exec Derek Llambias (right) was a good guy despite having a 'charisma bypass' Green then hit out at wouldbe owner Dave King by mentioning he has numerous convictions against his name 'I met him when I took Llambias into Ibrox when we did the deal for the naming rights (sold to Sports Direct for a pound).
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.35714285714285715, 'p': 0.29850746268656714, 'f': 0.32520324707250975}, 'rouge-2': {'r': 0.08064516129032258, 'p': 0.0641025641025641, 'f': 0.0714285664938779}, 'rouge-l': {'r': 0.19642857142857142, 'p': 0.16417910447761194, 'f': 0.17886178365787575}}]
4
@@@@@@@
But extraordinarily, none will face charges because the Crown Prosecution Service says there is insufficient evidence.Employer Mr Gillespie was on day release working at Ipswich Town Football Club, pictured, when the robbery took place Open prison Kenneth Gillespie had been serving a life sentence at Hollesley Bay in Woodbridge, Suffolk He has been at large since failing to return from day release on January 23.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.41935483870967744, 'p': 0.4482758620689655, 'f': 0.4333333283388889}, 'rouge-2': {'r': 0.16666666666666666, 'p': 0.203125, 'f': 0.18309858659789738}, 'rouge-l': {'r': 0.24193548387096775, 'p': 0.25862068965517243, 'f': 0.2499999950055557}}]
5
@@@@@@@
Scroll down for video Cheick Tiote (left) and Papiss Cisse (right) are among the players being closely monitored following their return from international qualifiers in Africa, where the Ebola crisis is deepening Swansea City's Wilfried Bony, who plays for Ivory Coast, will also be tested after competing in West AfricaWe have a strategy for when they return and making sure they and their families are taken care of.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2465753424657534, 'p': 0.3103448275862069, 'f': 0.27480915537089917}, 'rouge-2': {'r': 0.06741573033707865, 'p': 0.08955223880597014, 'f': 0.0769230720225184}, 'rouge-l': {'r': 0.1506849315068493, 'p': 0.1896551724137931, 'f': 0.16793892636326568}}]
6
@@@@@@@
Having tipped Brazil to win the World Cup I must say their opening performance against Croatia was an anticlimax that highlighted vulnerabilities, particularly in defence.Paulinho (right) isn't a ball winner or a creator and it isn't clear what he brings to Brazil
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.2972972972972973, 'p': 0.28205128205128205, 'f': 0.28947367921398903}, 'rouge-2': {'r': 0.10810810810810811, 'p': 0.09523809523809523, 'f': 0.10126581780483922}, 'rouge-l': {'r': 0.1891891891891892, 'p': 0.1794871794871795, 'f': 0.18421052131925222}}]
7
@@@@@@@
By Daily Mail Reporters PUBLISHED 2040 EST, 26 January 2014 | UPDATED 0631 EST, 27 January 2014 Shattered Kia Graves is a former actress who once had a successful career with a modeling agency but since she was raped in 2012, she hasn't worked and her socially life has been shattered A woman who was attacked and raped in her Manhattan apartment in 2012 has come forward to detail the horrific night a teenage pizza boy allegedly assaulted her as her 7yearold daughter slept in the bed beside her.Appearing at Manhattan Supreme Court today, Lucas Cesar kept his head down and stared at the table in front of him until he was asked to plea.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.4492753623188406, 'p': 0.34831460674157305, 'f': 0.3924050583712547}, 'rouge-2': {'r': 0.16666666666666666, 'p': 0.12389380530973451, 'f': 0.1421319748037828}, 'rouge-l': {'r': 0.2608695652173913, 'p': 0.20224719101123595, 'f': 0.22784809634593825}}]
8
@@@@@@@
Controversial artist John Currin painted ‘Bea Arthur Naked’ in 1991, it features the elderly star wearing a blank expression and sagging breasts.Maude debuted on CBS in 1972 and became one of the toprated sitcoms on U.S. television during its sixyear run.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.1388888888888889, 'p': 0.1282051282051282, 'f': 0.13333332834133352}, 'rouge-2': {'r': 0.023809523809523808, 'p': 0.023809523809523808, 'f': 0.023809518809524855}, 'rouge-l': {'r': 0.1111111111111111, 'p': 0.10256410256410256, 'f': 0.1066666616746669}}]
9
@@@@@@@
Financial problems plaguing Caesars Entertainment and its casino empire in Las Vegas have the company considering a trip to bankruptcy court, possibly as early as Thursday.U.S. casinohotel companies are dependent on extra cash in a person's pocket, but perhaps none more than Caesars, which waded into the recent economic downturn already burdened by more debt than any of them  a byproduct of a buyout in January 2008 that was largely a wager using other people's money.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.2631578947368421, 'p': 0.14925373134328357, 'f': 0.19047618585759646}, 'rouge-2': {'r': 0.04878048780487805, 'p': 0.025974025974025976, 'f': 0.03389830055012989}, 'rouge-l': {'r': 0.21052631578947367, 'p': 0.11940298507462686, 'f': 0.15238094776235842}}]
10
@@@@@@@
WASHINGTON (CNN)  The National Transportation Safety Board began four days of hearings Tuesday on how to stem the "drastic increase" in medical helicopter accidents.The NTSB said there were 55 EMSrelated aviation accidents  both fatal and nonfatal  between January 2002 and January 2005 that could have been prevented with "simple corrective actions."
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.3142857142857143, 'p': 0.22448979591836735, 'f': 0.2619047570436508}, 'rouge-2': {'r': 0.14285714285714285, 'p': 0.09615384615384616, 'f': 0.11494252392654268}, 'rouge-l': {'r': 0.2857142857142857, 'p': 0.20408163265306123, 'f': 0.23809523323412707}}]
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001

In [192]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.472222  0.395349  0.430380  rouge-1     0
0   0.324324  0.244898  0.279070  rouge-2     0
0   0.388889  0.325581  0.354430  rouge-l     0
0   0.206897  0.130435  0.160000  rouge-1     1
0   0.071429  0.039216  0.050633  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.010000  0.014925  rouge-2  1999
0   0.212121  0.084337  0.120690  rouge-l  1999
0   0.375000  0.428571  0.400000  rouge-1  2000
0   0.187500  0.230769  0.206897  rouge-2  2000
0   0.225000  0.257143  0.240000  rouge-l  2000

[6003 rows x 5 columns]

In [193]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.378122  0.311181  0.328176  1000.0
rouge-2  0.173525  0.137023  0.145122  1000.0
rouge-l  0.306968  0.251853  0.265735  1000.0

### SBERT+KMeans+CustomFeatures - Validation data

In [266]:
r_metric_all={}
def summarize_dataset_sample():
    i=0
    for article,highlights,sid in zip(dataset_sample_val['article'],dataset_sample_val['highlights'],dataset_sample_val['id']):
        i+=1
        print(i)
        article_processed=text_preprocess(article)
        article_processed_more=text_preprocess_more(article_processed)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        n_clusters = 2
        nos=1
        y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
        df=getSentenceFeatures(sentences,article_processed_more,highlights_processed)
        X=df[cols]
        y_pred=xgb_model.predict(X)
        df['sentence_rougue2_f_pred']=y_pred
        my_list=model_based_top_n(df,y_kmeans,nos)
        summary=combine_sentences(my_list,sentences)
        #print(y_kmeans)
        #print(my_list)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

1
@@@@@@@
True, overall U.S. marriage rates have fallen from 72% of U.S. adults in 1960 to just 51% in 2012, according to The Economist.Liberals are eager to talk about their favorite economic fixes for inequality raising the minimum wage, bolstering unions and taxing the rich to pay for new social benefits for families of modest means.
Will Marshall Retreat from marriage is pervading the working middle class Marriage in America is becoming another luxury item for economic elites, he says .
[{'rouge-1': {'r': 0.2608695652173913, 'p': 0.125, 'f': 0.16901408012695904}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.17391304347826086, 'p': 0.08333333333333333, 'f': 0.11267605195794503}}]
2
@@@@@@@
He may have only been looking for a bit of attention, but this cheeky lion cub bit off more than he could chew when he nipped his father's bum.The lion cub was trying to initiate a play fight with his father Xerxes by jumping on his back at Seattle Woodland Park Zoo in Washington, USA.
A cheeky lion cub bit off more than he could chew when he nipped his father's bum to get some attention He was trying to initiate a play fight with his father Xerxes by jumping on his back, but too things too far The male lion cub backed away with his tail between his legs after his father let off an almighty roar Photographer Scott Williams captured the play fighting at Seattle Woodland Park Zoo in Washington .
[{'rouge-1': {'r': 0.5873015873015873, 'p': 0.7551020408163265, 'f': 0.6607142807924108}, 'rouge-2': {'r': 0.4657534246575342, 'p': 0.6296296296296297, 'f': 0.535433065978052}, 'rouge-l': {'r': 0.5396825396825397, 'p': 0.6938775510204082, 'f': 0.6071428522209822}}]
3
@@@@@@@
Los Angeles firefighters say nearly two dozen people were injured when a commuter train struck a car near downtown Los Angeles and partially derailed.One person in the crushed car was critically injured and had to be cut out of the vehicle.
The Metro train slammed into the vehicle near the downtown USC campus Driver of the crushed car had to be cut out of the vehicle by firefighters .
[{'rouge-1': {'r': 0.6363636363636364, 'p': 0.4, 'f': 0.4912280654355187}, 'rouge-2': {'r': 0.375, 'p': 0.225, 'f': 0.28124999531250006}, 'rouge-l': {'r': 0.5909090909090909, 'p': 0.37142857142857144, 'f': 0.45614034613727306}}]
4
@@@@@@@
How did iron become scattered throughout Earth's 2,000mile (3,200km) thick mantle more than four billion years ago?By reanalysing the vapourisation point of iron, a study has determined that conditions on early Earth would have caused iron to rain down on the ground.
Scientists in New Mexico have a new theory for origin on Earth's iron Previously it was unclear how iron was scattered throughout the mantle But research suggests the vapourisation point of iron is lower than thought This means it would have turned into vapour when rocks hit early Earth It would have drifted up in plumes and then rained down on the surface .
[{'rouge-1': {'r': 0.3269230769230769, 'p': 0.4358974358974359, 'f': 0.37362636872841454}, 'rouge-2': {'r': 0.13114754098360656, 'p': 0.1951219512195122, 'f': 0.15686274029027314}, 'rouge-l': {'r': 0.2692307692307692, 'p': 0.358974358974359, 'f': 0.30769230279434856}}]
5
@@@@@@@
But David Cameron tried to bring some cheer to final Coalition Cabinet meeting today by giving all of his ministers a free bottle of beer.Nick Clegg gave each member of the Cabinet a pot of crisps from his constituency Wychwood Brewery of Witney created a special Coaleition Beer, bearing a label showing Mr Cameron and Mr Clegg waving in front of the famous Number 10 door above the slogan 'Indispensable political ale'.
Prime Minister leaves gift on Cabinet table for all 33 senior ministers Last time Tories and Lib Dems will meet in No.10 before general election Comes the morning after Cameron ruled out serving a third term as PM He named Theresa May and George Osborne as potential successors But around coffinshaped Cabinet table were others with an eye on top job .
[{'rouge-1': {'r': 0.17543859649122806, 'p': 0.17543859649122806, 'f': 0.1754385914912282}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.14035087719298245, 'p': 0.14035087719298245, 'f': 0.14035087219298265}}]
6
@@@@@@@
Emergency funding by the Government after last year's floods helped drive a 33% increase in pothole repairs, but there has been no reduction in the amount needed to bring the network in England and Wales up to scratch, said a report.The Asphalt Industry Alliance (AIA) said £12.16billion was needed to get the local road network back into 'reasonable' condition, adding that money spent on filling 2.7 million potholes in the past year had been 'wasted'.
One in six roads are still in poor shape even after millions of potholes fixed Asphalt Industry Alliance says money spent filling in 2.7million was wasted A report says that clearing the backlog of repairs could take up to 13 years .
[{'rouge-1': {'r': 0.42105263157894735, 'p': 0.25, 'f': 0.31372548552095353}, 'rouge-2': {'r': 0.0975609756097561, 'p': 0.05333333333333334, 'f': 0.06896551267092778}, 'rouge-l': {'r': 0.34210526315789475, 'p': 0.203125, 'f': 0.25490195610918887}}]
7
@@@@@@@
Fans of Leeds United have been involved in more trouble on the nation's railways than any other club in Britain, according to new information released by the British Transport Police.Fans of Birmingham City (40 incidents), Nottingham Forest (35) and Manchester City (30) complete the top five for England, with Glasgow Rangers also prominent in the tables released in response to a Freedom of Information request sent by The Sun.
Leeds fans were involved in more trouble on railways than other teams Manchester United were top of disturbances table for the Premier League Fans involved in 1,027 incidents across the last two football seasons .
[{'rouge-1': {'r': 0.5333333333333333, 'p': 0.2807017543859649, 'f': 0.3678160874355926}, 'rouge-2': {'r': 0.15625, 'p': 0.07352941176470588, 'f': 0.09999999564800019}, 'rouge-l': {'r': 0.43333333333333335, 'p': 0.22807017543859648, 'f': 0.29885057019421324}}]
8
@@@@@@@
'The whole experience only lasted a couple of minutes.'Red in tooth and claw Deep in the Maasai Mara, a lioness prepares to teach her children how to hunt Circling Captured frame by frame, the animals close in on a wildebeest separated from its herd Chase Weighing more than 500lbs when fullygrown, the wildebeest initially managed to evade capture Running The lion cubs pick up on tips they have been taught by their mother and attack from both sides Fear As the rapidfire sequence unfolds, the wildebeest kicks up dust in its frantic bid to escape Weakening The wildebeest then begins to slow, coming face to face with the animal which wants to take its life Teamwork Lionesses hunt in prides, rarely alone, and here the mother closed in to help her cubs Overpowered Outnumbered and tired, this was the moment the wildebeest could no longer put up a fight Eyeing its prey The family unit take a look before one of the animals sinks its jaws into the stricken beast Killed Lit by the golden evening sun, the wildebeest is dealt a fatal blow by the victorious hunters Dinner Wildebeest are strong and fast, but are vulnerable as soon as they are separated from the heard Beaten down South African photographer Mark Dumbleton said the hunt was over within minutes 'I couldn't believe the animal instinct they had,' he said.
Sequence of images taken in Kenya's Maasai Mara National Park It shows lioness approaching prey from behind before cubs take over Wildebeest fought  but separated from herd there was little it could do .
[{'rouge-1': {'r': 0.5, 'p': 0.10256410256410256, 'f': 0.17021276313263925}, 'rouge-2': {'r': 0.03125, 'p': 0.004484304932735426, 'f': 0.00784313506005444}, 'rouge-l': {'r': 0.34375, 'p': 0.07051282051282051, 'f': 0.11702127377093716}}]
9
@@@@@@@
Steven Muhvich, one of Mr Kanalis' best mates, said the 42yearold routinely helped out him and his father, according to Fairfax Media.Scroll down for video George Kanalis (pictured) lost his life on Thursday night after slamming his dream car into a power pole The 42yearold father died at the scene after crashing his luxury Lamborghini into a pole in Sydney's west 'He would do anything for me and my dad, I just don't know what happened to him,' Mr Muhvich said.
Tragic footage has emerged of the final moments of a man who died George Kanalis lost his life on Thursday after crashing his Lamborghini The father of two wrapped his sports car around a pole in Sydney's west The 42yearold appeared to have lost control after overtaking another car Friends say he was sort of person who 'would do anything' for his mates Police are investigating if speed or alcohol was a factor in the incident Noone else was injured in the incident on Thursday night .
[{'rouge-1': {'r': 0.40625, 'p': 0.38235294117647056, 'f': 0.3939393889439854}, 'rouge-2': {'r': 0.15853658536585366, 'p': 0.1625, 'f': 0.16049382216125607}, 'rouge-l': {'r': 0.3125, 'p': 0.29411764705882354, 'f': 0.30303029803489445}}]
10
@@@@@@@
Beautiful girls Hannah and her friend were all smiles as they posed for this snapshot before the dance Unforgettable evening Hannah tweeted that her prom night was 'epic' Making memories Hannah and one of her guy friends took a photo together before they entered the dance 'It took me a second to realize it was him at first, like to actually believe it,' she told WATE.com.First thanking, God for even blessing me to be able to go!'
Hannah Tate from Maryville, Tennessee, reached out to hairstylist Tokyo Stylez on social media in the hopes of being sent a custommade wig Tokyo, who has worked with Rihanna, Naomi Campbell, and Gabrielle Union, showed up at her door with his beauty team the day of her prom .
[{'rouge-1': {'r': 0.20454545454545456, 'p': 0.14516129032258066, 'f': 0.16981131589889656}, 'rouge-2': {'r': 0.0425531914893617, 'p': 0.02631578947368421, 'f': 0.03252032048119574}, 'rouge-l': {'r': 0.13636363636363635, 'p': 0.0967741935483871, 'f': 0.11320754231399095}}]
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000

In [267]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.260870  0.125000  0.169014  rouge-1     0
0   0.000000  0.000000  0.000000  rouge-2     0
0   0.173913  0.083333  0.112676  rouge-l     0
0   0.587302  0.755102  0.660714  rouge-1     1
0   0.465753  0.629630  0.535433  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.266667  0.177778  0.213333  rouge-2  1998
0   0.413793  0.292683  0.342857  rouge-l  1998
0   0.137931  0.117647  0.126984  rouge-1  1999
0   0.000000  0.000000  0.000000  rouge-2  1999
0   0.137931  0.117647  0.126984  rouge-l  1999

[6000 rows x 5 columns]

In [268]:
dfRogue.groupby("type").mean()

                r         p         f   sidx
type
rouge-1  0.358104  0.306757  0.316332  999.5
rouge-2  0.136584  0.114585  0.117433  999.5
rouge-l  0.272267  0.234057  0.240865  999.5

### SBERT+CustomFeatures - Validation data

In [276]:
r_metric_all={}
def summarize_dataset_sample():
    i=0
    for article,highlights,sid in zip(dataset_sample_val['article'],dataset_sample_val['highlights'],dataset_sample_val['id']):
        i+=1
        print(i)
        article_processed=text_preprocess(article)
        article_processed_more=text_preprocess_more(article_processed)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        nos=2
        y_kmeans=[0]*len(sentences)
        df=getSentenceFeatures(sentences,article_processed_more,highlights_processed)
        X=df[cols]
        y_pred=xgb_model.predict(X)
        df['sentence_rougue2_f_pred']=y_pred
        my_list=model_based_top_n(df,y_kmeans,nos)
        summary=combine_sentences(my_list,sentences)
        #print(y_kmeans)
        #print(my_list)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            #print(y_kmeans)
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

1
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
True, overall U.S. marriage rates have fallen from 72% of U.S. adults in 1960 to just 51% in 2012, according to The Economist.Liberals are eager to talk about their favorite economic fixes for inequality raising the minimum wage, bolstering unions and taxing the rich to pay for new social benefits for families of modest means.
Will Marshall Retreat from marriage is pervading the working middle class Marriage in America is becoming another luxury item for economic elites, he says .
[{'rouge-1': {'r': 0.2608695652173913, 'p': 0.125, 'f': 0.16901408012695904}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.17391304347826086, 'p': 0.08333333333333333, 'f': 0.11267605195794503}}]
2
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
The lion cub was trying to initiate a play fight with his father Xerxes by jumping on his back at Seattle Woodland Park Zoo in Washington, USA.Scroll down for video A cheeky lion cub bit off more than he could chew when he nipped his father's bum to get some attention in a Washington zoo The cub was trying to initiate a play fight but took things a step too far by taking a bite, causing father Xerxes to let off an almighty roar
A cheeky lion cub bit off more than he could chew when he nipped his father's bum to get some attention He was trying to initiate a play fight with his father Xerxes by jumping on his back, but too things too far The male lion cub backed away with his tail between his legs after his father let off an almighty roar Photographer Scott Williams captured the play fighting at Seattle Woodland Park Zoo in Washington .
[{'rouge-1': {'r': 0.7619047619047619, 'p': 0.7868852459016393, 'f': 0.7741935433883976}, 'rouge-2': {'r': 0.6027397260273972, 'p': 0.5866666666666667, 'f': 0.5945945895955077}, 'rouge-l': {'r': 0.7301587301587301, 'p': 0.7540983606557377, 'f': 0.7419354788722685}}]
3
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Los Angeles firefighters say nearly two dozen people were injured when a commuter train struck a car near downtown Los Angeles and partially derailed.Scroll down for video Los Angeles firefighters say nearly two dozen people suffered injuries when the commuter train struck a car Lenske says two of the train's three passenger cars derailed.
The Metro train slammed into the vehicle near the downtown USC campus Driver of the crushed car had to be cut out of the vehicle by firefighters .
[{'rouge-1': {'r': 0.3181818181818182, 'p': 0.2, 'f': 0.2456140303477994}, 'rouge-2': {'r': 0.041666666666666664, 'p': 0.023809523809523808, 'f': 0.03030302567493184}, 'rouge-l': {'r': 0.2727272727272727, 'p': 0.17142857142857143, 'f': 0.2105263110495538}}]
4
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
How did iron become scattered throughout Earth's 2,000mile (3,200km) thick mantle more than four billion years ago?By reanalysing the vapourisation point of iron, a study has determined that conditions on early Earth would have caused iron to rain down on the ground.
Scientists in New Mexico have a new theory for origin on Earth's iron Previously it was unclear how iron was scattered throughout the mantle But research suggests the vapourisation point of iron is lower than thought This means it would have turned into vapour when rocks hit early Earth It would have drifted up in plumes and then rained down on the surface .
[{'rouge-1': {'r': 0.3269230769230769, 'p': 0.4358974358974359, 'f': 0.37362636872841454}, 'rouge-2': {'r': 0.13114754098360656, 'p': 0.1951219512195122, 'f': 0.15686274029027314}, 'rouge-l': {'r': 0.2692307692307692, 'p': 0.358974358974359, 'f': 0.30769230279434856}}]
5
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
But David Cameron tried to bring some cheer to final Coalition Cabinet meeting today by giving all of his ministers a free bottle of beer.Nick Clegg gave each member of the Cabinet a pot of crisps from his constituency Wychwood Brewery of Witney created a special Coaleition Beer, bearing a label showing Mr Cameron and Mr Clegg waving in front of the famous Number 10 door above the slogan 'Indispensable political ale'.
Prime Minister leaves gift on Cabinet table for all 33 senior ministers Last time Tories and Lib Dems will meet in No.10 before general election Comes the morning after Cameron ruled out serving a third term as PM He named Theresa May and George Osborne as potential successors But around coffinshaped Cabinet table were others with an eye on top job .
[{'rouge-1': {'r': 0.17543859649122806, 'p': 0.17543859649122806, 'f': 0.1754385914912282}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.14035087719298245, 'p': 0.14035087719298245, 'f': 0.14035087219298265}}]
6
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Emergency funding by the Government after last year's floods helped drive a 33% increase in pothole repairs, but there has been no reduction in the amount needed to bring the network in England and Wales up to scratch, said a report.The Asphalt Industry Alliance (AIA) said £12.16billion was needed to get the local road network back into 'reasonable' condition, adding that money spent on filling 2.7 million potholes in the past year had been 'wasted'.
One in six roads are still in poor shape even after millions of potholes fixed Asphalt Industry Alliance says money spent filling in 2.7million was wasted A report says that clearing the backlog of repairs could take up to 13 years .
[{'rouge-1': {'r': 0.42105263157894735, 'p': 0.25, 'f': 0.31372548552095353}, 'rouge-2': {'r': 0.0975609756097561, 'p': 0.05333333333333334, 'f': 0.06896551267092778}, 'rouge-l': {'r': 0.34210526315789475, 'p': 0.203125, 'f': 0.25490195610918887}}]
7
@@@@@@@
[0, 0, 0, 0, 0, 0, 0]
Fans of Leeds United have been involved in more trouble on the nation's railways than any other club in Britain, according to new information released by the British Transport Police.British Transport Police say there have been 1,027 incidents involving football fans on trains in two years Fans of Leeds United have been involved in more trouble on the nation's railways than any other club The worst cases listed were four woundings and four cases of Grievous Bodily Harm on the railway network.
Leeds fans were involved in more trouble on railways than other teams Manchester United were top of disturbances table for the Premier League Fans involved in 1,027 incidents across the last two football seasons .
[{'rouge-1': {'r': 0.6333333333333333, 'p': 0.37254901960784315, 'f': 0.4691357978052127}, 'rouge-2': {'r': 0.1875, 'p': 0.09836065573770492, 'f': 0.12903225355069967}, 'rouge-l': {'r': 0.43333333333333335, 'p': 0.2549019607843137, 'f': 0.3209876496570645}}]
8
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
This was one such class in Kenya's Maasai Mara National Park, where a lioness taught her cubs how to hunt and kill a wildebeest to stay alive.Red in tooth and claw Deep in the Maasai Mara, a lioness prepares to teach her children how to hunt Circling Captured frame by frame, the animals close in on a wildebeest separated from its herd Chase Weighing more than 500lbs when fullygrown, the wildebeest initially managed to evade capture Running The lion cubs pick up on tips they have been taught by their mother and attack from both sides Fear As the rapidfire sequence unfolds, the wildebeest kicks up dust in its frantic bid to escape Weakening The wildebeest then begins to slow, coming face to face with the animal which wants to take its life Teamwork Lionesses hunt in prides, rarely alone, and here the mother closed in to help her cubs Overpowered Outnumbered and tired, this was the moment the wildebeest could no longer put up a fight Eyeing its prey The family unit take a look before one of the animals sinks its jaws into the stricken beast Killed Lit by the golden evening sun, the wildebeest is dealt a fatal blow by the victorious hunters Dinner Wildebeest are strong and fast, but are vulnerable as soon as they are separated from the heard Beaten down South African photographer Mark Dumbleton said the hunt was over within minutes 'I couldn't believe the animal instinct they had,' he said.
Sequence of images taken in Kenya's Maasai Mara National Park It shows lioness approaching prey from behind before cubs take over Wildebeest fought  but separated from herd there was little it could do .
[{'rouge-1': {'r': 0.59375, 'p': 0.11801242236024845, 'f': 0.19689118894359584}, 'rouge-2': {'r': 0.15625, 'p': 0.0211864406779661, 'f': 0.03731343073290277}, 'rouge-l': {'r': 0.40625, 'p': 0.08074534161490683, 'f': 0.13471502314048706}}]
9
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
George Kanalis died after he crashed his Lamborghini into a power pole in Sydney's west on Thursday night.Scroll down for video George Kanalis (pictured) lost his life on Thursday night after slamming his dream car into a power pole The 42yearold father died at the scene after crashing his luxury Lamborghini into a pole in Sydney's west 'He would do anything for me and my dad, I just don't know what happened to him,' Mr Muhvich said.
Tragic footage has emerged of the final moments of a man who died George Kanalis lost his life on Thursday after crashing his Lamborghini The father of two wrapped his sports car around a pole in Sydney's west The 42yearold appeared to have lost control after overtaking another car Friends say he was sort of person who 'would do anything' for his mates Police are investigating if speed or alcohol was a factor in the incident Noone else was injured in the incident on Thursday night .
[{'rouge-1': {'r': 0.40625, 'p': 0.4727272727272727, 'f': 0.43697478494456615}, 'rouge-2': {'r': 0.17073170731707318, 'p': 0.21212121212121213, 'f': 0.18918918424762612}, 'rouge-l': {'r': 0.296875, 'p': 0.34545454545454546, 'f': 0.3193277261210367}}]
10
@@@@@@@
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Scroll down for video Unforgettable moment Hannah Tate, who is battling a rare kidney cancer, posed for a preprom photo after a celebrity hairstylist gave her a complete makeover before the high school dance last Saturday So grateful The next day, the 18yearold, who goes by the Twitter name Molly Copeland, took to Twitter to thank everyone who had helped her get to her senior prom Hannah was diagnosed with cancer last November and lost her hair after chemotherapy and radiation treatments.Beautiful girls Hannah and her friend were all smiles as they posed for this snapshot before the dance Unforgettable evening Hannah tweeted that her prom night was 'epic' Making memories Hannah and one of her guy friends took a photo together before they entered the dance 'It took me a second to realize it was him at first, like to actually believe it,' she told WATE.com.
Hannah Tate from Maryville, Tennessee, reached out to hairstylist Tokyo Stylez on social media in the hopes of being sent a custommade wig Tokyo, who has worked with Rihanna, Naomi Campbell, and Gabrielle Union, showed up at her door with his beauty team the day of her prom .
[{'rouge-1': {'r': 0.2727272727272727, 'p': 0.11650485436893204, 'f': 0.1632653019279005}, 'rouge-2': {'r': 0.0425531914893617, 'p': 0.013888888888888888, 'f': 0.020942404666539405}, 'rouge-l': {'r': 0.18181818181818182, 'p': 0.07766990291262135, 'f': 0.10884353322041757}}]
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918

In [277]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.260870  0.125000  0.169014  rouge-1     0
0   0.000000  0.000000  0.000000  rouge-2     0
0   0.173913  0.083333  0.112676  rouge-l     0
0   0.761905  0.786885  0.774194  rouge-1     1
0   0.602740  0.586667  0.594595  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.200000  0.162162  0.179104  rouge-2  1998
0   0.344828  0.322581  0.333333  rouge-l  1998
0   0.448276  0.276596  0.342105  rouge-1  1999
0   0.272727  0.176471  0.214286  rouge-2  1999
0   0.413793  0.255319  0.315789  rouge-l  1999

[6000 rows x 5 columns]

In [278]:
dfRogue.groupby("type").mean()

                r         p         f   sidx
type
rouge-1  0.409703  0.319137  0.344234  999.5
rouge-2  0.168490  0.124461  0.135213  999.5
rouge-l  0.314483  0.245801  0.264552  999.5

### SBERT+KMeans+SentenceScore based on WordFreq

In [194]:
def wordfreq_ranked_top_n(y_kmeans,sentence_scores,nos):
    # Pick 1 sentence from each group
    my_list=[]
    for i in range(len(np.unique(y_kmeans))):
        my_dict={}
        for j in range(len(y_kmeans)):
            if y_kmeans[j]==i:
                #my_dict[j] =  distance.euclidean(kmeans.cluster_centers_[i],[list(sentence_scores.values())[j]])
                #my_dict[j] =  distance.euclidean(cluster_centers[i],X[j])
                my_dict[j] =  sentence_scores[j]
        #min_distance = min(my_dict.values())
        #my_list.append(min(my_dict, key=my_dict.get))
        my_list.extend([s for s,d in sorted(my_dict.items(), key=lambda item: item[1], reverse = True)][:nos])
        #print(my_dict)
    return my_list

In [195]:
embeddings.shape

(13, 768)

In [196]:
word_frequencies=getWordFreq(article0_processed_more)
ranked_sentences,sentence_scores=getSentScore(word_frequencies,sentences)
print(ranked_sentences)
print(sentence_scores)

[6, 3, 7, 12, 8, 1, 0, 5, 2, 4, 9, 10, 11]
{0: 3.6153846153846163, 1: 3.8461538461538467, 2: 3.0769230769230766, 3: 7.0769230769230775, 4: 2.6153846153846154, 5: 3.0769230769230775, 6: 8.230769230769232, 7: 6.307692307692307, 8: 4.153846153846154, 9: 2.0, 10: 1.2307692307692306, 11: 0.9999999999999998, 12: 4.769230769230769}

In [197]:
y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
y_kmeans

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [198]:
nos=1
my_list=wordfreq_ranked_top_n(y_kmeans,sentence_scores,nos)
my_list

[5, 6]

In [199]:
summary=combine_sentences(my_list,sentences)
summary

'Barcelona had planned to announce the new deal at the weekend but the unexpected prospect of winning the league on Saturday if they beat Atletico Madrid at home could even bring the announcement forward to Wednesday or Thursday.As well as being the world’s top two players Messi and Ronaldo are La Liga’s commercial colossi generating more money for their respective clubs than most of the rest of the league combined and due to an important change in Messi’s new deal Barca will now be better placed to tapin to that money stream as for the first time since signing his first deal in 2005 Messi will NOT keep 100 per cent of his image rights.'

In [200]:
r_metric=rouge_metric(summary, highlights0_processed)
r_metric

[{'rouge-1': {'r': 0.2972972972972973,
   'p': 0.12643678160919541,
   'f': 0.17741935065166506},
  'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0},
  'rouge-l': {'r': 0.24324324324324326,
   'p': 0.10344827586206896,
   'f': 0.14516128613553603}}]

In [201]:
r_metric_all={}
def summarize_dataset_sample():
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        article_processed=text_preprocess(article)
        article_processed_more=text_preprocess(article_processed)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        word_frequencies=getWordFreq(article_processed_more)
        ranked_sentences,sentence_scores=getSentScore(word_frequencies,sentences)
        n_clusters = 2
        y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
        nos=1
        my_list=wordfreq_ranked_top_n(y_kmeans,sentence_scores,nos)
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

@@@@@@@
"I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month.This material may not be published, broadcast, rewritten, or redistributed.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.08333333333333333, 'p': 0.07142857142857142, 'f': 0.07692307195266304}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.05555555555555555, 'p': 0.047619047619047616, 'f': 0.05128204631163757}}]
@@@@@@@
The two also are suspected in other shootings and murders in Tacoma, Washington, Montgomery, Alabama, and the Washington, D.C., area.The letter, addressed to the chief judge of the Prince William County Circuit Court, says the court must hold a hearing within 10 days of receiving the letter, and must set an execution date no later than 60 days after the hearing.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.1724137931034483, 'p': 0.10204081632653061, 'f': 0.1282051235338595}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.015873015873015872, 'f': 0.02197801771766777}, 'rouge-l': {'r': 0.13793103448275862, 'p': 0.08163265306122448, 'f': 0.10256409789283387}}]
@@@@@@@
The former Rangers chief executive (right) came to the defense of the existing regime at Ibrox Green came to the defence of Newcastle chairman Mike Ashley (left) after saying that he did not like him Pausing for dramatic effect throughout Green, in hospital for a knee operation, said 'Days like today make me think I should go back (to Rangers).'Derek Llambias (Chief Executive) might have had a charisma bypass, but actually he is a good guy doing a good job.
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.35714285714285715, 'p': 0.2898550724637681, 'f': 0.31999999505408006}, 'rouge-2': {'r': 0.08064516129032258, 'p': 0.06493506493506493, 'f': 0.0719424411013926}, 'rouge-l': {'r': 0.25, 'p': 0.2028985507246377, 'f': 0.2239999950540801}}]
@@@@@@@
By Andrew Levy PUBLISHED 1435 EST, 21 February 2013 | UPDATED 1844 EST, 21 February 2013 Suspect Kenneth Gillespie who is linked to a raid on a McDonalds in Ipswich could not be charged despite having £5,500 in cash on him When robbers snatched £17,000 from a security guard outside a McDonald’s, police had a pretty good idea who might have done it.If any new evidence comes to light, the case can be reviewed.’
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.27419354838709675, 'p': 0.2698412698412698, 'f': 0.27199999500032007}, 'rouge-2': {'r': 0.038461538461538464, 'p': 0.041666666666666664, 'f': 0.039999995008000624}, 'rouge-l': {'r': 0.1935483870967742, 'p': 0.19047619047619047, 'f': 0.19199999500032014}}]
@@@@@@@
Downing Street said the regime is poised to be rolled out across Gatwick and the Eurostar terminal The screening techniques include a form for passengers to fill in, asking about potential symptoms of the virus The Ghanaian sports minister said he had been contacted by the Confederation of African Football (CAF), which was also said to have been in touch with the South African Football Association.They are then declared free to go, referred for further assessment, classed as low risk and sent away with information to monitor their own condition, or classed as higher risk and actively monitored.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2328767123287671, 'p': 0.22077922077922077, 'f': 0.2266666616702223}, 'rouge-2': {'r': 0.033707865168539325, 'p': 0.031578947368421054, 'f': 0.03260869065749132}, 'rouge-l': {'r': 0.1095890410958904, 'p': 0.1038961038961039, 'f': 0.10666666167022246}}]
@@@@@@@
When the first note of the national anthem played, every single person stood up, held on to each other with something approaching fervour, and then absolutely belted out the anthem, every word of it as if their lives depended on it.At that point Rafa said to me, quite dryly ‘If it stays like this, you won’t be going back down to Rio tonight.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.10810810810810811, 'p': 0.07272727272727272, 'f': 0.08695651693052957}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.08108108108108109, 'p': 0.05454545454545454, 'f': 0.06521738649574706}}]
@@@@@@@
He said “I’m sorry,” and ran out,’ she said.She also started to feel horny, you can say,’ Continuing to refer to himself in the third person, Lucas Cesar then describes the sexual assault, claiming he had sexual intercourse with her for two minutes before leaving the apartment – but not before rummaging through her daughter’s purse and stealing $20, according to the New York Post.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.17391304347826086, 'p': 0.21818181818181817, 'f': 0.19354838216051}, 'rouge-2': {'r': 0.011904761904761904, 'p': 0.015384615384615385, 'f': 0.013422813873250753}, 'rouge-l': {'r': 0.10144927536231885, 'p': 0.12727272727272726, 'f': 0.11290322087018752}}]
@@@@@@@
Golden Girls Arthur, far right, with her costars in the 80s TV show Betty White, left, and Rue Mcclanahan In the early 1970s, she appeared on the groundbreaking television comedy 'All in the Family' as Edith Bunker's fiercely liberal cousin Maude.The procedure was legal in New York state, where the show was set, but not nationwide.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.19444444444444445, 'p': 0.14285714285714285, 'f': 0.16470587746989632}, 'rouge-2': {'r': 0.047619047619047616, 'p': 0.03636363636363636, 'f': 0.041237108491870074}, 'rouge-l': {'r': 0.19444444444444445, 'p': 0.14285714285714285, 'f': 0.16470587746989632}}]
@@@@@@@
Caesars Palace hotel and casino, in Las Vegas is pictured, as they try and find a way of cutting debt 'Caesars is, in a certain sense, a Nevada version of 'too big to fail,' said Michael Green, a history professor with the University of Nevada, Las Vegas.Regardless of the maneuvers, 'the fundamentals were not there to support the amount of debt that they had,' said Keith Foley, an analyst with Moody's Investors Service.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.15789473684210525, 'p': 0.10714285714285714, 'f': 0.12765956965142616}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.13157894736842105, 'p': 0.08928571428571429, 'f': 0.10638297390674535}}]
@@@@@@@
The three crashes occurred near South Padre Island, Texas, in February 2008; Huntsville, Texas, in June; and Whittier, Alaska, in December 2007.Expert witnesses such as pilots, medical personnel, managers and Federal Aviation Administration officials will give sworn testimony on what has been an "ongoing concern" of the safety board, which issued a report on emergency medical services operations in 2006.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.17142857142857143, 'p': 0.1111111111111111, 'f': 0.13483145590203274}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.11428571428571428, 'p': 0.07407407407407407, 'f': 0.08988763567731373}}]

In [202]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.083333  0.071429  0.076923  rouge-1     0
0   0.000000  0.000000  0.000000  rouge-2     0
0   0.055556  0.047619  0.051282  rouge-l     0
0   0.172414  0.102041  0.128205  rouge-1     1
0   0.035714  0.015873  0.021978  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.000000  0.000000  0.000000  rouge-2  1999
0   0.181818  0.080000  0.111111  rouge-l  1999
0   0.275000  0.166667  0.207547  rouge-1  2000
0   0.020833  0.012821  0.015873  rouge-2  2000
0   0.175000  0.106061  0.132075  rouge-l  2000

[6003 rows x 5 columns]

In [203]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.303362  0.198686  0.231488  1000.0
rouge-2  0.092424  0.055137  0.065870  1000.0
rouge-l  0.229243  0.149689  0.174492  1000.0

### SBERT+KMeans+PageRank

In [205]:
r_metric_all={}
def summarize_dataset_sample():
    i=0
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        i+=1
        print(i)
        article_processed=text_preprocess(article)
        article_processed_more=text_preprocess(article_processed)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        sim_matrix=cosine_similarity_matrix(sentences,embeddings)
        sim_matrix=np.nan_to_num(sim_matrix)
        ranked_sentences,sentence_scores=page_ranked_sentence(sim_matrix,sentences)
        n_clusters = 2
        y_kmeans,cluster_centers=cluster_kmeans(embeddings,n_clusters)
        nos=1
        my_list=wordfreq_ranked_top_n(y_kmeans,sentence_scores,nos)
        summary=combine_sentences(my_list,sentences)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
summarize_dataset_sample()

1
@@@@@@@
LONDON, England (Reuters)  Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him."Hopefully none of you will be reading about it."
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.3055555555555556, 'p': 0.2558139534883721, 'f': 0.27848100769748446}, 'rouge-2': {'r': 0.21621621621621623, 'p': 0.17777777777777778, 'f': 0.19512194626710305}, 'rouge-l': {'r': 0.3055555555555556, 'p': 0.2558139534883721, 'f': 0.27848100769748446}}]
2
@@@@@@@
WASHINGTON (CNN)  Virginia prosecutors are asking a state court to set a November 9 execution date for John Allen Muhammad, convicted in a series of sniperstyle shootings that terrorized the Washington area in 2002.In a letter dated Wednesday, Senior Assistant Attorney General Katherine B. Burnett said the November date "has been carefully coordinated with the governor's office to insure his availability for any clemency petition Muhammad may wish to pursue."
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.27586206896551724, 'p': 0.13114754098360656, 'f': 0.17777777340987666}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.014084507042253521, 'f': 0.020202016145292108}, 'rouge-l': {'r': 0.2413793103448276, 'p': 0.11475409836065574, 'f': 0.15555555118765446}}]
3
@@@@@@@
A muchderided figure following the doomed takeover which left Rangers back at the financial precipice, however, Green claimed Mike Ashley is the right man to turn the club around.'But Glazer put more money into that club than Martin Edwards ever did.
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.16071428571428573, 'p': 0.23684210526315788, 'f': 0.19148935688546867}, 'rouge-2': {'r': 0.04838709677419355, 'p': 0.07317073170731707, 'f': 0.05825242239230881}, 'rouge-l': {'r': 0.14285714285714285, 'p': 0.21052631578947367, 'f': 0.17021276114078782}}]
4
@@@@@@@
By Andrew Levy PUBLISHED 1435 EST, 21 February 2013 | UPDATED 1844 EST, 21 February 2013 Suspect Kenneth Gillespie who is linked to a raid on a McDonalds in Ipswich could not be charged despite having £5,500 in cash on him When robbers snatched £17,000 from a security guard outside a McDonald’s, police had a pretty good idea who might have done it.But prosecutor Karly McGuire said the case had not met the burden of proof required to bring charges.
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.2903225806451613, 'p': 0.2727272727272727, 'f': 0.2812499950048829}, 'rouge-2': {'r': 0.038461538461538464, 'p': 0.03896103896103896, 'f': 0.0387096724195636}, 'rouge-l': {'r': 0.1935483870967742, 'p': 0.18181818181818182, 'f': 0.18749999500488296}}]
5
@@@@@@@
Cheick Tiote, Papiss Cisse and Wilfried Bony are among the players who will be checked for the virus, after competing in African Nations Cup qualifiers.'He will go through normal fitness checks and medical tests which any player returning from an international game would go through.'
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.2465753424657534, 'p': 0.42857142857142855, 'f': 0.31304347362419666}, 'rouge-2': {'r': 0.06741573033707865, 'p': 0.13333333333333333, 'f': 0.08955223434506593}, 'rouge-l': {'r': 0.1506849315068493, 'p': 0.2619047619047619, 'f': 0.19130434318941408}}]
6
@@@@@@@
Having tipped Brazil to win the World Cup I must say their opening performance against Croatia was an anticlimax that highlighted vulnerabilities, particularly in defence.That’s the mark of a really great player, doing not much then contributing something significant when it matters.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.24324324324324326, 'p': 0.21428571428571427, 'f': 0.22784809628585176}, 'rouge-2': {'r': 0.10810810810810811, 'p': 0.09523809523809523, 'f': 0.10126581780483922}, 'rouge-l': {'r': 0.16216216216216217, 'p': 0.14285714285714285, 'f': 0.15189872919724418}}]
7
@@@@@@@
Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.And as much as she fears it, she may have to face her attacker in court.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.36231884057971014, 'p': 0.36231884057971014, 'f': 0.3623188355797102}, 'rouge-2': {'r': 0.07142857142857142, 'p': 0.06593406593406594, 'f': 0.06857142357942893}, 'rouge-l': {'r': 0.18840579710144928, 'p': 0.18840579710144928, 'f': 0.18840579210144942}}]
8
@@@@@@@
During her career, Arthur won acclaim for her comic timing and deadpan delivery in roles such as Maude, right 'It’s historically significant  it’s radical to sexualize someone people think of as asexual,' spokesman Koji Inoue told The New York Post.Maude debuted on CBS in 1972 and became one of the toprated sitcoms on U.S. television during its sixyear run.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.2222222222222222, 'p': 0.14545454545454545, 'f': 0.17582417104214482}, 'rouge-2': {'r': 0.023809523809523808, 'p': 0.016666666666666666, 'f': 0.01960783829296544}, 'rouge-l': {'r': 0.16666666666666666, 'p': 0.10909090909090909, 'f': 0.13186812708610088}}]
9
@@@@@@@
Caesars Palace hotel and casino, in Las Vegas is pictured, as they try and find a way of cutting debt 'Caesars is, in a certain sense, a Nevada version of 'too big to fail,' said Michael Green, a history professor with the University of Nevada, Las Vegas.U.S. casinohotel companies are dependent on extra cash in a person's pocket, but perhaps none more than Caesars, which waded into the recent economic downturn already burdened by more debt than any of them  a byproduct of a buyout in January 2008 that was largely a wager using other people's money.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.23684210526315788, 'p': 0.11538461538461539, 'f': 0.1551724093876339}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.21052631578947367, 'p': 0.10256410256410256, 'f': 0.1379310300772891}}]
10
@@@@@@@
WASHINGTON (CNN)  The National Transportation Safety Board began four days of hearings Tuesday on how to stem the "drastic increase" in medical helicopter accidents.The pilot, a paramedic and a flight nurse were killed, the NTSB said.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.3142857142857143, 'p': 0.3235294117647059, 'f': 0.3188405747111952}, 'rouge-2': {'r': 0.14285714285714285, 'p': 0.1388888888888889, 'f': 0.14084506542352726}, 'rouge-l': {'r': 0.2857142857142857, 'p': 0.29411764705882354, 'f': 0.2898550674648184}}]
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001

In [206]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.305556  0.255814  0.278481  rouge-1     0
0   0.216216  0.177778  0.195122  rouge-2     0
0   0.305556  0.255814  0.278481  rouge-l     0
0   0.275862  0.131148  0.177778  rouge-1     1
0   0.035714  0.014085  0.020202  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.029412  0.009434  0.014286  rouge-2  1999
0   0.212121  0.080460  0.116667  rouge-l  1999
0   0.300000  0.240000  0.266667  rouge-1  2000
0   0.041667  0.033333  0.037037  rouge-2  2000
0   0.250000  0.200000  0.222222  rouge-l  2000

[6003 rows x 5 columns]

In [207]:
dfRogue.groupby("type").mean()

                r         p         f    sidx
type
rouge-1  0.303346  0.229914  0.250704  1000.0
rouge-2  0.093449  0.064396  0.072155  1000.0
rouge-l  0.229424  0.172799  0.188756  1000.0

### Topic Modeling

In [240]:
article0_processed=text_preprocess(article0)
sentences=text_to_sentences(article0_processed)

In [241]:
sentences_corpus=[]
for s in sentences:
    s_processed_more=text_preprocess_more(s)
    words_corpus=[]
    for word in nltk.word_tokenize(s_processed_more):
        if word not in stopwords:
            words_corpus.append(word)
    sentences_corpus.append(words_corpus)

In [242]:
# Create Dictionary
id2word = corpora.Dictionary(sentences_corpus)
# Term Document Frequency
doc_term_matrix = [id2word.doc2bow(s) for s in sentences_corpus]

In [243]:
print(doc_term_matrix[0])

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1)]

In [244]:
# number of topics
num_topics = 2
# Build LDA model
lda_model = gensim.models.LdaMulticore(corpus=doc_term_matrix,id2word=id2word,num_topics=num_topics)

In [245]:
# Print the Keyword in the 4 topics
print(lda_model.print_topics())
print(lda_model.print_topics(num_topics=num_topics,num_words=5))
doc_lda = lda_model[doc_term_matrix]
doc_lda

[(0, '0.038*"messi" + 0.026*"club" + 0.020*"player" + 0.019*"new" + 0.014*"barca" + 0.014*"deal" + 0.013*"season" + 0.012*"world" + 0.011*"madrid" + 0.011*"week"'), (1, '0.023*"messi" + 0.017*"new" + 0.016*"barcelona" + 0.014*"deal" + 0.013*"barca" + 0.013*"club" + 0.012*"madrid" + 0.011*"aguero" + 0.011*"would" + 0.011*"player"')]
[(0, '0.038*"messi" + 0.026*"club" + 0.020*"player" + 0.019*"new" + 0.014*"barca"'), (1, '0.023*"messi" + 0.017*"new" + 0.016*"barcelona" + 0.014*"deal" + 0.013*"barca"')]

In [246]:
count=0
for i in doc_lda:
    print("doc : ",count,i)
    count+=1

doc :  0 [(0, 0.9096905), (1, 0.09030951)]
doc :  1 [(0, 0.9718857), (1, 0.028114278)]
doc :  2 [(0, 0.9731891), (1, 0.02681087)]
doc :  3 [(0, 0.0390107), (1, 0.96098924)]
doc :  4 [(0, 0.9636352), (1, 0.0363648)]
doc :  5 [(0, 0.028434727), (1, 0.9715653)]
doc :  6 [(0, 0.98237646), (1, 0.017623534)]
doc :  7 [(0, 0.977697), (1, 0.02230302)]
doc :  8 [(0, 0.97008616), (1, 0.029913867)]
doc :  9 [(0, 0.6524066), (1, 0.3475934)]
doc :  10 [(0, 0.04778694), (1, 0.9522131)]
doc :  11 [(0, 0.04631028), (1, 0.9536897)]
doc :  12 [(0, 0.9577711), (1, 0.04222888)]

In [247]:
labels=[]
for i in doc_lda:
    dict_i=dict(i)
    print(dict_i)
    l=[sent for sent,rank in sorted(dict_i.items(), key=lambda item: item[1], reverse = True)][0]
    labels.append(l)
labels

{0: 0.90973556, 1: 0.09026439}
{0: 0.97189444, 1: 0.028105572}
{0: 0.9731827, 1: 0.026817318}
{0: 0.039017905, 1: 0.9609821}
{0: 0.9636494, 1: 0.036350578}
{0: 0.02843256, 1: 0.97156745}
{0: 0.9823829, 1: 0.017617106}
{0: 0.97769547, 1: 0.02230456}
{0: 0.97008634, 1: 0.029913612}
{0: 0.65917826, 1: 0.34082174}
{0: 0.047807585, 1: 0.9521924}
{0: 0.04631929, 1: 0.9536807}
{0: 0.95776397, 1: 0.042236026}

[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0]

### SBERT+TopicModel+PageRank

In [253]:
def topic_assignment(sentences,num_topics):
    ## Topic Model
    sentences_corpus=[]
    for s in sentences:
        s_processed_more=text_preprocess_more(s)
        words_corpus=[]
        for word in nltk.word_tokenize(s_processed_more):
            if word not in stopwords:
                words_corpus.append(word)
        sentences_corpus.append(words_corpus)
    # Create Dictionary
    id2word = corpora.Dictionary(sentences_corpus)
    # Term Document Frequency
    doc_term_matrix = [id2word.doc2bow(s) for s in sentences_corpus]
    # number of topics
    #num_topics = 2
    # Build LDA model
    lda_model = gensim.models.LdaMulticore(corpus=doc_term_matrix,id2word=id2word,num_topics=num_topics)
    doc_lda = lda_model[doc_term_matrix]
    labels=[]
    for i in doc_lda:
        dict_i=dict(i)
        #print(dict_i)
        l=[sent for sent,rank in sorted(dict_i.items(), key=lambda item: item[1], reverse = True)][0]
        labels.append(l)
    return labels

In [255]:
y_kmeans=topic_assignment(sentences,2)
y_kmeans

[1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1]

In [256]:
my_list=wordfreq_ranked_top_n(y_kmeans,sentence_scores,nos)
my_list

[7, 6]

In [257]:
summary=combine_sentences(my_list,sentences)
summary

"As well as being the world’s top two players Messi and Ronaldo are La Liga’s commercial colossi generating more money for their respective clubs than most of the rest of the league combined and due to an important change in Messi’s new deal Barca will now be better placed to tapin to that money stream as for the first time since signing his first deal in 2005 Messi will NOT keep 100 per cent of his image rights.Stuttering Messi has had a quiet season by his own extremely high standards Record Messi is now Barca's highest ever scorer after bagging 371 goals for the club This is Messi’s seventh contract renewal in 11 years and his camp have finally given in to club demands that he share his rights."

In [258]:
rouge_metric(summary, highlights_processed)

[{'rouge-1': {'r': 0.2972972972972973,
   'p': 0.11458333333333333,
   'f': 0.16541352981853139},
  'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0},
  'rouge-l': {'r': 0.2702702702702703,
   'p': 0.10416666666666667,
   'f': 0.150375935833569}}]

In [269]:
r_metric_all={}
def summarize_dataset_sample():
    i=0
    for article,highlights,sid in zip(dataset_sample['article'],dataset_sample['highlights'],dataset_sample['id']):
        i+=1
        print(i)
        article_processed=text_preprocess(article)
        highlights_processed=text_preprocess(highlights)
        sentences=text_to_sentences(article_processed)
        embeddings = model.encode(sentences)
        sim_matrix=cosine_similarity_matrix(sentences,embeddings)
        sim_matrix=np.nan_to_num(sim_matrix)
        ranked_sentences,sentence_scores=page_ranked_sentence(sim_matrix,sentences)
        n_clusters = 2
        nos=1
        y_kmeans=topic_assignment(sentences,n_clusters)
        my_list=wordfreq_ranked_top_n(y_kmeans,sentence_scores,nos)
        summary=combine_sentences(my_list,sentences)
        #print(y_kmeans)
        #print(my_list)
        r_metric=rouge_metric(summary, highlights_processed)
        r_metric_all[sid]=r_metric
        if len(r_metric_all) <= 10:
            print("@@@@@@@")
            print(summary)
            print(highlights_processed)
            print(r_metric)
        if len(r_metric_all) > 200:
            break
summarize_dataset_sample()

1
@@@@@@@
LONDON, England (Reuters)  Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him."People are always looking to say 'kid star goes off the rails,'" he told reporters last month.
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday Young actor says he has no plans to fritter his cash away Radcliffe's earnings from first five Potter films have been held in trust fund .
[{'rouge-1': {'r': 0.3055555555555556, 'p': 0.2391304347826087, 'f': 0.2682926780011899}, 'rouge-2': {'r': 0.21621621621621623, 'p': 0.15384615384615385, 'f': 0.17977527604090407}, 'rouge-l': {'r': 0.3055555555555556, 'p': 0.2391304347826087, 'f': 0.2682926780011899}}]
2
@@@@@@@
WASHINGTON (CNN)  Virginia prosecutors are asking a state court to set a November 9 execution date for John Allen Muhammad, convicted in a series of sniperstyle shootings that terrorized the Washington area in 2002.Ultimately, Muhammad was convicted of the Meyers' killing and of one Maryland murder, which prosecutors there said was "insurance" in case the Virginia conviction was overturned.
Execution date proposed for convicted D.C. sniper John Allen Muhammad Police say Muhammad, Lee Boyd Malvo shot 13 people, killing 10 Muhammad's lawyer says he will seek clemency .
[{'rouge-1': {'r': 0.27586206896551724, 'p': 0.1702127659574468, 'f': 0.21052631106994468}, 'rouge-2': {'r': 0.03571428571428571, 'p': 0.01694915254237288, 'f': 0.02298850138195353}, 'rouge-l': {'r': 0.27586206896551724, 'p': 0.1702127659574468, 'f': 0.21052631106994468}}]
3
@@@@@@@
A muchderided figure following the doomed takeover which left Rangers back at the financial precipice, however, Green claimed Mike Ashley is the right man to turn the club around.Green said that current chief exec Derek Llambias (right) was a good guy despite having a 'charisma bypass' Green then hit out at wouldbe owner Dave King by mentioning he has numerous convictions against his name 'I met him when I took Llambias into Ibrox when we did the deal for the naming rights (sold to Sports Direct for a pound).
ExRangers chief Charles Green defended the existing hierarchy at Ibrox Green 'I don't like Mike Ashley, but I believe he is the right man for the job' Speaking from a hospital bed Green also denied rumours of his arrest The 61yearold then took a swipe at potential Gers owner Dave King by saying that Sandy Easdale should be given more respect from fans .
[{'rouge-1': {'r': 0.39285714285714285, 'p': 0.2894736842105263, 'f': 0.33333332844811764}, 'rouge-2': {'r': 0.11290322580645161, 'p': 0.07865168539325842, 'f': 0.09271522694794114}, 'rouge-l': {'r': 0.23214285714285715, 'p': 0.17105263157894737, 'f': 0.19696969208448128}}]
4
@@@@@@@
By Andrew Levy PUBLISHED 1435 EST, 21 February 2013 | UPDATED 1844 EST, 21 February 2013 Suspect Kenneth Gillespie who is linked to a raid on a McDonalds in Ipswich could not be charged despite having £5,500 in cash on him When robbers snatched £17,000 from a security guard outside a McDonald’s, police had a pretty good idea who might have done it.Accomplice A man pictured on CCTV believed to be linked to the robbery at McDonald's in Ipswich, Suffolk, in November 2011 Crime scene
Kenneth Gillespie was on day release from Hollesley Bay open prison Gillespie was serving a life sentence for a string of armed robberies He was working at Ipswich Town Football Club where cash was found It is believed it was part of £17,000 stolen from a G4S security guard Gillespie has since absconded from a prison in Boston, Lincolnshire One suspect matched a witness description of a man with one leg Magistrates have ordered the cash to be repaid to G4S .
[{'rouge-1': {'r': 0.3225806451612903, 'p': 0.29411764705882354, 'f': 0.30769230270295866}, 'rouge-2': {'r': 0.05128205128205128, 'p': 0.04938271604938271, 'f': 0.05031446041058552}, 'rouge-l': {'r': 0.22580645161290322, 'p': 0.20588235294117646, 'f': 0.2153846103952664}}]
5
@@@@@@@
Cheick Tiote, Papiss Cisse and Wilfried Bony are among the players who will be checked for the virus, after competing in African Nations Cup qualifiers.Manager Alan Pardew said Newcastle FC would be 'naive' not to take precautions following the Ebola outbreak They said 'Players are probably more closely monitored healthwise than any individuals in the country.
Players have been taking part in African Nations Cup qualifiers this week Newcastle's Alan Pardew said club would be 'naive' not to have concerns 'Strategy' in place for Ivory Coast's Cheick Tiote and Senegal's Papiss Cisse Ivory Coast's Wilfried Bony will also be put through tests by Swansea City Manchester City refused to say if Yaya Touré would be tested for Ebola Public Health England introduced screening at Heathrow earlier this week Officials say regime will extend to Birmingham and Manchester airports There are already plans to roll out screening at Gatwick and Eurostar .
[{'rouge-1': {'r': 0.3150684931506849, 'p': 0.46, 'f': 0.37398373501222826}, 'rouge-2': {'r': 0.1348314606741573, 'p': 0.21428571428571427, 'f': 0.16551723663828788}, 'rouge-l': {'r': 0.2328767123287671, 'p': 0.34, 'f': 0.27642275940247213}}]
6
@@@@@@@
Having tipped Brazil to win the World Cup I must say their opening performance against Croatia was an anticlimax that highlighted vulnerabilities, particularly in defence.The Brazil back four were visibly uncomfortable with the ball being crossed into the area.
Brazil's victory over Croatia was an anticlimax Ferdinand watched the match with Fabio and Rafael da Silva Brazil were lucky to win and vulnerable defensively There are no billboards or posters in Brazil, just people who love football .
[{'rouge-1': {'r': 0.2972972972972973, 'p': 0.2972972972972973, 'f': 0.2972972922972974}, 'rouge-2': {'r': 0.10810810810810811, 'p': 0.10256410256410256, 'f': 0.10526315289819968}, 'rouge-l': {'r': 0.1891891891891892, 'p': 0.1891891891891892, 'f': 0.1891891841891893}}]
7
@@@@@@@
By Daily Mail Reporters PUBLISHED 2040 EST, 26 January 2014 | UPDATED 0631 EST, 27 January 2014 Shattered Kia Graves is a former actress who once had a successful career with a modeling agency but since she was raped in 2012, she hasn't worked and her socially life has been shattered A woman who was attacked and raped in her Manhattan apartment in 2012 has come forward to detail the horrific night a teenage pizza boy allegedly assaulted her as her 7yearold daughter slept in the bed beside her.Charged Pizza delivery boy Cesar Lucas, who was 16 at the time, has pleaded not guilty to rape in court but confessed to 'sexual intercorse' with the 35yearold in a handwritten note released by police Graves still lives in the apartment where she was rapeda building in which she grew up and where her mother also lives to this dayand her deepest fear is that her attacker, who knows where she lives, will somehow come to find her.
Cesar Lucas, now 17, is accused of sexually assaulting 35yearold former actress Kia Graves as she slept in her Manhattan apartment in 2012 Graves says she was raped beside her sleeping 7yearold daughter Graves has been unable to work, spends her days in fear and has been plagued by nightmares since the attack The parttime pizza delivery boy pleaded not guilty, which could mean Graves will have to testify Lucas allegedly confessed he to the rape, and said he did it because he was 'feeling horny'
[{'rouge-1': {'r': 0.5507246376811594, 'p': 0.3392857142857143, 'f': 0.4198894980446263}, 'rouge-2': {'r': 0.19047619047619047, 'p': 0.1, 'f': 0.1311475364686914}, 'rouge-l': {'r': 0.3188405797101449, 'p': 0.19642857142857142, 'f': 0.24309391793412904}}]
8
@@@@@@@
During her career, Arthur won acclaim for her comic timing and deadpan delivery in roles such as Maude, right 'It’s historically significant  it’s radical to sexualize someone people think of as asexual,' spokesman Koji Inoue told The New York Post.Golden Girls Arthur, far right, with her costars in the 80s TV show Betty White, left, and Rue Mcclanahan In the early 1970s, she appeared on the groundbreaking television comedy 'All in the Family' as Edith Bunker's fiercely liberal cousin Maude.
The painting of the former 'Golden Girl' was called sexist and misogynistic when first unveiled in the early 90s Christie's had hoped the painting might sell for as much as $2.5m in auction Bea Arthur died of cancer in 2009 aged 86 .
[{'rouge-1': {'r': 0.25, 'p': 0.1267605633802817, 'f': 0.1682242946004019}, 'rouge-2': {'r': 0.047619047619047616, 'p': 0.02531645569620253, 'f': 0.03305784670719276}, 'rouge-l': {'r': 0.16666666666666666, 'p': 0.08450704225352113, 'f': 0.11214952824526178}}]
9
@@@@@@@
Caesars Palace hotel and casino, in Las Vegas is pictured, as they try and find a way of cutting debt 'Caesars is, in a certain sense, a Nevada version of 'too big to fail,' said Michael Green, a history professor with the University of Nevada, Las Vegas.U.S. casinohotel companies are dependent on extra cash in a person's pocket, but perhaps none more than Caesars, which waded into the recent economic downturn already burdened by more debt than any of them  a byproduct of a buyout in January 2008 that was largely a wager using other people's money.
Last year the company closed properties in Atlantic City, London and Mississippi By declaring bankruptcy, the company could cut existing debt by around $10billion Caesars Entertainment said it would cut global workforce by less than 1% The company never recovered from 2008 recession .
[{'rouge-1': {'r': 0.23684210526315788, 'p': 0.11538461538461539, 'f': 0.1551724093876339}, 'rouge-2': {'r': 0.0, 'p': 0.0, 'f': 0.0}, 'rouge-l': {'r': 0.21052631578947367, 'p': 0.10256410256410256, 'f': 0.1379310300772891}}]
10
@@@@@@@
WASHINGTON (CNN)  The National Transportation Safety Board began four days of hearings Tuesday on how to stem the "drastic increase" in medical helicopter accidents.Watch Sumwalt's remarks at hearing » Flying at night in poor weather conditions likely contributed to the crashes in Texas and Alaska of three medical helicopters that killed 11 people, the NTSB said.
Transportation safety board beginning four days of hearings Board examines reported "drastic increase" in accidents and deaths Nine air ambulance crashes killed 35 people during oneyear period Board's 2006 safety recommendations not fully implemented, it says .
[{'rouge-1': {'r': 0.37142857142857144, 'p': 0.2653061224489796, 'f': 0.30952380466269847}, 'rouge-2': {'r': 0.14285714285714285, 'p': 0.08928571428571429, 'f': 0.10989010515638228}, 'rouge-l': {'r': 0.3142857142857143, 'p': 0.22448979591836735, 'f': 0.2619047570436508}}]
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201

In [270]:
dfRogue=pd.DataFrame()
i=0
for a in r_metric_all.values():
    #print(a)
    #print(pd.DataFrame(a))
    for b in a:
        for c,d in b.items():
            dfTemp=pd.DataFrame([d])
            dfTemp["type"]=c
            dfTemp["sidx"]=i
            #print(dfTemp)
            dfRogue=pd.concat([dfRogue,dfTemp])
    i+=1
dfRogue

           r         p         f     type  sidx
0   0.305556  0.239130  0.268293  rouge-1     0
0   0.216216  0.153846  0.179775  rouge-2     0
0   0.305556  0.239130  0.268293  rouge-l     0
0   0.275862  0.170213  0.210526  rouge-1     1
0   0.035714  0.016949  0.022989  rouge-2     1
..       ...       ...       ...      ...   ...
0   0.400000  0.313725  0.351648  rouge-2   199
0   0.588235  0.512821  0.547945  rouge-l   199
0   0.277778  0.294118  0.285714  rouge-1   200
0   0.032258  0.033898  0.033058  rouge-2   200
0   0.222222  0.235294  0.228571  rouge-l   200

[603 rows x 5 columns]

In [271]:
dfRogue.groupby("type").mean()

                r         p         f   sidx
type
rouge-1  0.330311  0.234743  0.264588  100.0
rouge-2  0.106808  0.069917  0.080841  100.0
rouge-l  0.246169  0.175020  0.197256  100.0

### TFIDF+TopicModel+PageRank